/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.Produto;

import controller.ProdutoController;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Produtos;
import model.Usuario;
import telas.ProdutosOrcamento.IProdutoOrcamento;
import telas.Relatorios.Vendas.IMapaVendas;
import telas.Usuarios.UsuarioLogadoBean;
import util.LimiteTextoJedit;

/**
 *
 * @author Wolverine
 */
public class FrmConsultaProduto extends javax.swing.JFrame implements IProdutos {
    
    private List<Produtos> listaProduto;
    private ConsultaProdutoTableModel modelProduto;
    private UsuarioLogadoBean usuarioLogadoBean;
    private IProdutoOrcamento telaProdutoOrcamento;
    private String tipoFiltro;
    /**
     * Creates new form FrmConsultaCliente
     */
    public FrmConsultaProduto(UsuarioLogadoBean usuarioLogadoBean) {
        this.usuarioLogadoBean = usuarioLogadoBean;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo/logotela.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        carregarModelProduto(descricaojTextField.getText());
        this.setVisible(true);
    }
    
    public FrmConsultaProduto(UsuarioLogadoBean usuarioLogadoBean, IProdutoOrcamento telaProdutoOrcamento, String tipoFiltro) {
        this.usuarioLogadoBean = usuarioLogadoBean;
        this.tipoFiltro = tipoFiltro;
        this.telaProdutoOrcamento = telaProdutoOrcamento;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo/logotela.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        carregarModelProduto(descricaojTextField.getText());
        limitarJText();
        this.setVisible(true);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        descricaojTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProdutosjTable = new javax.swing.JTable();
        BarradeTarefasjToolBar = new javax.swing.JToolBar();
        AdicionarjButton = new javax.swing.JButton();
        EditarjButton = new javax.swing.JButton();
        SeparadordeTarefasjSeparator1 = new javax.swing.JToolBar.Separator();
        UsuariojButton = new javax.swing.JButton();
        FecharrjButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Produtos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Pesquisar Descrição Produto");

        descricaojTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descricaojTextFieldKeyReleased(evt);
            }
        });

        ProdutosjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProdutosjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProdutosjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProdutosjTable);
        ProdutosjTable.getColumnModel().getColumn(0).setResizable(false);
        ProdutosjTable.getColumnModel().getColumn(0).setPreferredWidth(50);
        ProdutosjTable.getColumnModel().getColumn(1).setResizable(false);
        ProdutosjTable.getColumnModel().getColumn(1).setPreferredWidth(300);

        BarradeTarefasjToolBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BarradeTarefasjToolBar.setFloatable(false);
        BarradeTarefasjToolBar.setRollover(true);

        AdicionarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/adicionar.png"))); // NOI18N
        AdicionarjButton.setText("Novo");
        AdicionarjButton.setToolTipText("Adicionar novo produto");
        AdicionarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AdicionarjButton.setMaximumSize(new java.awt.Dimension(80, 90));
        AdicionarjButton.setMinimumSize(new java.awt.Dimension(80, 90));
        AdicionarjButton.setName(""); // NOI18N
        AdicionarjButton.setPreferredSize(new java.awt.Dimension(80, 90));
        AdicionarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AdicionarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarjButtonActionPerformed(evt);
            }
        });
        BarradeTarefasjToolBar.add(AdicionarjButton);

        EditarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/editar.png"))); // NOI18N
        EditarjButton.setText("Editar");
        EditarjButton.setToolTipText("Editar produto");
        EditarjButton.setEnabled(false);
        EditarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EditarjButton.setMaximumSize(new java.awt.Dimension(80, 90));
        EditarjButton.setMinimumSize(new java.awt.Dimension(80, 90));
        EditarjButton.setPreferredSize(new java.awt.Dimension(80, 90));
        EditarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EditarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarjButtonActionPerformed(evt);
            }
        });
        BarradeTarefasjToolBar.add(EditarjButton);
        BarradeTarefasjToolBar.add(SeparadordeTarefasjSeparator1);

        UsuariojButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/USUARIO.png"))); // NOI18N
        UsuariojButton.setText("Usuário");
        UsuariojButton.setToolTipText("Vincular Produto ao Usuário");
        UsuariojButton.setEnabled(false);
        UsuariojButton.setFocusable(false);
        UsuariojButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        UsuariojButton.setMaximumSize(new java.awt.Dimension(80, 90));
        UsuariojButton.setMinimumSize(new java.awt.Dimension(80, 90));
        UsuariojButton.setName(""); // NOI18N
        UsuariojButton.setPreferredSize(new java.awt.Dimension(80, 90));
        UsuariojButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        UsuariojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariojButtonActionPerformed(evt);
            }
        });
        BarradeTarefasjToolBar.add(UsuariojButton);

        FecharrjButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/fechar.png"))); // NOI18N
        FecharrjButton1.setText("Fechar");
        FecharrjButton1.setToolTipText("Fechar");
        FecharrjButton1.setFocusable(false);
        FecharrjButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        FecharrjButton1.setMaximumSize(new java.awt.Dimension(80, 90));
        FecharrjButton1.setMinimumSize(new java.awt.Dimension(80, 90));
        FecharrjButton1.setPreferredSize(new java.awt.Dimension(80, 90));
        FecharrjButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        FecharrjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharrjButton1ActionPerformed(evt);
            }
        });
        BarradeTarefasjToolBar.add(FecharrjButton1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(descricaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(115, 115, 115)
                    .addComponent(BarradeTarefasjToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(121, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descricaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(316, 316, 316)
                    .addComponent(BarradeTarefasjToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descricaojTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descricaojTextFieldKeyReleased
        carregarModelProduto(descricaojTextField.getText());
    }//GEN-LAST:event_descricaojTextFieldKeyReleased

    private void ProdutosjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProdutosjTableMouseClicked
        if (evt.getClickCount()==1){
            EditarjButton.setEnabled(true);
            UsuariojButton.setEnabled(true);
        }
        if (evt.getClickCount() == 2) {
            if (telaProdutoOrcamento != null) {
            }
            int linha = ProdutosjTable.getSelectedRow();
            if (linha >= 0) {
                if (tipoFiltro.equalsIgnoreCase("relacionar")){
                    telaProdutoOrcamento.setProdutoOrcamento(listaProduto.get(linha));
                }else if (tipoFiltro.equalsIgnoreCase("remover")){
                    this.telaProdutoOrcamento.produtoExcluir(listaProduto.get(linha));
                }
                this.dispose();
            }
        }
    }//GEN-LAST:event_ProdutosjTableMouseClicked

    private void AdicionarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarjButtonActionPerformed
        if (usuarioLogadoBean.getAcesso().getProdutoAdicionar()==1){
          new FrmCadastrarProduto(null, this);
        }else {
            JOptionPane.showMessageDialog(rootPane, "Acesso Negado");
        }
    }//GEN-LAST:event_AdicionarjButtonActionPerformed

    private void EditarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarjButtonActionPerformed
        if (usuarioLogadoBean.getAcesso().getProdutoEditar()==1){
            int linha = ProdutosjTable.getSelectedRow();
            if (linha>=0){
                new FrmCadastrarProduto(listaProduto.get(linha), this);
            }else {
                JOptionPane.showMessageDialog(rootPane, "Selecione um produto orçamento");
            }
        }else {
            JOptionPane.showMessageDialog(rootPane, "Acesso Negado");
        }
    }//GEN-LAST:event_EditarjButtonActionPerformed

    private void UsuariojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariojButtonActionPerformed
        if (usuarioLogadoBean.getAcesso().getProdutoUsuario()==1){
            int linha = ProdutosjTable.getSelectedRow();
            if (linha>=0){
                new FrmConsultaProdutoUsuario(usuarioLogadoBean, listaProduto.get(linha));
            }else {
                JOptionPane.showMessageDialog(rootPane, "Selecione um produto orçamento");
            }
        }else {
            JOptionPane.showMessageDialog(rootPane, "Acesso Negado");
        }
    }//GEN-LAST:event_UsuariojButtonActionPerformed

    private void FecharrjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharrjButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_FecharrjButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarjButton;
    private javax.swing.JToolBar BarradeTarefasjToolBar;
    private javax.swing.JButton EditarjButton;
    private javax.swing.JButton FecharrjButton1;
    private javax.swing.JTable ProdutosjTable;
    private javax.swing.JToolBar.Separator SeparadordeTarefasjSeparator1;
    private javax.swing.JButton UsuariojButton;
    private javax.swing.JTextField descricaojTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void carregarModelProduto(String nome){
        ProdutoController  produtoController = new ProdutoController();
        listaProduto = produtoController.listarProdutos(nome);
        if (listaProduto==null){
            listaProduto = new ArrayList<Produtos>();
        }
        modelProduto = new ConsultaProdutoTableModel(listaProduto);
        ProdutosjTable.setModel(modelProduto);
        ProdutosjTable.getColumnModel().getColumn(0).setPreferredWidth(50);
        ProdutosjTable.getColumnModel().getColumn(1).setPreferredWidth(300);
        ProdutosjTable.repaint();
    }
    
    

    @Override
    public void setModel() {
        carregarModelProduto("");
    }

    @Override
    public void setUsuario(Usuario usuario) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    public void limitarJText(){
        descricaojTextField.setDocument(new LimiteTextoJedit(50));
    }   
}