/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.Fornecedor;

import controller.FornecedorController;
import controller.FornecedorProdutoController;
import controller.ProdutoController;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import model.Fornecedorproduto;
import model.Produtos;
import model.view.Viewfornecedor;
import model.view.Viewfornecedorproduto;
import telas.Produto.ConsultaProdutoTableModel;
import telas.Usuarios.UsuarioLogadoBean;
import util.LimiteTextoJedit;

/**
 *
 * @author Wolverine
 */
public class FrmVincularFornecedor extends javax.swing.JFrame {
    
    private UsuarioLogadoBean  usuarioLogadoBean;
    private List<Viewfornecedor> listaFornecedor;
    private ConsultaFornecedorTableModel modelFornecedor;
    private List<Produtos> listaProduto;
    private ConsultaProdutoTableModel modelProduto;
    private ConsultaProdutoFornecedorTableModel modelFornecedorProduto;
    private List<Viewfornecedorproduto> listaFornecedorProduto;
    private int linhaFornecedor;
    private int linhaProduto;

    /**
     * Creates new form FrmVincularFornecedor
     */
    public FrmVincularFornecedor(UsuarioLogadoBean usuarioLogadoBean) {
        this.usuarioLogadoBean = usuarioLogadoBean;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo/logotela.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        limitarJText();
        carregarModelFornecdor();
        carregarModelProduto("");       
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FornecedorjTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nomejTextField = new javax.swing.JTextField();
        cidadejTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        paisjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ProdutosjTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        fornecedorProdutojTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vincular Fornecedor");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        FornecedorjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Cidade", "País"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FornecedorjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FornecedorjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(FornecedorjTable);
        FornecedorjTable.getColumnModel().getColumn(0).setResizable(false);
        FornecedorjTable.getColumnModel().getColumn(0).setPreferredWidth(20);
        FornecedorjTable.getColumnModel().getColumn(1).setResizable(false);
        FornecedorjTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        FornecedorjTable.getColumnModel().getColumn(2).setResizable(false);

        jLabel1.setText("Pesquisar nome do fornecedor");

        nomejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomejTextFieldKeyReleased(evt);
            }
        });

        cidadejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cidadejTextFieldKeyReleased(evt);
            }
        });

        jLabel2.setText("Pesquisar por Cidade");

        paisjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisjTextFieldActionPerformed(evt);
            }
        });
        paisjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paisjTextFieldKeyReleased(evt);
            }
        });

        jLabel3.setText("Pesquisar por País");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botozinhos/listar.png"))); // NOI18N
        jButton3.setText("Pesquisar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paisjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paisjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ProdutosjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProdutosjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProdutosjTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ProdutosjTable);
        ProdutosjTable.getColumnModel().getColumn(0).setResizable(false);
        ProdutosjTable.getColumnModel().getColumn(0).setPreferredWidth(20);
        ProdutosjTable.getColumnModel().getColumn(1).setResizable(false);
        ProdutosjTable.getColumnModel().getColumn(1).setPreferredWidth(200);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("Vincular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remover");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(34, 34, 34)
                .addComponent(jButton2)
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        fornecedorProdutojTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(fornecedorProdutojTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProdutosjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProdutosjTableMouseClicked
        linhaProduto = ProdutosjTable.getSelectedRow();
        if (linhaProduto>=0){
            carregarModelFornecedorProduto(listaProduto.get(linhaProduto).getIdprodutos());
        }
    }//GEN-LAST:event_ProdutosjTableMouseClicked

    private void FornecedorjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FornecedorjTableMouseClicked
       linhaFornecedor = FornecedorjTable.getSelectedRow();
    }//GEN-LAST:event_FornecedorjTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if ((linhaFornecedor>=0) && (linhaProduto>=0)){
            vincularFornecedorProduto();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int linha = fornecedorProdutojTable.getSelectedRow();
        if (linha>=0){
            excluirFornecedorProduto(linha);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nomejTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomejTextFieldKeyReleased
        carregarModelFornecdor();
    }//GEN-LAST:event_nomejTextFieldKeyReleased

    private void cidadejTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cidadejTextFieldKeyReleased
        carregarModelFornecdor();
    }//GEN-LAST:event_cidadejTextFieldKeyReleased

    private void paisjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paisjTextFieldKeyReleased
        carregarModelFornecdor();
    }//GEN-LAST:event_paisjTextFieldKeyReleased

    private void paisjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paisjTextFieldActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable FornecedorjTable;
    private javax.swing.JTable ProdutosjTable;
    private javax.swing.JTextField cidadejTextField;
    private javax.swing.JTable fornecedorProdutojTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JTextField paisjTextField;
    // End of variables declaration//GEN-END:variables

public void carregarModelFornecdor(){
        FornecedorController fornecedorController =new FornecedorController();
        String sql = "SELECT v From Viewfornecedor v where v.nome like '" + 
                nomejTextField.getText() + "%' and v.cidade like '" + cidadejTextField.getText() + "%' and v.pais like '" +
                paisjTextField.getText() + "%' order by v.nome";
        listaFornecedor =fornecedorController.listaFornecedor(sql);
        if (listaFornecedor==null){
            listaFornecedor = new ArrayList<Viewfornecedor>();
        }
        modelFornecedor = new ConsultaFornecedorTableModel(listaFornecedor);
        FornecedorjTable.setModel(modelFornecedor);
        FornecedorjTable.getColumnModel().getColumn(0).setPreferredWidth(250);
        FornecedorjTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        FornecedorjTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        FornecedorjTable.repaint();
    }

    public void carregarModelProduto(String nome){
        ProdutoController  produtoController = new ProdutoController();
        listaProduto = produtoController.listarProdutos(nome);
        if (listaProduto==null){
            listaProduto = new ArrayList<Produtos>();
        }
        modelProduto = new ConsultaProdutoTableModel(listaProduto);
        ProdutosjTable.setModel(modelProduto);
        ProdutosjTable.getColumnModel().getColumn(0).setPreferredWidth(50);
        ProdutosjTable.getColumnModel().getColumn(1).setPreferredWidth(300);
        ProdutosjTable.repaint();
    }
    
    public void carregarModelFornecedorProduto(int idProduto){
        FornecedorProdutoController fornecedorProdutoController = new FornecedorProdutoController();
        listaFornecedorProduto = fornecedorProdutoController.listaFornecedorProduto(idProduto);
        if (listaFornecedorProduto==null){
            listaFornecedorProduto = new ArrayList<Viewfornecedorproduto>();
        }
        modelFornecedorProduto = new ConsultaProdutoFornecedorTableModel(listaFornecedorProduto);
        fornecedorProdutojTable.setModel(modelFornecedorProduto);
        fornecedorProdutojTable.getColumnModel().getColumn(0).setPreferredWidth(200);
        fornecedorProdutojTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        fornecedorProdutojTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        fornecedorProdutojTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        fornecedorProdutojTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        fornecedorProdutojTable.repaint();
    }
    
    public void vincularFornecedorProduto(){
        FornecedorProdutoController fornecedorProdutoController = new FornecedorProdutoController();
        Fornecedorproduto fornecedorproduto = new Fornecedorproduto();
        fornecedorproduto.setFornecedor(listaFornecedor.get(linhaFornecedor).getIdfornecedor());
        fornecedorproduto.setProdutos(listaProduto.get(linhaProduto).getIdprodutos());
        fornecedorProdutoController.salvar(fornecedorproduto);
        carregarModelFornecedorProduto(listaProduto.get(linhaProduto).getIdprodutos());
    }
    
    public void excluirFornecedorProduto(int linha){
        FornecedorProdutoController fornecedorProdutoController = new FornecedorProdutoController();
        fornecedorProdutoController.Excluir(listaFornecedorProduto.get(linha).getIdFornecedorProduto());
        carregarModelFornecedorProduto(listaProduto.get(linhaProduto).getIdprodutos());
        carregarModelFornecedorProduto(listaProduto.get(linhaProduto).getIdprodutos());
    }
    public void limitarJText(){
        nomejTextField.setDocument(new LimiteTextoJedit(100));
        cidadejTextField.setDocument(new LimiteTextoJedit(50));
    }
}
