/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.FollowUp;

import controller.ControleLojaController;
import controller.FollowupController;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import model.Cliente;
import model.Controleloja;
import model.Followup;
import model.view.Viewconsultacontroleloja;
import telas.Usuarios.UsuarioLogadoBean;

/**
 *
 * @author Wolverine
 */
public class FrmConsultaHistorico extends javax.swing.JFrame implements IHistorico{
    
    private List<Viewconsultacontroleloja> listaHistorico;
    private ConsultaHistoricoTableModel modelHistorico;
    private UsuarioLogadoBean usuarioLogadoBean;
    private Cliente cliente;
    private Followup followup;
    private IFollowup telaFollowup;

    /**
     * Creates new form FrmConsultaEventos
     */
    public FrmConsultaHistorico(UsuarioLogadoBean usuarioLogadoBean, Cliente cliente, Followup followup, IFollowup telaFollowup, String programa) {
        this.telaFollowup = telaFollowup;
        this.usuarioLogadoBean = usuarioLogadoBean;
        this.followup = followup;
        this.cliente = cliente;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo/logotela.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        carregarModelHistorico();
        programajTextField.setText(programa);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historicojTable = new javax.swing.JTable();
        BarradeTarefasjToolBar3 = new javax.swing.JToolBar();
        AdicionarjButton3 = new javax.swing.JButton();
        EditarjButton = new javax.swing.JButton();
        SeparadordeTarefasjSeparator = new javax.swing.JToolBar.Separator();
        FecharrjButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        programajTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta FollowUP");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        historicojTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Data", "Hora", "Histórico", "Unidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        historicojTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historicojTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(historicojTable);
        if (historicojTable.getColumnModel().getColumnCount() > 0) {
            historicojTable.getColumnModel().getColumn(0).setResizable(false);
            historicojTable.getColumnModel().getColumn(0).setPreferredWidth(30);
            historicojTable.getColumnModel().getColumn(1).setResizable(false);
            historicojTable.getColumnModel().getColumn(1).setPreferredWidth(30);
            historicojTable.getColumnModel().getColumn(2).setResizable(false);
            historicojTable.getColumnModel().getColumn(2).setPreferredWidth(200);
            historicojTable.getColumnModel().getColumn(3).setResizable(false);
            historicojTable.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        BarradeTarefasjToolBar3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BarradeTarefasjToolBar3.setFloatable(false);
        BarradeTarefasjToolBar3.setRollover(true);

        AdicionarjButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/adicionar.png"))); // NOI18N
        AdicionarjButton3.setText("Novo");
        AdicionarjButton3.setToolTipText("Adicionar Cliente");
        AdicionarjButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AdicionarjButton3.setMaximumSize(new java.awt.Dimension(80, 90));
        AdicionarjButton3.setMinimumSize(new java.awt.Dimension(80, 90));
        AdicionarjButton3.setName(""); // NOI18N
        AdicionarjButton3.setPreferredSize(new java.awt.Dimension(80, 90));
        AdicionarjButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AdicionarjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarjButton3ActionPerformed(evt);
            }
        });
        BarradeTarefasjToolBar3.add(AdicionarjButton3);

        EditarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/editar.png"))); // NOI18N
        EditarjButton.setText("Editar");
        EditarjButton.setToolTipText("Editar Clietne");
        EditarjButton.setEnabled(false);
        EditarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EditarjButton.setMaximumSize(new java.awt.Dimension(80, 90));
        EditarjButton.setMinimumSize(new java.awt.Dimension(80, 90));
        EditarjButton.setPreferredSize(new java.awt.Dimension(80, 90));
        EditarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EditarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarjButtonActionPerformed(evt);
            }
        });
        BarradeTarefasjToolBar3.add(EditarjButton);
        BarradeTarefasjToolBar3.add(SeparadordeTarefasjSeparator);

        FecharrjButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/fechar.png"))); // NOI18N
        FecharrjButton4.setText("Fechar");
        FecharrjButton4.setToolTipText("Fechar");
        FecharrjButton4.setFocusable(false);
        FecharrjButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        FecharrjButton4.setMaximumSize(new java.awt.Dimension(80, 90));
        FecharrjButton4.setMinimumSize(new java.awt.Dimension(80, 90));
        FecharrjButton4.setPreferredSize(new java.awt.Dimension(80, 90));
        FecharrjButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        FecharrjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharrjButton4ActionPerformed(evt);
            }
        });
        BarradeTarefasjToolBar3.add(FecharrjButton4);

        jLabel1.setText("Programa / Produto");

        programajTextField.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(BarradeTarefasjToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(programajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(programajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BarradeTarefasjToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 751, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void historicojTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historicojTableMouseClicked
        EditarjButton.setEnabled(true);

    }//GEN-LAST:event_historicojTableMouseClicked

    private void AdicionarjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarjButton3ActionPerformed
        new FrmCadastrarHistorico(usuarioLogadoBean, null, cliente, followup, this);
    }//GEN-LAST:event_AdicionarjButton3ActionPerformed

    private void EditarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarjButtonActionPerformed
        int linha = historicojTable.getSelectedRow();
        if (linha>=0){
            ControleLojaController controleLojaController = new ControleLojaController();
            Controleloja controleloja  = controleLojaController.consuiltar(listaHistorico.get(linha).getIdcontroleloja());
            new FrmCadastrarHistorico(usuarioLogadoBean, controleloja, cliente, followup, this);
        }
    }//GEN-LAST:event_EditarjButtonActionPerformed

    private void FecharrjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharrjButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_FecharrjButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarjButton3;
    private javax.swing.JToolBar BarradeTarefasjToolBar3;
    private javax.swing.JButton EditarjButton;
    private javax.swing.JButton FecharrjButton4;
    private javax.swing.JToolBar.Separator SeparadordeTarefasjSeparator;
    private javax.swing.JTable historicojTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField programajTextField;
    // End of variables declaration//GEN-END:variables

    public void carregarModelHistorico(){
        String sql="";
        if (usuarioLogadoBean.getUsuario().getTipo().equalsIgnoreCase("Gerencial")){
            sql = "Select a From Viewconsultacontroleloja a where a.clienteIdcliente=" + cliente.getIdcliente();
        } else {
            sql = "Select a From Viewconsultacontroleloja a where unidadeNegocioidUnidadeNegocio=" + usuarioLogadoBean.getUnidadeNegocio().getIdunidadeNegocio() +
                    " and a.clienteIdcliente="+ cliente.getIdcliente();
        }        
        ControleLojaController  controleLojaController = new ControleLojaController();
        listaHistorico = controleLojaController.listaFollowup(sql);
        if (listaHistorico==null){
            listaHistorico = new ArrayList<Viewconsultacontroleloja>();
        }
        modelHistorico = new ConsultaHistoricoTableModel(listaHistorico);
        historicojTable.setModel(modelHistorico);
        historicojTable.getColumnModel().getColumn(0).setPreferredWidth(30);
        historicojTable.getColumnModel().getColumn(1).setPreferredWidth(30);
        historicojTable.getColumnModel().getColumn(2).setPreferredWidth(200);
        historicojTable.getColumnModel().getColumn(3).setPreferredWidth(100);
        historicojTable.repaint();
    }

    @Override
    public void setModelHistorico(Followup followup) {
        this.followup = followup;
        carregarModelHistorico();
        this.telaFollowup.setModel();
    }

}
