/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.Cliente;

import com.toedter.calendar.JTextFieldDateEditor;
import controller.ClienteController;
import controller.PublicidadeController;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Publicidade;
import telas.Usuarios.UsuarioLogadoBean;
import util.Formatacao;
import util.LimiteTextoJedit;

/**
 *
 * @author Wolverine
 */
public class FrmCadastrarCliente extends javax.swing.JFrame {
    
    private String datePattern;
    private String maskPattern;
    private char placeHolder;
    private ICliente telaCliente;
    private Cliente cliente;
    private UsuarioLogadoBean usuarioLogadoBean;
    private String caracteres = "0987654321-()";
    
    

    /**
     * Creates new form FrmCadastrarCliente
     */
    public FrmCadastrarCliente(Cliente cliente, ICliente telaCliente, UsuarioLogadoBean usuarioLogadoBean) {
        this.cliente = cliente;
        this.telaCliente = telaCliente;
        this.usuarioLogadoBean = usuarioLogadoBean;
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/##";
        placeHolder = '_';
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo/logotela.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        limitarJText();
        setMascaras();
        if (cliente!=null){
            peencherCampos();
        }
        carregarComboBoxPublicidade();
        nomejTextField.requestFocus();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        clientejTabbedPane = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomejTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rgjTextField = new javax.swing.JTextField();
        dataNascimentojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
            maskPattern, placeHolder));
    paisNascimentojTextField = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    cidadeNascimentojTextField = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    sexojComboBox = new javax.swing.JComboBox();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    datavalidadePassaportejDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
dataExpedicaoPassaporteClientejDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
    maskPattern, placeHolder));
    jLabel13 = new javax.swing.JLabel();
    tipoLogradourojComboBox = new javax.swing.JComboBox();
    logradourojTextField = new javax.swing.JTextField();
    jLabel14 = new javax.swing.JLabel();
    numerojTextField = new javax.swing.JTextField();
    jLabel15 = new javax.swing.JLabel();
    jLabel16 = new javax.swing.JLabel();
    complementojTextField = new javax.swing.JTextField();
    jLabel17 = new javax.swing.JLabel();
    bairrojTextField = new javax.swing.JTextField();
    jLabel18 = new javax.swing.JLabel();
    cidadejTextField = new javax.swing.JTextField();
    jLabel19 = new javax.swing.JLabel();
    estadojComboBox = new javax.swing.JComboBox();
    jLabel21 = new javax.swing.JLabel();
    paisEnderecojTextField = new javax.swing.JTextField();
    jLabel20 = new javax.swing.JLabel();
    numeroCPFjFormattedTextField = new javax.swing.JFormattedTextField();
    cepjFormattedTextField = new javax.swing.JFormattedTextField();
    jLabel5 = new javax.swing.JLabel();
    numeroPassaportejTextField = new javax.swing.JTextField();
    estadoCiveljComboBox = new javax.swing.JComboBox();
    jLabel6 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    profissaojTextField = new javax.swing.JTextField();
    jLabel25 = new javax.swing.JLabel();
    jLabel26 = new javax.swing.JLabel();
    emailjTextField = new javax.swing.JTextField();
    jLabel27 = new javax.swing.JLabel();
    skypejTextField = new javax.swing.JTextField();
    jLabel28 = new javax.swing.JLabel();
    facebookjTextField = new javax.swing.JTextField();
    jLabel29 = new javax.swing.JLabel();
    nomeMaejTextField = new javax.swing.JTextField();
    profissaoMaejTextField = new javax.swing.JTextField();
    jLabel30 = new javax.swing.JLabel();
    jLabel32 = new javax.swing.JLabel();
    nomePaijTextField = new javax.swing.JTextField();
    profissaoPaijTextField = new javax.swing.JTextField();
    jLabel33 = new javax.swing.JLabel();
    jLabel35 = new javax.swing.JLabel();
    escolaridadejComboBox = new javax.swing.JComboBox();
    publicidadejComboBox = new javax.swing.JComboBox();
    jLabel36 = new javax.swing.JLabel();
    complementoPublicidadejTextField = new javax.swing.JTextField();
    foneResidencialjCheckBox = new javax.swing.JCheckBox();
    foneResidencialjTextField = new javax.swing.JTextField();
    foneCelularjTextField = new javax.swing.JTextField();
    foneCelularjCheckBox = new javax.swing.JCheckBox();
    foneComercialjCheckBox = new javax.swing.JCheckBox();
    foneComercialjTextField = new javax.swing.JTextField();
    foneMaejCheckBox = new javax.swing.JCheckBox();
    foneMaejTextField = new javax.swing.JTextField();
    fonePaijCheckBox = new javax.swing.JCheckBox();
    fonePaijTextField = new javax.swing.JTextField();
    jPanel4 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jLayeredPane1 = new javax.swing.JLayeredPane();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Cadastro de Clientes");
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabel1.setText("Nome");

    jLabel2.setText("Data Nascimento");

    jLabel3.setText("Nº CPF");

    jLabel4.setText("Nº RG");

    dataNascimentojDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataNascimentojDateChooserFocusGained(evt);
        }
    });

    jLabel7.setText("Nacionalidade");

    jLabel8.setText("Cidade de Nascimento");

    jLabel9.setText("Sexo");

    sexojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Feminino", "Masculino" }));

    jLabel10.setText("Nº Passaporte");

    jLabel11.setText("Data de Validade");

    datavalidadePassaportejDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            datavalidadePassaportejDateChooserFocusGained(evt);
        }
    });

    dataExpedicaoPassaporteClientejDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataExpedicaoPassaporteClientejDateChooserFocusGained(evt);
        }
    });

    jLabel13.setText("Tipo Logradouro");

    tipoLogradourojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Avenida", "BR", "Estrada", "Rodovia", "Rua", "Servidão", "Parque", "Travessa", " " }));

    jLabel14.setText("Logradouro");

    jLabel15.setText("Número");

    jLabel16.setText("Complemento");

    jLabel17.setText("Bairro");

    jLabel18.setText("CEP");

    jLabel19.setText("Cidade");

    estadojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

    jLabel21.setText("Estado");

    jLabel20.setText("País");

    try {
        numeroCPFjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
    } catch (java.text.ParseException ex) {
        ex.printStackTrace();
    }

    jLabel5.setText("Data Expedição");

    estadoCiveljComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro", "Casado", "Divorciado", "Viúvo", " " }));

    jLabel6.setText("Estado Cívil");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel13)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(tipoLogradourojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(logradourojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(numerojTextField)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addGap(0, 69, Short.MAX_VALUE)))
                                    .addGap(18, 18, 18))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(136, 136, 136)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(cidadeNascimentojTextField)
                                                .addComponent(numeroPassaportejTextField))
                                            .addGap(18, 18, 18))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel8))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(complementojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(estadoCiveljComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(rgjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(dataExpedicaoPassaporteClientejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(131, 131, 131)))))))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(0, 489, Short.MAX_VALUE))
                                .addComponent(nomejTextField))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dataNascimentojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))
                        .addComponent(jLabel7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(paisNascimentojTextField)
                            .addComponent(numeroCPFjFormattedTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sexojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel11)
                        .addComponent(datavalidadePassaportejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel17)
                        .addComponent(bairrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addGap(101, 101, 101))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(cepjFormattedTextField)
                            .addGap(18, 18, 18)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel21)
                        .addComponent(estadojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(paisEnderecojTextField)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addGap(0, 0, Short.MAX_VALUE)))))
            .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataNascimentojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(sexojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(paisNascimentojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cidadeNascimentojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(estadoCiveljComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(rgjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numeroCPFjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numeroPassaportejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel5))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(datavalidadePassaportejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataExpedicaoPassaporteClientejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel13)
                .addComponent(jLabel14)
                .addComponent(jLabel15)
                .addComponent(jLabel16))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tipoLogradourojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(logradourojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(numerojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(complementojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel17)
                .addComponent(jLabel18)
                .addComponent(jLabel19)
                .addComponent(jLabel21)
                .addComponent(jLabel20))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(bairrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(estadojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(paisEnderecojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cepjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(30, Short.MAX_VALUE))
    );

    clientejTabbedPane.addTab("Informações Pessoais", jPanel3);

    jLabel25.setText("Profissão");

    jLabel26.setText("E-mail");

    jLabel27.setText("Skype");

    jLabel28.setText("FaceBook");

    jLabel29.setText("Nome da Mãe");

    jLabel30.setText("Profissão");

    jLabel32.setText("Nome do Pai");

    jLabel33.setText("Profissão");

    jLabel35.setText("Escolaridade");

    escolaridadejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ensino Fundamental", "Ensino Médio", "Ensino Superior", " " }));

    jLabel36.setText("Como conheceu a TravelMate");

    foneResidencialjCheckBox.setText("9-Fone Residencial");
    foneResidencialjCheckBox.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            foneResidencialjCheckBoxItemStateChanged(evt);
        }
    });

    foneResidencialjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            foneResidencialjTextFieldFocusLost(evt);
        }
    });
    foneResidencialjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            foneResidencialjTextFieldKeyPressed(evt);
        }
        public void keyTyped(java.awt.event.KeyEvent evt) {
            foneResidencialjTextFieldKeyTyped(evt);
        }
    });

    foneCelularjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            foneCelularjTextFieldFocusLost(evt);
        }
    });
    foneCelularjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            foneCelularjTextFieldKeyPressed(evt);
        }
        public void keyTyped(java.awt.event.KeyEvent evt) {
            foneCelularjTextFieldKeyTyped(evt);
        }
    });

    foneCelularjCheckBox.setText("9-Fone Celular");
    foneCelularjCheckBox.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            foneCelularjCheckBoxItemStateChanged(evt);
        }
    });

    foneComercialjCheckBox.setText("9-Fone Comercial");
    foneComercialjCheckBox.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            foneComercialjCheckBoxItemStateChanged(evt);
        }
    });
    foneComercialjCheckBox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            foneComercialjCheckBoxActionPerformed(evt);
        }
    });

    foneComercialjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            foneComercialjTextFieldFocusLost(evt);
        }
    });
    foneComercialjTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            foneComercialjTextFieldActionPerformed(evt);
        }
    });
    foneComercialjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            foneComercialjTextFieldKeyPressed(evt);
        }
        public void keyTyped(java.awt.event.KeyEvent evt) {
            foneComercialjTextFieldKeyTyped(evt);
        }
    });

    foneMaejCheckBox.setText("9-Fone Mãe");
    foneMaejCheckBox.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            foneMaejCheckBoxItemStateChanged(evt);
        }
    });

    foneMaejTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            foneMaejTextFieldFocusLost(evt);
        }
    });
    foneMaejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            foneMaejTextFieldKeyPressed(evt);
        }
        public void keyTyped(java.awt.event.KeyEvent evt) {
            foneMaejTextFieldKeyTyped(evt);
        }
    });

    fonePaijCheckBox.setText("9-Fone Pai");
    fonePaijCheckBox.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            fonePaijCheckBoxItemStateChanged(evt);
        }
    });

    fonePaijTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            fonePaijTextFieldFocusLost(evt);
        }
    });
    fonePaijTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            fonePaijTextFieldKeyPressed(evt);
        }
        public void keyTyped(java.awt.event.KeyEvent evt) {
            fonePaijTextFieldKeyTyped(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel29)
                            .addGap(272, 272, 272))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(nomePaijTextField)
                                .addComponent(nomeMaejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
                            .addGap(18, 18, 18)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel30)
                        .addComponent(profissaoMaejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(foneMaejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(foneMaejCheckBox)
                        .addComponent(fonePaijCheckBox)))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel32)
                        .addComponent(jLabel35)
                        .addComponent(escolaridadejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(publicidadejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(complementoPublicidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel36)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel33)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(profissaoPaijTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fonePaijTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(foneResidencialjCheckBox)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(foneResidencialjTextField))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(foneCelularjCheckBox)
                                .addComponent(foneCelularjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel26)
                        .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(foneComercialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(foneComercialjCheckBox))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addGap(229, 229, 229))
                                .addComponent(profissaojTextField)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel27)
                                .addComponent(skypejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel28)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(facebookjTextField))))))
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(foneResidencialjCheckBox)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(foneResidencialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(foneCelularjCheckBox)
                        .addComponent(foneComercialjCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(foneCelularjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(foneComercialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(profissaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel26)
                .addComponent(jLabel27)
                .addComponent(jLabel28))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(facebookjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(skypejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel29)
                                .addComponent(jLabel30))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nomeMaejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(profissaoMaejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(foneMaejCheckBox)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(foneMaejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel33)
                        .addComponent(jLabel32))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomePaijTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(profissaoPaijTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(fonePaijCheckBox)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fonePaijTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel35)
                .addComponent(jLabel36))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(escolaridadejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(publicidadejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(complementoPublicidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(24, Short.MAX_VALUE))
    );

    clientejTabbedPane.addTab("Dados Complementares", jPanel2);

    jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botozinhos/confirmar.png"))); // NOI18N
    jButton1.setText("Confirmar");
    jButton1.setToolTipText("Confirmar Cadastro de Cliente");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botozinhos/cancel.png"))); // NOI18N
    jButton2.setText("Cancelar");
    jButton2.setToolTipText("Cancela Cadastro de Cliente");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(jButton1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
            .addComponent(jButton2)
            .addGap(34, 34, 34))
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1)
                .addComponent(jButton2))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
    jLayeredPane1.setLayout(jLayeredPane1Layout);
    jLayeredPane1Layout.setHorizontalGroup(
        jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 100, Short.MAX_VALUE)
    );
    jLayeredPane1Layout.setVerticalGroup(
        jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 100, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(156, 156, 156))
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(clientejTabbedPane)
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(clientejTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 860, 400));

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataNascimentojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataNascimentojDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataNascimentojDateChooserFocusGained

    private void datavalidadePassaportejDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_datavalidadePassaportejDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_datavalidadePassaportejDateChooserFocusGained

    private void dataExpedicaoPassaporteClientejDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataExpedicaoPassaporteClientejDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataExpedicaoPassaporteClientejDateChooserFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String validar = validarCliente();
        if (validar.length()<5){
            preencherModelCliente();
        }else {
            JOptionPane.showMessageDialog(rootPane, validar);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void foneResidencialjCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_foneResidencialjCheckBoxItemStateChanged
        foneResidencialjTextField.setText("");
        foneResidencialjTextField.requestFocus();
    }//GEN-LAST:event_foneResidencialjCheckBoxItemStateChanged

    private void foneResidencialjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_foneResidencialjTextFieldFocusLost
        caracteres = "0987654321-()";
    }//GEN-LAST:event_foneResidencialjTextFieldFocusLost

    private void foneResidencialjTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_foneResidencialjTextFieldKeyPressed
        if ((evt.getKeyCode() != KeyEvent.VK_DELETE) && (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE)) {
            String texto = foneResidencialjTextField.getText();
            if (foneResidencialjTextField.getText().length() == 0) {
                foneResidencialjTextField.setText("(");
            } else if (foneResidencialjTextField.getText().length() == 3) {
                foneResidencialjTextField.setText(foneResidencialjTextField.getText() + ")");
            }
            if (foneResidencialjCheckBox.isSelected()) {
                if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 9) {
                    if (foneResidencialjTextField.getText().length() == 8) {
                        foneResidencialjTextField.setText(foneResidencialjTextField.getText() + '-');
                    }
                } else {
                    if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 8) {
                        if (foneResidencialjTextField.getText().length() == 9) {
                            foneResidencialjTextField.setText(foneResidencialjTextField.getText() + '-');
                        }
                    }
                }
            } else {
                if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 9) {
                    if (foneResidencialjTextField.getText().length() == 9) {
                        foneResidencialjTextField.setText(foneResidencialjTextField.getText() + '-');
                    }
                } else {
                    if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 8) {
                        if (foneResidencialjTextField.getText().length() == 8) {
                            foneResidencialjTextField.setText(foneResidencialjTextField.getText() + '-');
                        }
                    }
                }
            }
            if (foneResidencialjCheckBox.isSelected()) {
                if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 9) {
                    if (foneResidencialjTextField.getText().length() > 12) {
                        caracteres = "";
                    }
                } else {
                    if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 8) {
                        if (foneResidencialjTextField.getText().length() > 13) {
                            caracteres = "";
                        }
                    }
                }

            } else {
                if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 9) {
                    if (foneResidencialjTextField.getText().length() > 13) {
                        caracteres = "";
                    }
                } else {
                    if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 8) {
                        if (foneResidencialjTextField.getText().length() > 12) {
                            caracteres = "";
                        }
                    }
                }
            }
        }else {
            foneResidencialjTextField.setText("");
        }
    }//GEN-LAST:event_foneResidencialjTextFieldKeyPressed

    private void foneResidencialjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_foneResidencialjTextFieldKeyTyped
        if (evt.getKeyChar()=='.'){
            evt.setKeyChar(',');
        }
        if (evt.getKeyChar() != '\b') {
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_foneResidencialjTextFieldKeyTyped

    private void foneCelularjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_foneCelularjTextFieldFocusLost
        caracteres = "0987654321-()";
    }//GEN-LAST:event_foneCelularjTextFieldFocusLost

    private void foneCelularjTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_foneCelularjTextFieldKeyPressed
        if ((evt.getKeyCode() != KeyEvent.VK_DELETE) && (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE)) {
            String texto = foneCelularjTextField.getText();
            if (foneCelularjTextField.getText().length() == 0) {
                foneCelularjTextField.setText("(");
            } else if (foneCelularjTextField.getText().length() == 3) {
                foneCelularjTextField.setText(foneCelularjTextField.getText() + ")");
            }
            if (foneCelularjCheckBox.isSelected()) {
                if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 9) {
                    if (foneCelularjTextField.getText().length() == 8) {
                        foneCelularjTextField.setText(foneCelularjTextField.getText() + '-');
                    }
                } else {
                    if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 8) {
                        if (foneCelularjTextField.getText().length() == 9) {
                            foneCelularjTextField.setText(foneCelularjTextField.getText() + '-');
                        }
                    }
                }
            } else {
                if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 9) {
                    if (foneCelularjTextField.getText().length() == 9) {
                        foneCelularjTextField.setText(foneCelularjTextField.getText() + '-');
                    }
                } else {
                    if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 8) {
                        if (foneCelularjTextField.getText().length() == 8) {
                            foneCelularjTextField.setText(foneCelularjTextField.getText() + '-');
                        }
                    }
                }
            }
            if (foneCelularjCheckBox.isSelected()) {
                if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 9) {
                    if (foneCelularjTextField.getText().length() > 12) {
                        caracteres = "";
                    }
                } else {
                    if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 8) {
                        if (foneCelularjTextField.getText().length() > 13) {
                            caracteres = "";
                        }
                    }
                }

            } else {
                if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 9) {
                    if (foneCelularjTextField.getText().length() > 13) {
                        caracteres = "";
                    }
                } else {
                    if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 8) {
                        if (foneCelularjTextField.getText().length() > 12) {
                            caracteres = "";
                        }
                    }
                }
            }
        }else {
            foneCelularjTextField.setText("");
        }
    }//GEN-LAST:event_foneCelularjTextFieldKeyPressed

    private void foneCelularjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_foneCelularjTextFieldKeyTyped
        if (evt.getKeyChar()=='.'){
            evt.setKeyChar(',');
        }
        if (evt.getKeyChar() != '\b') {
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_foneCelularjTextFieldKeyTyped

    private void foneCelularjCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_foneCelularjCheckBoxItemStateChanged
        foneCelularjTextField.setText("");
        foneCelularjTextField.requestFocus();
    }//GEN-LAST:event_foneCelularjCheckBoxItemStateChanged

    private void foneComercialjCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_foneComercialjCheckBoxItemStateChanged
        foneComercialjTextField.setText("");
        foneComercialjTextField.requestFocus();
    }//GEN-LAST:event_foneComercialjCheckBoxItemStateChanged

    private void foneComercialjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_foneComercialjTextFieldFocusLost
        caracteres = "0987654321-()";
    }//GEN-LAST:event_foneComercialjTextFieldFocusLost

    private void foneComercialjTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_foneComercialjTextFieldKeyPressed
        if ((evt.getKeyCode() != KeyEvent.VK_DELETE) && (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE)) {
            String texto = foneComercialjTextField.getText();
            if (foneComercialjTextField.getText().length() == 0) {
                foneComercialjTextField.setText("(");
            } else if (foneComercialjTextField.getText().length() == 3) {
                foneComercialjTextField.setText(foneComercialjTextField.getText() + ")");
            }
            if (foneComercialjCheckBox.isSelected()) {
                if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 9) {
                    if (foneComercialjTextField.getText().length() == 8) {
                        foneComercialjTextField.setText(foneComercialjTextField.getText() + '-');
                    }
                } else {
                    if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 8) {
                        if (foneComercialjTextField.getText().length() == 9) {
                            foneComercialjTextField.setText(foneComercialjTextField.getText() + '-');
                        }
                    }
                }
            } else {
                if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 9) {
                    if (foneComercialjTextField.getText().length() == 9) {
                        foneComercialjTextField.setText(foneComercialjTextField.getText() + '-');
                    }
                } else {
                    if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 8) {
                        if (foneComercialjTextField.getText().length() == 8) {
                            foneComercialjTextField.setText(foneComercialjTextField.getText() + '-');
                        }
                    }
                }
            }
            if (foneComercialjCheckBox.isSelected()) {
                if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 9) {
                    if (foneComercialjTextField.getText().length() > 12) {
                        caracteres = "";
                    }
                } else {
                    if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 8) {
                        if (foneComercialjTextField.getText().length() > 13) {
                            caracteres = "";
                        }
                    }
                }

            } else {
                if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 9) {
                    if (foneComercialjTextField.getText().length() > 13) {
                        caracteres = "";
                    }
                } else {
                    if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 8) {
                        if (foneComercialjTextField.getText().length() > 12) {
                            caracteres = "";
                        }
                    }
                }
            }
        }else {
            foneComercialjTextField.setText("");
        }
    }//GEN-LAST:event_foneComercialjTextFieldKeyPressed

    private void foneComercialjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_foneComercialjTextFieldKeyTyped
        if (evt.getKeyChar()=='.'){
            evt.setKeyChar(',');
        }
        if (evt.getKeyChar() != '\b') {
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_foneComercialjTextFieldKeyTyped

    private void foneMaejCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_foneMaejCheckBoxItemStateChanged
        foneMaejTextField.setText("");
        foneMaejTextField.requestFocus();
    }//GEN-LAST:event_foneMaejCheckBoxItemStateChanged

    private void foneMaejTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_foneMaejTextFieldFocusLost
        caracteres = "0987654321-()";
    }//GEN-LAST:event_foneMaejTextFieldFocusLost

    private void foneMaejTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_foneMaejTextFieldKeyPressed
        if ((evt.getKeyCode() != KeyEvent.VK_DELETE) && (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE)) {
            String texto = foneMaejTextField.getText();
            if (foneMaejTextField.getText().length() == 0) {
                foneMaejTextField.setText("(");
            } else if (foneMaejTextField.getText().length() == 3) {
                foneMaejTextField.setText(foneMaejTextField.getText() + ")");
            }
            if (foneMaejCheckBox.isSelected()) {
                if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 9) {
                    if (foneMaejTextField.getText().length() == 8) {
                        foneMaejTextField.setText(foneMaejTextField.getText() + '-');
                    }
                } else {
                    if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 8) {
                        if (foneMaejTextField.getText().length() == 9) {
                            foneMaejTextField.setText(foneMaejTextField.getText() + '-');
                        }
                    }
                }
            } else {
                if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 9) {
                    if (foneMaejTextField.getText().length() == 9) {
                        foneMaejTextField.setText(foneMaejTextField.getText() + '-');
                    }
                } else {
                    if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 8) {
                        if (foneMaejTextField.getText().length() == 8) {
                            foneMaejTextField.setText(foneMaejTextField.getText() + '-');
                        }
                    }
                }
            }
            if (foneMaejCheckBox.isSelected()) {
                if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 9) {
                    if (foneMaejTextField.getText().length() > 12) {
                        caracteres = "";
                    }
                } else {
                    if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 8) {
                        if (foneMaejTextField.getText().length() > 13) {
                            caracteres = "";
                        }
                    }
                }

            } else {
                if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 9) {
                    if (foneMaejTextField.getText().length() > 13) {
                        caracteres = "";
                    }
                } else {
                    if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 8) {
                        if (foneMaejTextField.getText().length() > 12) {
                            caracteres = "";
                        }
                    }
                }
            }
        }else {
            foneMaejTextField.setText("");
        }
    }//GEN-LAST:event_foneMaejTextFieldKeyPressed

    private void foneMaejTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_foneMaejTextFieldKeyTyped
        if (evt.getKeyChar()=='.'){
            evt.setKeyChar(',');
        }
        if (evt.getKeyChar() != '\b') {
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_foneMaejTextFieldKeyTyped

    private void fonePaijCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fonePaijCheckBoxItemStateChanged
        fonePaijTextField.setText("");
        fonePaijTextField.requestFocus();
    }//GEN-LAST:event_fonePaijCheckBoxItemStateChanged

    private void fonePaijTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fonePaijTextFieldFocusLost
        caracteres = "0987654321-()";
    }//GEN-LAST:event_fonePaijTextFieldFocusLost

    private void fonePaijTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fonePaijTextFieldKeyPressed
        if ((evt.getKeyCode() != KeyEvent.VK_DELETE) && (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE)) {
            String texto = fonePaijTextField.getText();
            if (fonePaijTextField.getText().length() == 0) {
                fonePaijTextField.setText("(");
            } else if (fonePaijTextField.getText().length() == 3) {
                fonePaijTextField.setText(fonePaijTextField.getText() + ")");
            }
            if (fonePaijCheckBox.isSelected()) {
                if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 9) {
                    if (fonePaijTextField.getText().length() == 8) {
                        fonePaijTextField.setText(fonePaijTextField.getText() + '-');
                    }
                } else {
                    if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 8) {
                        if (fonePaijTextField.getText().length() == 9) {
                            fonePaijTextField.setText(fonePaijTextField.getText() + '-');
                        }
                    }
                }
            } else {
                if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 9) {
                    if (fonePaijTextField.getText().length() == 9) {
                        fonePaijTextField.setText(fonePaijTextField.getText() + '-');
                    }
                } else {
                    if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 8) {
                        if (fonePaijTextField.getText().length() == 8) {
                            fonePaijTextField.setText(fonePaijTextField.getText() + '-');
                        }
                    }
                }
            }
            if (fonePaijCheckBox.isSelected()) {
                if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 9) {
                    if (fonePaijTextField.getText().length() > 12) {
                        caracteres = "";
                    }
                } else {
                    if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 8) {
                        if (fonePaijTextField.getText().length() > 13) {
                            caracteres = "";
                        }
                    }
                }

            } else {
                if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 9) {
                    if (fonePaijTextField.getText().length() > 13) {
                        caracteres = "";
                    }
                } else {
                    if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone() == 8) {
                        if (fonePaijTextField.getText().length() > 12) {
                            caracteres = "";
                        }
                    }
                }
            }
        }else {
            fonePaijTextField.setText("");
        }
    }//GEN-LAST:event_fonePaijTextFieldKeyPressed

    private void fonePaijTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fonePaijTextFieldKeyTyped
        if (evt.getKeyChar()=='.'){
            evt.setKeyChar(',');
        }
        if (evt.getKeyChar() != '\b') {
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_fonePaijTextFieldKeyTyped

    private void foneComercialjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foneComercialjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foneComercialjTextFieldActionPerformed

    private void foneComercialjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foneComercialjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foneComercialjCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairrojTextField;
    private javax.swing.JFormattedTextField cepjFormattedTextField;
    private javax.swing.JTextField cidadeNascimentojTextField;
    private javax.swing.JTextField cidadejTextField;
    private javax.swing.JTabbedPane clientejTabbedPane;
    private javax.swing.JTextField complementoPublicidadejTextField;
    private javax.swing.JTextField complementojTextField;
    private com.toedter.calendar.JDateChooser dataExpedicaoPassaporteClientejDateChooser;
    private com.toedter.calendar.JDateChooser dataNascimentojDateChooser;
    private com.toedter.calendar.JDateChooser datavalidadePassaportejDateChooser;
    private javax.swing.JTextField emailjTextField;
    private javax.swing.JComboBox escolaridadejComboBox;
    private javax.swing.JComboBox estadoCiveljComboBox;
    private javax.swing.JComboBox estadojComboBox;
    private javax.swing.JTextField facebookjTextField;
    private javax.swing.JCheckBox foneCelularjCheckBox;
    private javax.swing.JTextField foneCelularjTextField;
    private javax.swing.JCheckBox foneComercialjCheckBox;
    private javax.swing.JTextField foneComercialjTextField;
    private javax.swing.JCheckBox foneMaejCheckBox;
    private javax.swing.JTextField foneMaejTextField;
    private javax.swing.JCheckBox fonePaijCheckBox;
    private javax.swing.JTextField fonePaijTextField;
    private javax.swing.JCheckBox foneResidencialjCheckBox;
    private javax.swing.JTextField foneResidencialjTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField logradourojTextField;
    private javax.swing.JTextField nomeMaejTextField;
    private javax.swing.JTextField nomePaijTextField;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JFormattedTextField numeroCPFjFormattedTextField;
    private javax.swing.JTextField numeroPassaportejTextField;
    private javax.swing.JTextField numerojTextField;
    private javax.swing.JTextField paisEnderecojTextField;
    private javax.swing.JTextField paisNascimentojTextField;
    private javax.swing.JTextField profissaoMaejTextField;
    private javax.swing.JTextField profissaoPaijTextField;
    private javax.swing.JTextField profissaojTextField;
    private javax.swing.JComboBox publicidadejComboBox;
    private javax.swing.JTextField rgjTextField;
    private javax.swing.JComboBox sexojComboBox;
    private javax.swing.JTextField skypejTextField;
    private javax.swing.JComboBox tipoLogradourojComboBox;
    // End of variables declaration//GEN-END:variables

    public void carregarComboBoxPublicidade(){
        PublicidadeController publicidadeController = new PublicidadeController();
        List<Publicidade> listaPublicidade = publicidadeController.listar();
        if (listaPublicidade==null){
            listaPublicidade = new ArrayList<Publicidade>();
        }
        publicidadejComboBox = Formatacao.preencherComobox(listaPublicidade, publicidadejComboBox, false, "Nenhum");
    }
    
    public void preencherModelCliente(){
        if (cliente==null){
            cliente = new Cliente();
            cliente.setDataCadastro(new Date());
            cliente.setUnidadenegocio(usuarioLogadoBean.getUnidadeNegocio().getIdunidadeNegocio());
        }
        cliente.setNome(nomejTextField.getText());
        cliente.setBairro(bairrojTextField.getText());
        cliente.setCep(cepjFormattedTextField.getText());
        cliente.setCidade(cidadejTextField.getText());
        cliente.setCidadeNascimento(cidadeNascimentojTextField.getText());
        cliente.setComplemento(complementojTextField.getText());
        cliente.setCpf(numeroCPFjFormattedTextField.getText());
        cliente.setCep(cepjFormattedTextField.getText());
        cliente.setDataExpedicaoPassaporte(dataExpedicaoPassaporteClientejDateChooser.getDate());
        cliente.setDataInscricao(new Date());
        cliente.setDataNascimento(dataNascimentojDateChooser.getDate());
        cliente.setEstadoCivil(estadoCiveljComboBox.getSelectedItem().toString());
        cliente.setEmail(emailjTextField.getText());
        cliente.setEscolaridade(escolaridadejComboBox.getSelectedItem().toString());
        cliente.setEstado(estadojComboBox.getSelectedItem().toString());
        cliente.setFacebook(facebookjTextField.getText());
        cliente.setFoneCelular(foneCelularjTextField.getText());
        cliente.setFoneComercial(foneComercialjTextField.getText());
        cliente.setFoneMae(foneMaejTextField.getText());
        cliente.setFonePai(fonePaijTextField.getText());
        cliente.setFoneResidencial(foneResidencialjTextField.getText());
        cliente.setLogradouro(logradourojTextField.getText());
        cliente.setNomeMae(nomeMaejTextField.getText());
        cliente.setNomePai(nomePaijTextField.getText());
        cliente.setNumero(numerojTextField.getText());
        cliente.setNumeroPassaporte(numeroPassaportejTextField.getText());
        cliente.setPais(paisEnderecojTextField.getText());
        cliente.setPaisNascimento(paisNascimentojTextField.getText());
        cliente.setProfissao(profissaojTextField.getText());
        cliente.setProfissaoMae(profissaoMaejTextField.getText());
        cliente.setProfissaoPai(profissaoPaijTextField.getText());
        cliente.setComplementopublicidade(complementoPublicidadejTextField.getText());
        Publicidade publicidade = (Publicidade) publicidadejComboBox.getSelectedItem();
        if (publicidade!=null){
            cliente.setPublicidade(publicidade.getIdpublicidade());
        }else cliente.setPublicidade(1);
        cliente.setRg(rgjTextField.getText());
        cliente.setSexo(sexojComboBox.getSelectedItem().toString());
        cliente.setSkype(skypejTextField.getText());
        cliente.setTipologradouro(tipoLogradourojComboBox.getSelectedItem().toString());
        cliente.setValidadePassaporte(datavalidadePassaportejDateChooser.getDate());
        ClienteController clienteController = new ClienteController();
        cliente = clienteController.salvar(cliente);
        telaCliente.setModel();
        this.dispose();
    }
    
    public void peencherCampos(){
        if (usuarioLogadoBean.getUnidadeNegocio().getDigitosTelefone()==9){
            foneResidencialjCheckBox.setText("8-Fone Residencial");
            foneComercialjCheckBox.setText("8-Fone Comercial");
            foneCelularjCheckBox.setText("8-Fone Celular");
            foneMaejCheckBox.setText("8-Fone Mãe");
            fonePaijCheckBox.setText("8-Fone Pai");
        }else {
            foneResidencialjCheckBox.setText("9-Fone Residencial");
            foneComercialjCheckBox.setText("9-Fone Comercial");
            foneCelularjCheckBox.setText("9-Fone Celular");
            foneMaejCheckBox.setText("9-Fone Mãe");
            fonePaijCheckBox.setText("9-Fone Pai");
        }
        nomejTextField.setText(cliente.getNome());
        dataNascimentojDateChooser.setDate(cliente.getDataNascimento());
        sexojComboBox.setSelectedItem(cliente.getSexo());
        paisNascimentojTextField.setText(cliente.getPaisNascimento());
        cidadeNascimentojTextField.setText(cliente.getCidadeNascimento());
        rgjTextField.setText(cliente.getRg());
        numeroCPFjFormattedTextField.setText(cliente.getCpf());
        estadoCiveljComboBox.setSelectedItem(cliente.getEstadoCivil());
        numeroPassaportejTextField.setText(cliente.getNumeroPassaporte());
        dataExpedicaoPassaporteClientejDateChooser.setDate(cliente.getDataExpedicaoPassaporte());
        datavalidadePassaportejDateChooser.setDate(cliente.getValidadePassaporte());
        tipoLogradourojComboBox.setSelectedItem(cliente.getTipologradouro());
        logradourojTextField.setText(cliente.getLogradouro());
        numerojTextField.setText(cliente.getNumero());
        complementojTextField.setText(cliente.getComplemento());
        bairrojTextField.setText(cliente.getBairro());
        cidadejTextField.setText(cliente.getCidade());
        cepjFormattedTextField.setText(cliente.getCep());
        estadojComboBox.setSelectedItem(cliente.getEstado());
        paisEnderecojTextField.setText(cliente.getPais());
        foneResidencialjTextField.setText(cliente.getFoneResidencial());
        foneCelularjTextField.setText(cliente.getFoneCelular());
        foneComercialjTextField.setText(cliente.getFoneComercial());
        profissaojTextField.setText(cliente.getProfissao());
        emailjTextField.setText(cliente.getEmail());
        skypejTextField.setText(cliente.getSkype());
        facebookjTextField.setText(cliente.getFacebook());
        nomeMaejTextField.setText(cliente.getNomeMae());
        profissaoMaejTextField.setText(cliente.getProfissaoMae());
        foneMaejTextField.setText(cliente.getFoneMae());
        nomePaijTextField.setText(cliente.getNomePai());
        fonePaijTextField.setText(cliente.getFonePai());
        profissaoPaijTextField.setText(cliente.getProfissaoPai());
        escolaridadejComboBox.setSelectedItem(cliente.getEscolaridade());
        PublicidadeController publicidadeController = new PublicidadeController();
        complementoPublicidadejTextField.setText(cliente.getComplementopublicidade());
        Publicidade publicidade = publicidadeController.consultar(cliente.getPublicidade());
        if (publicidade!=null){
            publicidadejComboBox.setSelectedItem(publicidade);
        }
    }
    
    public String validarCliente(){
        String msg = "";
        if (dataNascimentojDateChooser.getDate()==null){
            msg = msg + "Data Nascimento Inválida\r\n";
        }
        if (numeroCPFjFormattedTextField.getText().equalsIgnoreCase("   .   .   -  ")){
            msg = msg + "Nº CPF inválido\r\n";
        }else if (!Formatacao.validaCPF(numeroCPFjFormattedTextField.getText())){
            msg = msg + "Nº CPF inválido\r\n";
        }
        if (nomejTextField.getText().length()==0){
            msg = msg + "Nome do Cliente não preechido\r\n";
        }
        if (rgjTextField.getText().length()==0){
            msg = msg + "RG não preenchido";
        }
        return msg;
    }
    
    public void  setMascaras(){
        try {
            numeroCPFjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));           
            cepjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));           
        } catch (ParseException ex) {
            Logger.getLogger(FrmCadastrarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void limitarJText(){
        nomejTextField.setDocument(new LimiteTextoJedit(100));
        paisNascimentojTextField.setDocument(new LimiteTextoJedit(50));
        cidadeNascimentojTextField.setDocument(new LimiteTextoJedit(50));
        rgjTextField.setDocument(new LimiteTextoJedit(45));
        numeroCPFjFormattedTextField.setDocument(new LimiteTextoJedit(14));
        numeroPassaportejTextField.setDocument(new LimiteTextoJedit(50));
        logradourojTextField.setDocument(new LimiteTextoJedit(100));
        numerojTextField.setDocument(new LimiteTextoJedit(30));
        complementojTextField.setDocument(new LimiteTextoJedit(100));
        bairrojTextField.setDocument(new LimiteTextoJedit(50));
        cepjFormattedTextField.setDocument(new LimiteTextoJedit(9));
        cidadejTextField.setDocument(new LimiteTextoJedit(50));
        paisEnderecojTextField.setDocument(new LimiteTextoJedit(50));
        foneResidencialjTextField.setDocument(new LimiteTextoJedit(14));
        foneCelularjTextField.setDocument(new LimiteTextoJedit(14));
        foneComercialjTextField.setDocument(new LimiteTextoJedit(14));
        profissaojTextField.setDocument(new LimiteTextoJedit(50));
        emailjTextField.setDocument(new LimiteTextoJedit(100));
        skypejTextField.setDocument(new LimiteTextoJedit(100));
        facebookjTextField.setDocument(new LimiteTextoJedit(100));
        nomeMaejTextField.setDocument(new LimiteTextoJedit(100));
        profissaoMaejTextField.setDocument(new LimiteTextoJedit(50));
        foneMaejTextField.setDocument(new LimiteTextoJedit(14));
        nomePaijTextField.setDocument(new LimiteTextoJedit(100));
        profissaoPaijTextField.setDocument(new LimiteTextoJedit(50));
        fonePaijTextField.setDocument(new LimiteTextoJedit(14));
        complementoPublicidadejTextField.setDocument(new LimiteTextoJedit(100));
    }

}
