/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.Visto;


import com.toedter.calendar.JTextFieldDateEditor;
import controller.VistosController;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import model.Controlevistos;
import model.view.Viewcontrolevistos;
import telas.Usuarios.UsuarioLogadoBean;
import util.LimiteTextoJedit;


/**
 *
 * @author Wolverine
 */
public class FrmAtulizarControleVistos extends javax.swing.JFrame {
    
    private String datePattern;
    private String maskPattern;
    private char placeHolder;
    private Controlevistos controle;
    private Viewcontrolevistos vendasVistos;
  //  private List<Viewcontrolecursos> listaVendas;
    

    /**
     * Creates new form FrmAtulizarControleCurso
     */
    public FrmAtulizarControleVistos(Viewcontrolevistos vendasVistos, UsuarioLogadoBean usuarioLogadoBean) {
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/##";
        placeHolder = '_';
        this.vendasVistos= vendasVistos;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo/logotela.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        limitarJText();
        inicializar();
        if (usuarioLogadoBean.getUsuario().getTipo().equalsIgnoreCase("Unidade")){
            jTabbedPane1.setEnabled(false);
        }       
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        numeroControlejTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dataInscricaojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
            maskPattern, placeHolder));
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    unidadeNegociojTextField = new javax.swing.JTextField();
    consultorjTextField = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    nomejTextField = new javax.swing.JTextField();
    emailjTextField = new javax.swing.JTextField();
    foneCelularjTextField = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    datanascimentojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jLabel33 = new javax.swing.JLabel();
paisVistojTextField = new javax.swing.JTextField();
jLabel9 = new javax.swing.JLabel();
dataInicioProgramajDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
    maskPattern, placeHolder));
    jLabel34 = new javax.swing.JLabel();
    categoriajTextField = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    observacaojTextArea = new javax.swing.JTextArea();
    jLabel25 = new javax.swing.JLabel();
    jCheckBox01 = new javax.swing.JCheckBox();
    jCheckBox02 = new javax.swing.JCheckBox();
    jCheckBox03 = new javax.swing.JCheckBox();
    jCheckBox04 = new javax.swing.JCheckBox();
    jCheckBox05 = new javax.swing.JCheckBox();
    jCheckBox06 = new javax.swing.JCheckBox();
    jCheckBox07 = new javax.swing.JCheckBox();
    jCheckBox08 = new javax.swing.JCheckBox();
    jPanel17 = new javax.swing.JPanel();
    jButton5 = new javax.swing.JButton();
    jButton6 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Atualizar Controle Vistos");

    jLabel2.setText("Nº Controle");

    numeroControlejTextField.setEditable(false);

    jLabel1.setText("Data Inscrição");

    dataInscricaojDateChooser.setEnabled(false);

    jLabel3.setText("Nome");

    jLabel4.setText("Unidade Negócio");

    unidadeNegociojTextField.setEditable(false);

    consultorjTextField.setEditable(false);

    jLabel5.setText("Consultor");

    jLabel6.setText("E-mail");

    jLabel7.setText("Fone Celular");

    nomejTextField.setEditable(false);
    nomejTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            nomejTextFieldActionPerformed(evt);
        }
    });

    emailjTextField.setEditable(false);

    foneCelularjTextField.setEditable(false);

    jLabel8.setText("Data Nascimento");

    jLabel33.setText("País do Visto");

    jLabel9.setText("Data Ínicio Programa");

    jLabel34.setText("Categoria");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(numeroControlejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(11, 11, 11)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataInscricaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(unidadeNegociojTextField))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(consultorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(dataInicioProgramajDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel34)
                            .addGap(0, 485, Short.MAX_VALUE))
                        .addComponent(categoriajTextField)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(nomejTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(64, 64, 64))
                        .addComponent(foneCelularjTextField)))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(datanascimentojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel33)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(paisVistojTextField))))
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(jLabel1)
                .addComponent(jLabel4)
                .addComponent(jLabel5))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(numeroControlejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dataInscricaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidadeNegociojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(jLabel3)
                .addComponent(jLabel7))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(foneCelularjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel8)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(datanascimentojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel33)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(paisVistojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel9)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(dataInicioProgramajDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel34)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(categoriajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(34, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Dados da Ficha", jPanel1);

    observacaojTextArea.setColumns(20);
    observacaojTextArea.setRows(5);
    jScrollPane1.setViewportView(observacaojTextArea);

    jLabel25.setText("Observação");

    jCheckBox01.setText("E-mail com orientação");

    jCheckBox02.setText("Confirmação de matrícula");
    jCheckBox02.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jCheckBox02ActionPerformed(evt);
        }
    });

    jCheckBox03.setText("Rascunho dos formulários");

    jCheckBox04.setText("Preenchimento dos documentos");

    jCheckBox05.setText("Conferencia dos documetos");
    jCheckBox05.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jCheckBox05ActionPerformed(evt);
        }
    });

    jCheckBox06.setText("Envio para processamento");

    jCheckBox07.setText("Protocolo");

    jCheckBox08.setText("Visto liberado");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel25)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jCheckBox05)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCheckBox06))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jCheckBox01)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCheckBox02)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBox03)
                                .addComponent(jCheckBox07))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBox08)
                                .addComponent(jCheckBox04))))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jCheckBox01)
                .addComponent(jCheckBox02)
                .addComponent(jCheckBox03)
                .addComponent(jCheckBox04))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jCheckBox05)
                .addComponent(jCheckBox06)
                .addComponent(jCheckBox07)
                .addComponent(jCheckBox08))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel25)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(46, 46, 46))
    );

    jTabbedPane1.addTab("Dados de Controle", jPanel2);

    jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botozinhos/confirmar.png"))); // NOI18N
    jButton5.setText("Confirmar");
    jButton5.setToolTipText("Confirma Controle Vistos");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });

    jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botozinhos/cancel.png"))); // NOI18N
    jButton6.setText("Cancelar");
    jButton6.setToolTipText("Cancela Controle Vistos");
    jButton6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton6ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
    jPanel17.setLayout(jPanel17Layout);
    jPanel17Layout.setHorizontalGroup(
        jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel17Layout.createSequentialGroup()
            .addContainerGap(85, Short.MAX_VALUE)
            .addComponent(jButton5)
            .addGap(37, 37, 37)
            .addComponent(jButton6)
            .addGap(86, 86, 86))
    );
    jPanel17Layout.setVerticalGroup(
        jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel17Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton5)
                .addComponent(jButton6))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTabbedPane1)
            .addContainerGap())
        .addGroup(layout.createSequentialGroup()
            .addGap(141, 141, 141)
            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        salvarControleVistos();
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jCheckBox02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox02ActionPerformed

    private void jCheckBox05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox05ActionPerformed

    private void nomejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomejTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField categoriajTextField;
    private javax.swing.JTextField consultorjTextField;
    private com.toedter.calendar.JDateChooser dataInicioProgramajDateChooser;
    private com.toedter.calendar.JDateChooser dataInscricaojDateChooser;
    private com.toedter.calendar.JDateChooser datanascimentojDateChooser;
    private javax.swing.JTextField emailjTextField;
    private javax.swing.JTextField foneCelularjTextField;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox01;
    private javax.swing.JCheckBox jCheckBox02;
    private javax.swing.JCheckBox jCheckBox03;
    private javax.swing.JCheckBox jCheckBox04;
    private javax.swing.JCheckBox jCheckBox05;
    private javax.swing.JCheckBox jCheckBox06;
    private javax.swing.JCheckBox jCheckBox07;
    private javax.swing.JCheckBox jCheckBox08;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JTextField numeroControlejTextField;
    private javax.swing.JTextArea observacaojTextArea;
    private javax.swing.JTextField paisVistojTextField;
    private javax.swing.JTextField unidadeNegociojTextField;
    // End of variables declaration//GEN-END:variables

    public void salvarControleVistos(){
        if (jCheckBox01.isSelected()){
            controle.setEmailOrientacao("Sim");
        }else controle.setEmailOrientacao("Não");
        if (jCheckBox02.isSelected()){
            controle.setConfirmacaoMatricula("Sim");
        }else controle.setConfirmacaoMatricula("Não");
        if (jCheckBox03.isSelected()){
            controle.setRascunhoFormularios("Sim");
        }else controle.setRascunhoFormularios("Não");
        if (jCheckBox04.isSelected()){
            controle.setPreenchimentoFormularios("Sim");
        }else controle.setPreenchimentoFormularios("Não");
        if (jCheckBox05.isSelected()){
            controle.setConferenciaDocumentos("Sim");
        }else controle.setConferenciaDocumentos("Não");
        if (jCheckBox06.isSelected()){
            controle.setEnvioProcessamento("Sim");
        }else controle.setEnvioProcessamento("Não");
        if (jCheckBox07.isSelected()){
            controle.setProtocolo("Sim");
        }else controle.setProtocolo("Não");
        if (jCheckBox08.isSelected()){
            controle.setVistoLiberado("Sim");
        }else controle.setVistoLiberado("Não");
        controle.setDataNascimento(datanascimentojDateChooser.getDate());
        controle.setPaisVisto(paisVistojTextField.getText());
        controle.setCategoria(categoriajTextField.getText());
        controle.setDataInicioPrograma(dataInicioProgramajDateChooser.getDate());
        controle.setObservacao(observacaojTextArea.getText());
        VistosController vistosController = new VistosController();
        controle = vistosController.salvar(controle);
    }
   
    public void inicializar() {
        VistosController vistosController = new VistosController();
        controle = vistosController.consultarControleVistos(vendasVistos.getIdvendas());
        if (controle != null) {
            numeroControlejTextField.setText(String.valueOf(vendasVistos.getIdvendas()));
            dataInscricaojDateChooser.setDate(vendasVistos.getDataVenda());
            unidadeNegociojTextField.setText(vendasVistos.getNomeFantasia());
            consultorjTextField.setText(vendasVistos.getNomeConsultor());
            nomejTextField.setText(vendasVistos.getNomeCliente());
            emailjTextField.setText(vendasVistos.getEmail());
            if (controle.getDataInicioPrograma()!=null){
                dataInicioProgramajDateChooser.setDate(controle.getDataInicioPrograma());
            }
            paisVistojTextField.setText(controle.getPaisVisto());
            categoriajTextField.setText(controle.getCategoria());
            if (controle.getDataNascimento()!=null){
                datanascimentojDateChooser.setDate(controle.getDataNascimento());
            }
            observacaojTextArea.setText(vendasVistos.getObservacao());
            if (vendasVistos.getEmailOrientacao().equalsIgnoreCase("Sim")){
                jCheckBox01.setSelected(true);
            }else jCheckBox01.setSelected(false);
            if (vendasVistos.getConfirmacaoMatricula().equalsIgnoreCase("Sim")){
                jCheckBox02.setSelected(true);
            }else jCheckBox02.setSelected(false);
            if (vendasVistos.getRascunhoFormularios().equalsIgnoreCase("Sim")){
                jCheckBox03.setSelected(true);
            }else jCheckBox03.setSelected(false);
            if (vendasVistos.getPreenchimentoFormularios().equalsIgnoreCase("Sim")){
                jCheckBox04.setSelected(true);
            }else jCheckBox04.setSelected(false);
            if (vendasVistos.getConferenciaDocumentos().equalsIgnoreCase("Sim")){
                jCheckBox05.setSelected(true);
            }else jCheckBox05.setSelected(false);
            if (vendasVistos.getEnvioProcessamento().equalsIgnoreCase("Sim")){
                jCheckBox06.setSelected(true);
            }else jCheckBox06.setSelected(false);
            if (vendasVistos.getProtocolo().equalsIgnoreCase("Sim")){
                jCheckBox07.setSelected(true);
            }else jCheckBox07.setSelected(false);
            if (vendasVistos.getVistoLiberado().equalsIgnoreCase("Sim")){
                jCheckBox08.setSelected(true);
            }else jCheckBox08.setSelected(false);
        }
    }
    public void limitarJText(){
        nomejTextField.setDocument(new LimiteTextoJedit(100));
        emailjTextField.setDocument(new LimiteTextoJedit(100));
        foneCelularjTextField.setDocument(new LimiteTextoJedit(14));
        paisVistojTextField.setDocument(new LimiteTextoJedit(100));
        categoriajTextField.setDocument(new LimiteTextoJedit(100));        
    }
}
