/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.OrcamentoCurso.Modelos;

import controller.ModeloOrcamentoCursoController;
import telas.OrcamentoCurso.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Cambio;
import model.Cliente;
import model.Modeloorcamentocurso;
import model.Unidadenegocio;
import model.Usuario;
import model.view.Viewmodeloorcamento;
import Singleton.ConexaoSingleton;
import telas.Cursos.FrmConsultarCursos;
import telas.Usuarios.UsuarioLogadoBean;

/**
 *
 * @author Wolverine
 */
public class FrmConsultarModeloOrcamentoCurso extends javax.swing.JFrame implements IConsultaOrcamento{
    
    private List<Viewmodeloorcamento> listaModelo;
    private ConsultaModeloOrcamentoCursoTableModel modelModelo;
    
    private UsuarioLogadoBean usuarioLogadoBean;
    List<Cambio> listaCambio;
    private int linha;
    private IOrcamentoCurso telaOrcamentoCurso;

    /**
     * Creates new form FrmConsultarCursos
     */
    public FrmConsultarModeloOrcamentoCurso(UsuarioLogadoBean usuarioLogadoBean, List<Cambio> listaCambio, IOrcamentoCurso telaOrcamentoCurso) {
        this.listaCambio = listaCambio;
        this.telaOrcamentoCurso = telaOrcamentoCurso;
        this.usuarioLogadoBean = usuarioLogadoBean;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo/logotela.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        carregarModelVendas();
        this.setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orcamentoCursojTable = new javax.swing.JTable();
        BarradeTarefasjToolBar3 = new javax.swing.JToolBar();
        AdicionarjButton3 = new javax.swing.JButton();
        EditarjButton = new javax.swing.JButton();
        excluirjButton = new javax.swing.JButton();
        SeparadordeTarefasjSeparator = new javax.swing.JToolBar.Separator();
        FecharrjButton = new javax.swing.JButton();
        matrizjCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Orçamento de Cursos");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        orcamentoCursojTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Data Inscrição", "Curso", "Unidade", "Agente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orcamentoCursojTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orcamentoCursojTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(orcamentoCursojTable);
        if (orcamentoCursojTable.getColumnModel().getColumnCount() > 0) {
            orcamentoCursojTable.getColumnModel().getColumn(0).setResizable(false);
            orcamentoCursojTable.getColumnModel().getColumn(0).setPreferredWidth(200);
            orcamentoCursojTable.getColumnModel().getColumn(1).setResizable(false);
            orcamentoCursojTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            orcamentoCursojTable.getColumnModel().getColumn(2).setResizable(false);
            orcamentoCursojTable.getColumnModel().getColumn(2).setPreferredWidth(200);
            orcamentoCursojTable.getColumnModel().getColumn(3).setResizable(false);
            orcamentoCursojTable.getColumnModel().getColumn(3).setPreferredWidth(200);
            orcamentoCursojTable.getColumnModel().getColumn(4).setResizable(false);
            orcamentoCursojTable.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        BarradeTarefasjToolBar3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BarradeTarefasjToolBar3.setFloatable(false);
        BarradeTarefasjToolBar3.setRollover(true);

        AdicionarjButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/adicionar.png"))); // NOI18N
        AdicionarjButton3.setText("Novo");
        AdicionarjButton3.setToolTipText("Novo Orçamento Curso");
        AdicionarjButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AdicionarjButton3.setMaximumSize(new java.awt.Dimension(80, 90));
        AdicionarjButton3.setMinimumSize(new java.awt.Dimension(80, 90));
        AdicionarjButton3.setName(""); // NOI18N
        AdicionarjButton3.setPreferredSize(new java.awt.Dimension(80, 90));
        AdicionarjButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AdicionarjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarjButton3ActionPerformed(evt);
            }
        });
        BarradeTarefasjToolBar3.add(AdicionarjButton3);

        EditarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/editar.png"))); // NOI18N
        EditarjButton.setText("Editar");
        EditarjButton.setToolTipText("Editar Orçamento Curso");
        EditarjButton.setEnabled(false);
        EditarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EditarjButton.setMaximumSize(new java.awt.Dimension(80, 90));
        EditarjButton.setMinimumSize(new java.awt.Dimension(80, 90));
        EditarjButton.setPreferredSize(new java.awt.Dimension(80, 90));
        EditarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EditarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarjButtonActionPerformed(evt);
            }
        });
        BarradeTarefasjToolBar3.add(EditarjButton);

        excluirjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/cancelar.png"))); // NOI18N
        excluirjButton.setText("Cancelar");
        excluirjButton.setToolTipText("Cancelar modelo de orçamento");
        excluirjButton.setEnabled(false);
        excluirjButton.setFocusable(false);
        excluirjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        excluirjButton.setMaximumSize(new java.awt.Dimension(80, 90));
        excluirjButton.setMinimumSize(new java.awt.Dimension(80, 90));
        excluirjButton.setPreferredSize(new java.awt.Dimension(80, 90));
        excluirjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        excluirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirjButtonActionPerformed(evt);
            }
        });
        BarradeTarefasjToolBar3.add(excluirjButton);
        BarradeTarefasjToolBar3.add(SeparadordeTarefasjSeparator);

        FecharrjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/fechar.png"))); // NOI18N
        FecharrjButton.setText("Fechar");
        FecharrjButton.setToolTipText("Fechar");
        FecharrjButton.setFocusable(false);
        FecharrjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        FecharrjButton.setMaximumSize(new java.awt.Dimension(80, 90));
        FecharrjButton.setMinimumSize(new java.awt.Dimension(80, 90));
        FecharrjButton.setPreferredSize(new java.awt.Dimension(80, 90));
        FecharrjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        FecharrjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharrjButtonActionPerformed(evt);
            }
        });
        BarradeTarefasjToolBar3.add(FecharrjButton);

        matrizjCheckBox.setText("Modelos da Matriz");
        matrizjCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                matrizjCheckBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(matrizjCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BarradeTarefasjToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(230, 230, 230))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BarradeTarefasjToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizjCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdicionarjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarjButton3ActionPerformed
        if (usuarioLogadoBean.getAcesso().getCursosAdicionar()==1){
            if (listaCambio!=null){
                new FrmFichaModeloOrcamentoCurso(0, usuarioLogadoBean, this, listaCambio.get(0).getData());
            }else {
                JOptionPane.showMessageDialog(rootPane, "Cambio do dia ainda não liberado");
            }
        }else JOptionPane.showMessageDialog(rootPane,"Acesso Negado");
        
    }//GEN-LAST:event_AdicionarjButton3ActionPerformed

    private void EditarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarjButtonActionPerformed
        if (usuarioLogadoBean.getAcesso().getCursosEditar() == 1) {
            int linha = orcamentoCursojTable.getSelectedRow();
            if (linha >= 0) {
                new FrmFichaModeloOrcamentoCurso(listaModelo.get(linha).getIdorcamentoCurso(), usuarioLogadoBean, this, listaCambio.get(0).getData());
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Acesso Negado");
        }
    }//GEN-LAST:event_EditarjButtonActionPerformed

    private void orcamentoCursojTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orcamentoCursojTableMouseClicked
        EditarjButton.setEnabled(true);
        excluirjButton.setEnabled(true);
        if (evt.getClickCount()==2){
            if (this.telaOrcamentoCurso!=null){
                int linha = orcamentoCursojTable.getSelectedRow();
                if (linha>=0){
                    this.telaOrcamentoCurso.setModeloOrcamento(listaModelo.get(linha).getIdorcamentoCurso());
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_orcamentoCursojTableMouseClicked

    private void FecharrjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharrjButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_FecharrjButtonActionPerformed

    private void matrizjCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_matrizjCheckBoxItemStateChanged
        carregarModelVendas();
    }//GEN-LAST:event_matrizjCheckBoxItemStateChanged

    private void excluirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirjButtonActionPerformed
        int linha = orcamentoCursojTable.getSelectedRow();
        if (linha>=0){
            boolean resultado = JOptionPane.showConfirmDialog(null, "Confirma Cancelamento do Orçamento?", "Excluir", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0;
            if (resultado) {
                ModeloOrcamentoCursoController modeloOrcamentoCursoController = new ModeloOrcamentoCursoController();
                Modeloorcamentocurso modeloorcamentocurso = modeloOrcamentoCursoController.consultar(listaModelo.get(linha).getIdorcamentoCurso());
                if (modeloorcamentocurso!=null){
                    int idUnidade = usuarioLogadoBean.getUnidadeNegocio().getIdunidadeNegocio();
                    int idUnidadeOrcamento = modeloorcamentocurso.getUnidadenegocio();
                    if (idUnidade == idUnidadeOrcamento){
                        modeloorcamentocurso.setSituacao("Cancelado");
                        modeloOrcamentoCursoController.salvar(modeloorcamentocurso);
                        carregarModelVendas();
                    }else JOptionPane.showMessageDialog(rootPane, "Este modelo não pertence a sua Unidade");
                }
            }
        }
    }//GEN-LAST:event_excluirjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarjButton3;
    private javax.swing.JToolBar BarradeTarefasjToolBar3;
    private javax.swing.JButton EditarjButton;
    private javax.swing.JButton FecharrjButton;
    private javax.swing.JToolBar.Separator SeparadordeTarefasjSeparator;
    private javax.swing.JButton excluirjButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox matrizjCheckBox;
    private javax.swing.JTable orcamentoCursojTable;
    // End of variables declaration//GEN-END:variables
    public void carregarModelVendas(){
        try {
            ConexaoSingleton.desconectar();
        } catch (SQLException ex) {
            Logger.getLogger(FrmConsultarCursos.class.getName()).log(Level.SEVERE, null, ex);
        }
        String sql = null;
        if (usuarioLogadoBean.getUsuario().getTipo().equalsIgnoreCase("Gerencial")){
            sql = "select v from Viewmodeloorcamento v where v.situacao='Ativo' order by v.nome";
        }else {
            sql = "select v from Viewmodeloorcamento v ";
            if (matrizjCheckBox.isSelected()){
                sql = sql + " where idunidadeNegocio=6 or idunidadeNegocio=1 or  idunidadeNegocio=2 or idunidadeNegocio=" + 
                    usuarioLogadoBean.getUnidadeNegocio().getIdunidadeNegocio() + " and v.situacao='Ativo' order by v.nome";
            }else {
                sql = sql + " where idunidadeNegocio=" + 
                    usuarioLogadoBean.getUnidadeNegocio().getIdunidadeNegocio() + " and v.situacao='Ativo' order by v.nome";
            }
            
        }
        ModeloOrcamentoCursoController modeloOrcamentoCursoController = new ModeloOrcamentoCursoController();
        listaModelo = modeloOrcamentoCursoController.listarModeloOrcamentoCurso(sql);
        if (listaModelo==null){
            listaModelo = new ArrayList<Viewmodeloorcamento>();
        }
        modelModelo = new ConsultaModeloOrcamentoCursoTableModel(listaModelo);
        orcamentoCursojTable.setModel(modelModelo);
        orcamentoCursojTable.getColumnModel().getColumn(0).setPreferredWidth(200);
        orcamentoCursojTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        orcamentoCursojTable.getColumnModel().getColumn(2).setPreferredWidth(200);
        orcamentoCursojTable.repaint();
    }

    @Override
    public void setModel() {
        carregarModelVendas();
    }

    @Override
    public void setImpressao(boolean ficha, boolean contrato, boolean recibo) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setPesquisa(Cliente cliente, Unidadenegocio unidade, Usuario usuario, Date dataInicial, Date dataFinal) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
