/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmCadastrarFornecedor.java
 *
 * Created on 22/03/2011, 11:05:38
 */

package telas.UnidadeNegocio;

import controller.BancoController;
import controller.UnidadeNegocioController;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Banco;
import model.Unidadenegocio;
import util.Formatacao;
import util.LimiteTextoJedit;


/**
 *
 * @author wolverine
 */
public class FrmCadastrarUnidadeNegocio extends javax.swing.JFrame {

    /** Creates new form FrmCadastrarFornecedor */
    private Unidadenegocio unidadeNegocio;
    private IUnidadeNegocio telaUnidadeNegocio;
    private String caracteres = "0987654321-()";
    

    public FrmCadastrarUnidadeNegocio(Unidadenegocio unidadeNegocio, IUnidadeNegocio telaUnidadeNeogcio) {
        this.telaUnidadeNegocio = telaUnidadeNeogcio;
        this.unidadeNegocio = unidadeNegocio;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo/logotela.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        try {
            setMascaras();
        } catch (ParseException ex) {
            Logger.getLogger(FrmCadastrarUnidadeNegocio.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setLocationRelativeTo(null);
        limitarJText();
        if (unidadeNegocio!=null){
            preenherCampoCadastro();
        }        
        setVisible(true);

    }
    
    private void preenherCampoCadastro(){
        razaoSocialjTextField.setText(unidadeNegocio.getRazaoSocial());
        nomeFantasiajTextField.setText(unidadeNegocio.getNomeFantasia());
        cnpjjFormattedTextField.setText(unidadeNegocio.getCnpj());
        tipologradourojComboBox.setSelectedItem(unidadeNegocio.getTipoLogradouro());
        foneComercialjTextField.setText(unidadeNegocio.getFone());
        enderecojTextField.setText(unidadeNegocio.getLogradouro());
        numeroEnderecojTextField.setText(unidadeNegocio.getNumero());
        complementojTextField.setText(unidadeNegocio.getComplemento());
        bairrojTextField.setText(unidadeNegocio.getBairro());
        cepjFormattedTextField.setText(unidadeNegocio.getCep());
        cidadejTextField.setText(unidadeNegocio.getCidade());
        estadojComboBox.setSelectedItem(unidadeNegocio.getEstado());
        emailjTextField.setText(unidadeNegocio.getEmail());
        tipojComboBox.setSelectedItem(unidadeNegocio.getTipo());
        mesPagamentojTextField.setText(String.valueOf(unidadeNegocio.getMespagamento()));
        if (unidadeNegocio.getDigitosTelefone()==9){
            quintoDigitojCheckBox.setSelected(true);
        }else quintoDigitojCheckBox.setSelected(false);
        perComissaojTextField.setText(Formatacao.formatarDoubleString(unidadeNegocio.getPerconsultor()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        razaoSocialjTextField = new javax.swing.JTextField();
        nomeFantasiajTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cnpjjFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        enderecojTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        complementojTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cepjFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        cidadejTextField = new javax.swing.JTextField();
        estadojComboBox = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        emailjTextField = new javax.swing.JTextField();
        tipologradourojComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        numeroEnderecojTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bairrojTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        quintoDigitojCheckBox = new javax.swing.JCheckBox();
        foneComercialjCheckBox = new javax.swing.JCheckBox();
        foneComercialjTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tipojComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        perComissaojTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bancojComboBox = new javax.swing.JComboBox();
        mesPagamentojTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        salvarjButton2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Unidade de Negócio");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Razão Social");

        jLabel2.setText("Nome Fantasia");

        jLabel3.setText("Nº CNPJ");

        try {
            cnpjjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel9.setText("Endereço");

        jLabel10.setText("Complemento");

        jLabel12.setText("CEP");

        try {
            cepjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel13.setText("Cidade");

        estadojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabel14.setText("Estado");

        jLabel15.setText("E-mail");

        tipologradourojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rua", "Alameda", "Avenida", "Beco", "Estrada", "Jardim", "Largo", "Loteamento", "Parque", "Praça", "Praia", "Rodovia", "Servidao", "Travessa", "Trevo", "Via", "Vila" }));

        jLabel4.setText("Tipo");

        jLabel6.setText("Número");

        jLabel16.setText("Bairro");

        quintoDigitojCheckBox.setText("9o. Digito");

        foneComercialjCheckBox.setText("9-Fone Comercial");
        foneComercialjCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                foneComercialjCheckBoxItemStateChanged(evt);
            }
        });

        foneComercialjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                foneComercialjTextFieldFocusLost(evt);
            }
        });
        foneComercialjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                foneComercialjTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                foneComercialjTextFieldKeyTyped(evt);
            }
        });

        jLabel5.setText("Tipo");

        tipojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Premium", "Express" }));

        jLabel7.setText("Comissão Consultor");

        perComissaojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel8.setText("Banco");

        mesPagamentojTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mesPagamentojTextFieldKeyTyped(evt);
            }
        });

        jLabel11.setText("No. mês Pagamento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(razaoSocialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeFantasiajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(foneComercialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(foneComercialjCheckBox)
                            .addComponent(jLabel3)
                            .addComponent(cnpjjFormattedTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tipologradourojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(enderecojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(numeroEnderecojTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(complementojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addComponent(bairrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(18, 18, 18)))
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(estadojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(emailjTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(cepjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(14, 14, 14)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(cidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(18, 18, 18)
                            .addComponent(quintoDigitojCheckBox)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tipojComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(160, 160, 160)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(perComissaojTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(15, 15, 15))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bancojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(mesPagamentojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(razaoSocialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnpjjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(foneComercialjCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeFantasiajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foneComercialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enderecojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipologradourojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numeroEnderecojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(29, 29, 29)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(complementojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bairrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cepjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quintoDigitojCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(perComissaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bancojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesPagamentojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 510, 460));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salvarjButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        salvarjButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botozinhos/confirmar.png"))); // NOI18N
        salvarjButton2.setText("Confirmar");
        salvarjButton2.setToolTipText("Confirma Cadastro");
        salvarjButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        salvarjButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        salvarjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButton2SalvarCadastroAssociado(evt);
            }
        });
        jPanel4.add(salvarjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botozinhos/cancel.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setToolTipText("Cancela Cadastro");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2FecharCadastro(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 340, 48));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarjButton2SalvarCadastroAssociado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButton2SalvarCadastroAssociado
        if (unidadeNegocio==null){
            unidadeNegocio = new Unidadenegocio();
        }
        unidadeNegocio.setRazaoSocial(razaoSocialjTextField.getText());
        unidadeNegocio.setNomeFantasia(nomeFantasiajTextField.getText());
        unidadeNegocio.setCnpj(cnpjjFormattedTextField.getText());
        unidadeNegocio.setFone(foneComercialjTextField.getText());
        unidadeNegocio.setTipoLogradouro(tipologradourojComboBox.getSelectedItem().toString());
        unidadeNegocio.setLogradouro(enderecojTextField.getText());
        unidadeNegocio.setNumero(numeroEnderecojTextField.getText());
        unidadeNegocio.setComplemento(complementojTextField.getText());
        unidadeNegocio.setBairro(bairrojTextField.getText());
        unidadeNegocio.setCep(cepjFormattedTextField.getText());
        unidadeNegocio.setCidade(cidadejTextField.getText());
        unidadeNegocio.setEstado((String)estadojComboBox.getSelectedItem());
        unidadeNegocio.setEmail(emailjTextField.getText());
        unidadeNegocio.setTipo(tipojComboBox.getSelectedItem().toString());
        if (perComissaojTextField.getText().length()>0){
            unidadeNegocio.setPerconsultor(Formatacao.formatarStringDouble(perComissaojTextField.getText()));
        }else unidadeNegocio.setPerconsultor(0.0);
        if (quintoDigitojCheckBox.isSelected()){
            unidadeNegocio.setDigitosTelefone(9);
        }else {
            unidadeNegocio.setDigitosTelefone(8);
        }
        if (mesPagamentojTextField.getText().length()>0){
            unidadeNegocio.setMespagamento(Integer.parseInt(mesPagamentojTextField.getText()));
        }
        unidadeNegocio.setBanco((Banco) bancojComboBox.getSelectedItem());
        UnidadeNegocioController unidadeNegocioController = new UnidadeNegocioController();
        unidadeNegocioController.salvar(unidadeNegocio);
        telaUnidadeNegocio.setModel();
        this.dispose();
}//GEN-LAST:event_salvarjButton2SalvarCadastroAssociado

    private void jButton2FecharCadastro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2FecharCadastro
        this.dispose();
}//GEN-LAST:event_jButton2FecharCadastro

    private void foneComercialjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_foneComercialjTextFieldKeyTyped
        if (evt.getKeyChar()=='.'){
            evt.setKeyChar(',');
        }
        if (evt.getKeyChar() != '\b') {
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_foneComercialjTextFieldKeyTyped

    private void foneComercialjTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_foneComercialjTextFieldKeyPressed
        if ((evt.getKeyCode() != KeyEvent.VK_DELETE) && (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE)) {
            String texto = foneComercialjTextField.getText();
            if (foneComercialjTextField.getText().length() == 0) {
                foneComercialjTextField.setText("(");
            } else if (foneComercialjTextField.getText().length() == 3) {
                foneComercialjTextField.setText(foneComercialjTextField.getText() + ")");
            }
            if (foneComercialjCheckBox.isSelected()) {
                if (foneComercialjTextField.getText().length() == 9) {
                    foneComercialjTextField.setText(foneComercialjTextField.getText() + '-');
                }

            } else {
                if (foneComercialjTextField.getText().length() == 8) {
                    foneComercialjTextField.setText(foneComercialjTextField.getText() + '-');
                }
            }
            if (foneComercialjCheckBox.isSelected()) {
                if (foneComercialjTextField.getText().length() > 13) {
                    caracteres = "";

                }
            } else {
                if (foneComercialjTextField.getText().length() > 12) {
                    caracteres = "";
                }
            }
        } else {
            foneComercialjTextField.setText("");
        }
    }//GEN-LAST:event_foneComercialjTextFieldKeyPressed

    private void foneComercialjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_foneComercialjTextFieldFocusLost
        caracteres = "0987654321-()";
    }//GEN-LAST:event_foneComercialjTextFieldFocusLost

    private void foneComercialjCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_foneComercialjCheckBoxItemStateChanged
        foneComercialjTextField.setText("");
        foneComercialjTextField.requestFocus();
    }//GEN-LAST:event_foneComercialjCheckBoxItemStateChanged

    private void mesPagamentojTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesPagamentojTextFieldKeyTyped
        String caracteres = "0987654321";
        if (evt.getKeyChar() != '\b') {
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_mesPagamentojTextFieldKeyTyped

    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairrojTextField;
    private javax.swing.JComboBox bancojComboBox;
    private javax.swing.JFormattedTextField cepjFormattedTextField;
    private javax.swing.JTextField cidadejTextField;
    private javax.swing.JFormattedTextField cnpjjFormattedTextField;
    private javax.swing.JTextField complementojTextField;
    private javax.swing.JTextField emailjTextField;
    private javax.swing.JTextField enderecojTextField;
    private javax.swing.JComboBox estadojComboBox;
    private javax.swing.JCheckBox foneComercialjCheckBox;
    private javax.swing.JTextField foneComercialjTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField mesPagamentojTextField;
    private javax.swing.JTextField nomeFantasiajTextField;
    private javax.swing.JTextField numeroEnderecojTextField;
    private javax.swing.JTextField perComissaojTextField;
    private javax.swing.JCheckBox quintoDigitojCheckBox;
    private javax.swing.JTextField razaoSocialjTextField;
    private javax.swing.JButton salvarjButton2;
    private javax.swing.JComboBox tipojComboBox;
    private javax.swing.JComboBox tipologradourojComboBox;
    // End of variables declaration//GEN-END:variables

    

    public final void setMascaras() throws ParseException {
        foneComercialjCheckBox.setText("9-Fone Comercial");
        cnpjjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        cepjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        BancoController bancoController = new BancoController();
        List<Banco> listaBanco = bancoController.listar();
        bancojComboBox = Formatacao.preencherComobox(listaBanco, bancojComboBox, false, "");
    }
    public void limitarJText(){
       razaoSocialjTextField.setDocument(new LimiteTextoJedit(100));
       cnpjjFormattedTextField.setDocument(new LimiteTextoJedit(18)); 
       nomeFantasiajTextField.setDocument(new LimiteTextoJedit(100));
       foneComercialjTextField.setDocument(new LimiteTextoJedit(14)); 
       enderecojTextField.setDocument(new LimiteTextoJedit(100));
       numeroEnderecojTextField.setDocument(new LimiteTextoJedit(10));        
       complementojTextField.setDocument(new LimiteTextoJedit(50));        
       bairrojTextField.setDocument(new LimiteTextoJedit(50));        
       cepjFormattedTextField.setDocument(new LimiteTextoJedit(9));        
       emailjTextField.setDocument(new LimiteTextoJedit(100));
    }
}
