/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.Cancelamento;

import com.toedter.calendar.JTextFieldDateEditor;
import controller.CancelamentoController;
import controller.ContasReceberController;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import model.Cancelamento;
import model.Contasreceber;
import telas.Usuarios.UsuarioLogadoBean;
import util.Formatacao;

/**
 *
 * @author Wolverine
 */
public class FrmCancelamento extends javax.swing.JFrame {
    
    private String datePattern;
    private String maskPattern;
    private char placeHolder;
    private UsuarioLogadoBean usuarioLogadoBean;
    private Cancelamento cancelamento;
    private int idVenda;
    private int idCliente;
    private String curso;
    

    /**
     * Creates new form FrmCancelamento
     */
    public FrmCancelamento(UsuarioLogadoBean usuarioLogadoBean, int idVenda, int idCliente, String curso) {
        this.idVenda = idVenda;
        this.idCliente = idCliente;
        this.curso = curso;
        this.usuarioLogadoBean = usuarioLogadoBean;
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/##";
        placeHolder = '_';
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo/logotela.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        CancelamentoController cancelamentoController = new CancelamentoController();
        cancelamento = cancelamentoController.cunsultar(idVenda);
        if (cancelamento==null){
            cancelamento = new Cancelamento();
            dataSolicitacaojDateChooser.setDate(new Date());
            valorMatrizjTextField.setText(Formatacao.formatarFloatString(calcaularValorRecebidoMatriz()));
            valorPagarjTextField.setText(valorMatrizjTextField.getText());
        }else {
            valorLojajTextField.setEditable(false);
            valormultajTextField.setEditable(false);
            valorPagarjTextField.setEditable(false);
            creditojRadioButton.setEnabled(false);
            reembolsojRadioButton.setEnabled(false);
            dataAcertojDateChooser.setEnabled(false);
            observacaojTextArea.setEnabled(false);
            confirmajButton.setEnabled(false);
        }
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rembolsocreditobuttonGroup = new javax.swing.ButtonGroup();
        realizadobuttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dataSolicitacaojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
            maskPattern, placeHolder));
    jLabel3 = new javax.swing.JLabel();
    valorMatrizjTextField = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    valorLojajTextField = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    valormultajTextField = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    valorPagarjTextField = new javax.swing.JTextField();
    jPanel3 = new javax.swing.JPanel();
    reembolsojRadioButton = new javax.swing.JRadioButton();
    creditojRadioButton = new javax.swing.JRadioButton();
    jLabel7 = new javax.swing.JLabel();
    dataAcertojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jPanel4 = new javax.swing.JPanel();
jScrollPane1 = new javax.swing.JScrollPane();
observacaojTextArea = new javax.swing.JTextArea();
jPanel6 = new javax.swing.JPanel();
realizadoLojajRadioButton = new javax.swing.JRadioButton();
realizadoMatrizjRadioButton = new javax.swing.JRadioButton();
jPanel5 = new javax.swing.JPanel();
confirmajButton = new javax.swing.JButton();
cancelarjButton = new javax.swing.JButton();
termojButton1 = new javax.swing.JButton();

setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
jLabel1.setText("Reembolso e Crédito");

javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
jPanel1.setLayout(jPanel1Layout);
jPanel1Layout.setHorizontalGroup(
    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabel2.setText("Data Solicitação Cliente ");

    dataSolicitacaojDateChooser.setEnabled(false);
    dataSolicitacaojDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataSolicitacaojDateChooserFocusGained(evt);
        }
    });

    jLabel3.setText("Valor Recebido na Matriz");

    valorMatrizjTextField.setEditable(false);
    valorMatrizjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

    jLabel4.setText("Valor Recebido na Loja");

    valorLojajTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorLojajTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            valorLojajTextFieldKeyPressed(evt);
        }
        public void keyReleased(java.awt.event.KeyEvent evt) {
            valorLojajTextFieldKeyReleased(evt);
        }
        public void keyTyped(java.awt.event.KeyEvent evt) {
            valorLojajTextFieldKeyTyped(evt);
        }
    });

    jLabel5.setText("Multa");

    valormultajTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valormultajTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            valormultajTextFieldKeyPressed(evt);
        }
        public void keyReleased(java.awt.event.KeyEvent evt) {
            valormultajTextFieldKeyReleased(evt);
        }
        public void keyTyped(java.awt.event.KeyEvent evt) {
            valormultajTextFieldKeyTyped(evt);
        }
    });

    jLabel6.setText("Valor Reembolso / Crédito");

    valorPagarjTextField.setEditable(false);
    valorPagarjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

    jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    rembolsocreditobuttonGroup.add(reembolsojRadioButton);
    reembolsojRadioButton.setText("Reembolso");

    rembolsocreditobuttonGroup.add(creditojRadioButton);
    creditojRadioButton.setSelected(true);
    creditojRadioButton.setText("Crédito");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addComponent(reembolsojRadioButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(creditojRadioButton)
            .addGap(66, 66, 66))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(reembolsojRadioButton)
                .addComponent(creditojRadioButton))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jLabel7.setText("Data acerto com cliente");

    dataAcertojDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataAcertojDateChooserFocusGained(evt);
        }
    });

    jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Observação"));

    observacaojTextArea.setColumns(20);
    observacaojTextArea.setRows(5);
    jScrollPane1.setViewportView(observacaojTextArea);

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1)
            .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 13, Short.MAX_VALUE))
    );

    jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    realizadobuttonGroup.add(realizadoLojajRadioButton);
    realizadoLojajRadioButton.setSelected(true);
    realizadoLojajRadioButton.setText("Realizado na Loja ");

    realizadobuttonGroup.add(realizadoMatrizjRadioButton);
    realizadoMatrizjRadioButton.setText("Realizado na Matriz");

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addComponent(realizadoLojajRadioButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(realizadoMatrizjRadioButton)
            .addGap(25, 25, 25))
    );
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(realizadoLojajRadioButton)
                .addComponent(realizadoMatrizjRadioButton))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(90, 90, 90)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(valorPagarjTextField)
                                .addComponent(valormultajTextField)
                                .addComponent(valorLojajTextField)
                                .addComponent(valorMatrizjTextField)
                                .addComponent(dataSolicitacaojDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dataAcertojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 9, Short.MAX_VALUE))
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(dataSolicitacaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2))
            .addGap(32, 32, 32)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(valorMatrizjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel4)
                .addComponent(valorLojajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(valormultajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(valorPagarjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel6))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(dataAcertojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel7))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    confirmajButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botozinhos/confirmar.png"))); // NOI18N
    confirmajButton.setText("Confirmar");
    confirmajButton.setToolTipText("Confirmar Cancelamento");
    confirmajButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            confirmajButtonActionPerformed(evt);
        }
    });

    cancelarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botozinhos/cancel.png"))); // NOI18N
    cancelarjButton.setText("Cancelar");
    cancelarjButton.setToolTipText("Cancela Cancelamento");
    cancelarjButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cancelarjButtonActionPerformed(evt);
        }
    });

    termojButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botozinhos/imprimir.png"))); // NOI18N
    termojButton1.setText("Termo");
    termojButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            termojButton1ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(confirmajButton)
            .addGap(18, 18, 18)
            .addComponent(termojButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(cancelarjButton)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(confirmajButton)
                .addComponent(cancelarjButton)
                .addComponent(termojButton1))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataSolicitacaojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataSolicitacaojDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataSolicitacaojDateChooserFocusGained

    private void dataAcertojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataAcertojDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataAcertojDateChooserFocusGained

    private void confirmajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmajButtonActionPerformed
        cancelamento.setDataacerto(dataAcertojDateChooser.getDate());
        cancelamento.setDatasolicitacao(dataSolicitacaojDateChooser.getDate());
        if (realizadoLojajRadioButton.isSelected()){
            cancelamento.setLocalacerto("Realizado na Loja");
        }else {
            cancelamento.setLocalacerto("Realizado na Matriz");
        }
        if (reembolsojRadioButton.isSelected()){
            cancelamento.setTipopagamento("Reembolso");
        }else {
            cancelamento.setTipopagamento("Crédito");
        }
        if (valorMatrizjTextField.getText().length()>0){
            cancelamento.setValormatriz(Formatacao.formatarStringfloat(valorMatrizjTextField.getText()));
        }else {
            cancelamento.setValormatriz(0.0f);
        }
        if (valorLojajTextField.getText().length()>0){
            cancelamento.setValorloja(Formatacao.formatarStringfloat(valorLojajTextField.getText()));
        }else {
            cancelamento.setValorloja(0.0f);
        }
        if (valormultajTextField.getText().length()>0){
            cancelamento.setMulta(Formatacao.formatarStringfloat(valormultajTextField.getText()));
        }else {
            cancelamento.setMulta(0.0f);
        }
        if (valorPagarjTextField.getText().length()>0){
            cancelamento.setValorreembolso(Formatacao.formatarStringfloat(valorPagarjTextField.getText()));
        }else {
            cancelamento.setValorreembolso(0.0f);
        }
        cancelamento.setUsuario(usuarioLogadoBean.getUsuario().getIdusuario());
        cancelamento.setVendas(idVenda);
        cancelamento.setObservacao(observacaojTextArea.getText());
        CancelamentoController cancelamentoController = new CancelamentoController();
        cancelamento = cancelamentoController.salvar(cancelamento);
        JOptionPane.showMessageDialog(rootPane, "Cancelamento efetuado com Sucesso");
        this.dispose();
    }//GEN-LAST:event_confirmajButtonActionPerformed

    private void cancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarjButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarjButtonActionPerformed

    private void valorLojajTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorLojajTextFieldKeyTyped
        String caracteres = "0987654321,.";
        if (evt.getKeyChar() != '\b') {
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_valorLojajTextFieldKeyTyped

    private void valormultajTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valormultajTextFieldKeyTyped
        // TODO add your handling code here:evt) {                                              
        String caracteres = "0987654321.,";
        if (evt.getKeyChar() != '\b') {
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_valormultajTextFieldKeyTyped

    private void valorLojajTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorLojajTextFieldKeyPressed
        
    }//GEN-LAST:event_valorLojajTextFieldKeyPressed

    private void valormultajTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valormultajTextFieldKeyPressed
        
    }//GEN-LAST:event_valormultajTextFieldKeyPressed

    private void valorLojajTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorLojajTextFieldKeyReleased
        float valorMulta = 0.0f;
        if (valormultajTextField.getText().length()>0){
            valorMulta = Formatacao.formatarStringfloat(valormultajTextField.getText());
        }
        float valorLoja = 0.0f;
        if (valorLojajTextField.getText().length()>0){
            valorLoja = Formatacao.formatarStringfloat(valorLojajTextField.getText());
        }
        float valorMatriz = Formatacao.formatarStringfloat(valorMatrizjTextField.getText());
        float total = (valorMatriz + valorLoja) - valorMulta;
        valorPagarjTextField.setText(Formatacao.formatarFloatString(total));
        if (total<=0){
            JOptionPane.showMessageDialog(rootPane, "Erro Total menor ou igual a 0");
        }
    }//GEN-LAST:event_valorLojajTextFieldKeyReleased

    private void valormultajTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valormultajTextFieldKeyReleased
        float valorMulta = 0.0f;
        if (valormultajTextField.getText().length()>0){
            valorMulta = Formatacao.formatarStringfloat(valormultajTextField.getText());
        }
        float valorLoja = 0.0f;
        if (valorLojajTextField.getText().length()>0){
            valorLoja = Formatacao.formatarStringfloat(valorLojajTextField.getText());
        }
        float valorMatriz = Formatacao.formatarStringfloat(valorMatrizjTextField.getText());
        float total = (valorMatriz + valorLoja) - valorMulta;
        valorPagarjTextField.setText(Formatacao.formatarFloatString(total));
        if (total<=0){
            JOptionPane.showMessageDialog(rootPane, "Erro Total menor ou igual a 0");
        }
    }//GEN-LAST:event_valormultajTextFieldKeyReleased

    private void termojButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termojButton1ActionPerformed
         if (reembolsojRadioButton.isSelected()) {
            new FrmImpressaoTermoQuitacao(idCliente, curso);
        }else JOptionPane.showMessageDialog(null, "Cancelamento não é reembolso");
    }//GEN-LAST:event_termojButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JButton confirmajButton;
    private javax.swing.JRadioButton creditojRadioButton;
    private com.toedter.calendar.JDateChooser dataAcertojDateChooser;
    private com.toedter.calendar.JDateChooser dataSolicitacaojDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea observacaojTextArea;
    private javax.swing.JRadioButton realizadoLojajRadioButton;
    private javax.swing.JRadioButton realizadoMatrizjRadioButton;
    private javax.swing.ButtonGroup realizadobuttonGroup;
    private javax.swing.JRadioButton reembolsojRadioButton;
    private javax.swing.ButtonGroup rembolsocreditobuttonGroup;
    private javax.swing.JButton termojButton1;
    private javax.swing.JTextField valorLojajTextField;
    private javax.swing.JTextField valorMatrizjTextField;
    private javax.swing.JTextField valorPagarjTextField;
    private javax.swing.JTextField valormultajTextField;
    // End of variables declaration//GEN-END:variables

    public Float calcaularValorRecebidoMatriz(){
        ContasReceberController contasReceberController = new ContasReceberController();
        List<Contasreceber> lista = contasReceberController.listar(idVenda);
        float soma = 0.0f;
        if (lista!=null){
            for(int i=0;i<lista.size();i++){
                if (lista.get(i).getValorpago()>0){
                    soma+=lista.get(i).getValorparcela();
                }
            }
        }
        return soma;
    }


}
