/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.Aupair.Controle;


import com.toedter.calendar.JTextFieldDateEditor;
import controller.AupairController;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import model.Controleaupair;
import model.view.Viewcontroleaupair;
import telas.Usuarios.UsuarioLogadoBean;
import util.LimiteTextoJedit;

/**
 *
 * @author Wolverine
 */
public class FrmAtulizarControleAupair extends javax.swing.JFrame {
    
    private String datePattern;
    private String maskPattern;
    private char placeHolder;
    private Controleaupair controle;
    private Viewcontroleaupair vendasAupair;
    private UsuarioLogadoBean usuarioLogadoBean;
  //  private List<Viewcontrolecursos> listaVendas;
    

    /**
     * Creates new form FrmAtulizarControleCurso
     */
    public FrmAtulizarControleAupair(Viewcontroleaupair vendasAupair, UsuarioLogadoBean usuarioLogadoBean) {
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/##";
        placeHolder = '_';
        this.usuarioLogadoBean = usuarioLogadoBean;
        this.vendasAupair = vendasAupair;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo/logotela.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        limitarJText();
        inicializar();
        if (usuarioLogadoBean.getUsuario().getTipo().equalsIgnoreCase("Unidade")){
            jTabbedPane1.setEnabled(false);
        }
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        numeroControlejTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dataInscricaojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
            maskPattern, placeHolder));
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    unidadeNegociojTextField = new javax.swing.JTextField();
    consultorjTextField = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    cursojTextField = new javax.swing.JTextField();
    jLabel12 = new javax.swing.JLabel();
    nomejTextField = new javax.swing.JTextField();
    emailjTextField = new javax.swing.JTextField();
    foneCelularjTextField = new javax.swing.JTextField();
    cidadeEstudajTextField = new javax.swing.JTextField();
    jLabel14 = new javax.swing.JLabel();
    jLabel15 = new javax.swing.JLabel();
    linguajTextField = new javax.swing.JTextField();
    jLabel16 = new javax.swing.JLabel();
    niveljTextField = new javax.swing.JTextField();
    universidadejTextField = new javax.swing.JTextField();
    jLabel26 = new javax.swing.JLabel();
    dataNascimentojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jLabel27 = new javax.swing.JLabel();
sexojTextField = new javax.swing.JTextField();
rgjTextField = new javax.swing.JTextField();
jLabel28 = new javax.swing.JLabel();
dataIniciojDateChooser01 = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
    maskPattern, placeHolder));
    jLabel9 = new javax.swing.JLabel();
    dataIniciojDateChooser02 = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jLabel13 = new javax.swing.JLabel();
dataTerminojDateChooser01 = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
    maskPattern, placeHolder));
    dataTerminojDateChooser02 = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jPanel2 = new javax.swing.JPanel();
jLabel17 = new javax.swing.JLabel();
skypejTextField = new javax.swing.JTextField();
dataEmbarquejDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
    maskPattern, placeHolder));
    jLabel18 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    observacaojTextArea = new javax.swing.JTextArea();
    jLabel25 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    passaportejTextField = new javax.swing.JTextField();
    jLabel31 = new javax.swing.JLabel();
    sponsorjTextField = new javax.swing.JTextField();
    jLabel32 = new javax.swing.JLabel();
    cidadeEmpregadorjTextField = new javax.swing.JTextField();
    jLabel33 = new javax.swing.JLabel();
    empregadorjTextField = new javax.swing.JTextField();
    dataRetornojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jLabel34 = new javax.swing.JLabel();
jLabel35 = new javax.swing.JLabel();
statusProcessojComboBox = new javax.swing.JComboBox();
jLabel36 = new javax.swing.JLabel();
statusProgramajTextField = new javax.swing.JTextField();
jPanel3 = new javax.swing.JPanel();
jCheckBox01 = new javax.swing.JCheckBox();
jCheckBox02 = new javax.swing.JCheckBox();
jCheckBox03 = new javax.swing.JCheckBox();
jCheckBox04 = new javax.swing.JCheckBox();
jCheckBox05 = new javax.swing.JCheckBox();
jCheckBox06 = new javax.swing.JCheckBox();
jCheckBox09 = new javax.swing.JCheckBox();
jCheckBox08 = new javax.swing.JCheckBox();
jCheckBox07 = new javax.swing.JCheckBox();
jCheckBox10 = new javax.swing.JCheckBox();
jCheckBox11 = new javax.swing.JCheckBox();
jCheckBox12 = new javax.swing.JCheckBox();
jCheckBox13 = new javax.swing.JCheckBox();
jCheckBox14 = new javax.swing.JCheckBox();
jCheckBox15 = new javax.swing.JCheckBox();
jCheckBox16 = new javax.swing.JCheckBox();
jCheckBox17 = new javax.swing.JCheckBox();
jCheckBox18 = new javax.swing.JCheckBox();
jPanel17 = new javax.swing.JPanel();
jButton5 = new javax.swing.JButton();
jButton6 = new javax.swing.JButton();

setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
setTitle("Atualizar Controle de Aupair");

jLabel2.setText("Nº Controle");

numeroControlejTextField.setEditable(false);

jLabel1.setText("Data Inscrição");

dataInscricaojDateChooser.setEnabled(false);

jLabel3.setText("Nome");

jLabel4.setText("Unidade Negócio");

unidadeNegociojTextField.setEditable(false);

consultorjTextField.setEditable(false);

jLabel5.setText("Consultor");

jLabel6.setText("E-mail");

jLabel7.setText("Fone Celular");

jLabel11.setText("Curso");

cursojTextField.setEditable(false);

jLabel12.setText("Cidade");

nomejTextField.setEditable(false);

emailjTextField.setEditable(false);

foneCelularjTextField.setEditable(false);

cidadeEstudajTextField.setEditable(false);

jLabel14.setText("Data Nascimento");

jLabel15.setText("Lingua");

linguajTextField.setEditable(false);

jLabel16.setText("Nível");

niveljTextField.setEditable(false);

universidadejTextField.setEditable(false);

jLabel26.setText("Universidade");

dataNascimentojDateChooser.setEnabled(false);

jLabel27.setText("Sexo");

sexojTextField.setEditable(false);

rgjTextField.setEditable(false);

jLabel28.setText("RG");

dataIniciojDateChooser01.setEnabled(false);

jLabel9.setText("Data de Início Pretendida");

dataIniciojDateChooser02.setEnabled(false);

jLabel13.setText("Data de Término Pretendida");

dataTerminojDateChooser01.setEnabled(false);

dataTerminojDateChooser02.setEnabled(false);

javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
jPanel1.setLayout(jPanel1Layout);
jPanel1Layout.setHorizontalGroup(
    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel26)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(universidadejTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(dataNascimentojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(linguajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(niveljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(cursojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cidadeEstudajTextField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(numeroControlejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataInscricaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unidadeNegociojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(consultorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(foneCelularjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sexojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(rgjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dataIniciojDateChooser01, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dataIniciojDateChooser02, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dataTerminojDateChooser01, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dataTerminojDateChooser02, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(28, 28, 28))))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(jLabel1)
                .addComponent(jLabel4)
                .addComponent(jLabel5))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(numeroControlejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dataInscricaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidadeNegociojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(jLabel3)
                .addComponent(jLabel7))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(foneCelularjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel26)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(universidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11)
                .addComponent(jLabel12))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cursojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cidadeEstudajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel14)
                .addComponent(jLabel15)
                .addComponent(jLabel16))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linguajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(niveljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(dataNascimentojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel27)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(sexojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel28)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(rgjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel9)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataIniciojDateChooser01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataIniciojDateChooser02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel13)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataTerminojDateChooser01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataTerminojDateChooser02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap(66, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Dados da Ficha", jPanel1);

    jLabel17.setText("Skype");

    jLabel18.setText("Passaporte");

    observacaojTextArea.setColumns(20);
    observacaojTextArea.setRows(5);
    jScrollPane1.setViewportView(observacaojTextArea);

    jLabel25.setText("Observação");

    jLabel8.setText("Data Embarque");

    jLabel31.setText("Sponsor");

    jLabel32.setText("Cidade");

    jLabel33.setText("Familia");

    jLabel34.setText("Data Retorno");

    jLabel35.setText("Status do Processo");

    statusProcessojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Placed ", "Pending" }));

    jLabel36.setText("Status do Programa");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(empregadorjTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sponsorjTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(skypejTextField)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(0, 199, Short.MAX_VALUE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dataEmbarquejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel32)
                                .addComponent(cidadeEmpregadorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(passaportejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel36)
                                    .addComponent(statusProgramajTextField))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(dataRetornojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel35)
                        .addComponent(statusProcessojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel33)
                        .addComponent(jLabel25))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)
                        .addComponent(jLabel8))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(skypejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dataEmbarquejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(passaportejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statusProgramajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel31)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sponsorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel32)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cidadeEmpregadorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel33))
                        .addComponent(jLabel34))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(empregadorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataRetornojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel35)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(statusProcessojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.LEADING))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel25)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
            .addContainerGap())
    );

    jTabbedPane1.addTab("Dados de Controle", jPanel2);

    jCheckBox01.setText("Job Guarantee Job Offer");

    jCheckBox02.setText("Data Início Job Offer ");

    jCheckBox03.setText("Data Termino Job Offer");

    jCheckBox04.setText("Email lista de DOCS");

    jCheckBox05.setText("Ficha/Contrato Original");

    jCheckBox06.setText("Informativo Original");

    jCheckBox09.setText("Copia Rg e CPF");

    jCheckBox08.setText("Copia PPT Colorida");

    jCheckBox07.setText("Atestado Original");

    jCheckBox10.setText("Foto DS");

    jCheckBox11.setText("DS160");

    jCheckBox12.setText("CV");

    jCheckBox13.setText("Carta apresentação");

    jCheckBox14.setText("2 cartas recomendação");

    jCheckBox15.setText("Atestado 2º SME Original");

    jCheckBox16.setText("Atestado Saude");

    jCheckBox17.setText("Antecedentes Criminais");

    jCheckBox18.setText("Sleep Teste Corrigido");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(16, 16, 16)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jCheckBox01)
                .addComponent(jCheckBox04)
                .addComponent(jCheckBox07)
                .addComponent(jCheckBox10)
                .addComponent(jCheckBox13)
                .addComponent(jCheckBox16))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jCheckBox02)
                .addComponent(jCheckBox05)
                .addComponent(jCheckBox08)
                .addComponent(jCheckBox11)
                .addComponent(jCheckBox14)
                .addComponent(jCheckBox17))
            .addGap(79, 79, 79)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jCheckBox15)
                .addComponent(jCheckBox12)
                .addComponent(jCheckBox09)
                .addComponent(jCheckBox06)
                .addComponent(jCheckBox03)
                .addComponent(jCheckBox18))
            .addGap(27, 27, 27))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jCheckBox01)
                .addComponent(jCheckBox02)
                .addComponent(jCheckBox03))
            .addGap(18, 18, 18)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jCheckBox04)
                .addComponent(jCheckBox05)
                .addComponent(jCheckBox06))
            .addGap(18, 18, 18)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jCheckBox07)
                .addComponent(jCheckBox08)
                .addComponent(jCheckBox09))
            .addGap(18, 18, 18)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jCheckBox10)
                .addComponent(jCheckBox11)
                .addComponent(jCheckBox12))
            .addGap(18, 18, 18)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jCheckBox13)
                .addComponent(jCheckBox14)
                .addComponent(jCheckBox15))
            .addGap(18, 18, 18)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jCheckBox16)
                .addComponent(jCheckBox17)
                .addComponent(jCheckBox18))
            .addContainerGap(148, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Lista de Controles", jPanel3);

    jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botozinhos/confirmar.png"))); // NOI18N
    jButton5.setText("Confirmar");
    jButton5.setToolTipText("Confirma Atualização");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });

    jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botozinhos/cancel.png"))); // NOI18N
    jButton6.setText("Cancelar");
    jButton6.setToolTipText("Cancela Atualização");
    jButton6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton6ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
    jPanel17.setLayout(jPanel17Layout);
    jPanel17Layout.setHorizontalGroup(
        jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel17Layout.createSequentialGroup()
            .addContainerGap(85, Short.MAX_VALUE)
            .addComponent(jButton5)
            .addGap(37, 37, 37)
            .addComponent(jButton6)
            .addGap(86, 86, 86))
    );
    jPanel17Layout.setVerticalGroup(
        jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel17Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton5)
                .addComponent(jButton6))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(124, 124, 124))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        salvarControleCursos();
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField cidadeEmpregadorjTextField;
    private javax.swing.JTextField cidadeEstudajTextField;
    private javax.swing.JTextField consultorjTextField;
    private javax.swing.JTextField cursojTextField;
    private com.toedter.calendar.JDateChooser dataEmbarquejDateChooser;
    private com.toedter.calendar.JDateChooser dataIniciojDateChooser01;
    private com.toedter.calendar.JDateChooser dataIniciojDateChooser02;
    private com.toedter.calendar.JDateChooser dataInscricaojDateChooser;
    private com.toedter.calendar.JDateChooser dataNascimentojDateChooser;
    private com.toedter.calendar.JDateChooser dataRetornojDateChooser;
    private com.toedter.calendar.JDateChooser dataTerminojDateChooser01;
    private com.toedter.calendar.JDateChooser dataTerminojDateChooser02;
    private javax.swing.JTextField emailjTextField;
    private javax.swing.JTextField empregadorjTextField;
    private javax.swing.JTextField foneCelularjTextField;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox01;
    private javax.swing.JCheckBox jCheckBox02;
    private javax.swing.JCheckBox jCheckBox03;
    private javax.swing.JCheckBox jCheckBox04;
    private javax.swing.JCheckBox jCheckBox05;
    private javax.swing.JCheckBox jCheckBox06;
    private javax.swing.JCheckBox jCheckBox07;
    private javax.swing.JCheckBox jCheckBox08;
    private javax.swing.JCheckBox jCheckBox09;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField linguajTextField;
    private javax.swing.JTextField niveljTextField;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JTextField numeroControlejTextField;
    private javax.swing.JTextArea observacaojTextArea;
    private javax.swing.JTextField passaportejTextField;
    private javax.swing.JTextField rgjTextField;
    private javax.swing.JTextField sexojTextField;
    private javax.swing.JTextField skypejTextField;
    private javax.swing.JTextField sponsorjTextField;
    private javax.swing.JComboBox statusProcessojComboBox;
    private javax.swing.JTextField statusProgramajTextField;
    private javax.swing.JTextField unidadeNegociojTextField;
    private javax.swing.JTextField universidadejTextField;
    // End of variables declaration//GEN-END:variables

    public void salvarControleCursos(){
        if (jCheckBox01.isSelected()){
            controle.setJobGuarante("Sim");
        }else controle.setJobGuarante("Não");
        if (jCheckBox02.isSelected()){
            controle.setDataInicioJobOffer("Sim");
        }else controle.setDataInicioJobOffer("Não");
        if (jCheckBox03.isSelected()){
            controle.setDataTerminoJobOffer("Sim");
        }else controle.setDataTerminoJobOffer("Não");
        if (jCheckBox04.isSelected()){
            controle.setEmailListaDocoumentos("Sim");
        }else controle.setEmailListaDocoumentos("Não");
        if (jCheckBox05.isSelected()){
            controle.setFichaContratoOriginal("Sim");
        }else controle.setFichaContratoOriginal("Não");
        if (jCheckBox06.isSelected()){
            controle.setInformativoOriginal("Sim");
        }else controle.setInformativoOriginal("Não");
        if (jCheckBox07.isSelected()){
            controle.setAtestadoOriginal("Sim");
        }else controle.setAtestadoOriginal("Não");
        if (jCheckBox08.isSelected()){
            controle.setCopiaPPTColorida("Sim");
        }else controle.setCopiaPPTColorida("Não");
        if (jCheckBox09.isSelected()){
            controle.setCopiaRGCPF("Sim");
        }else controle.setCopiaRGCPF("Não");
        if (jCheckBox10.isSelected()){
            controle.setFotoDS("Sim");
        }else controle.setFotoDS("Nào");
        if (jCheckBox11.isSelected()){
            controle.setDs160("Sim");
        }else controle.setDs160("Não");
        if (jCheckBox12.isSelected()){
            controle.setVc("Sim");
        }else controle.setVc("Não");
        if (jCheckBox13.isSelected()){
            controle.setCartaoApresentacao("Sim");
        }else controle.setCartaoApresentacao("Não");
        if (jCheckBox14.isSelected()){
            controle.setCartaoRecomendacao("Sim");
        }else controle.setCartaoRecomendacao("Não");
        if (jCheckBox15.isSelected()){
            controle.setAtestado2SMEOriginal("Sim");
        }else controle.setAtestado2SMEOriginal("Não");
        if (jCheckBox16.isSelected()){
            controle.setAtestadoSaude("Sim");
        }else controle.setAtestadoSaude("Não");
        if (jCheckBox17.isSelected()){
            controle.setAntecedentesCrimianis("Sim");
        }else controle.setAntecedentesCrimianis("Não");
        if (jCheckBox18.isSelected()){
            controle.setSleeptestecorrigido("Sim");
        }else controle.setSleeptestecorrigido("Não");
        controle.setSkype(skypejTextField.getText());
        controle.setDataEmbarque(dataEmbarquejDateChooser.getDate());
        controle.setNumeroPassaporte(passaportejTextField.getText());
        controle.setStatusPrograma(statusProgramajTextField.getText());
        controle.setSponsor(sponsorjTextField.getText());
        controle.setCidadeSponsor(cidadeEmpregadorjTextField.getText());
        controle.setEmpregador(empregadorjTextField.getText());
        controle.setDataRetorno(dataRetornojDateChooser.getDate());
        controle.setStatusProcesso(statusProcessojComboBox.getSelectedItem().toString());
        controle.setObservacoes(observacaojTextArea.getText());
        AupairController aupairController = new AupairController();
        controle = aupairController.salvar(controle);
    }
    
    public void inicializar() {
        AupairController aupairController = new AupairController();
        controle = aupairController.consultarControleAupair(vendasAupair.getIdVendas());
        if (controle != null) {
            numeroControlejTextField.setText(String.valueOf(controle.getIdcontroleAuPair()));
            dataInscricaojDateChooser.setDate(vendasAupair.getDataVenda());
            unidadeNegociojTextField.setText(vendasAupair.getNomeFantasia());
            consultorjTextField.setText(vendasAupair.getNomeConsultor());
            nomejTextField.setText(vendasAupair.getNomeCliente());
            emailjTextField.setText(vendasAupair.getEmail());
            universidadejTextField.setText(vendasAupair.getInituicaoEstuda());
            cursojTextField.setText(vendasAupair.getCurso());
            cidadeEstudajTextField.setText(vendasAupair.getCidadeEndereco());
            dataNascimentojDateChooser.setDate(vendasAupair.getDataNascimento());
            linguajTextField.setText(vendasAupair.getIdioma01());
            niveljTextField.setText(vendasAupair.getNivelidioma01());
            sexojTextField.setText(vendasAupair.getSexo());
            rgjTextField.setText(vendasAupair.getRg());
            dataIniciojDateChooser01.setDate(vendasAupair.getDataInicioPretendida01());
            dataIniciojDateChooser02.setDate(vendasAupair.getDataInicioPretendida02());
            dataTerminojDateChooser01.setDate(vendasAupair.getDataTerminoPretendida01());
            dataTerminojDateChooser02.setDate(vendasAupair.getDataTerminoPretendida02());
            skypejTextField.setText(vendasAupair.getSkype());
            dataEmbarquejDateChooser.setDate(vendasAupair.getDataEmbarque());
            passaportejTextField.setText(vendasAupair.getNumeroPassaporte());
            statusProgramajTextField.setText(vendasAupair.getStatusPrograma());
            sponsorjTextField.setText(vendasAupair.getSponsor());
            cidadeEmpregadorjTextField.setText(vendasAupair.getCidadeSponsor());
            empregadorjTextField.setText(vendasAupair.getEmpregador());
            dataRetornojDateChooser.setDate(vendasAupair.getDataRetorno());
            statusProcessojComboBox.setSelectedItem(vendasAupair.getStatusProcesso());
            observacaojTextArea.setText(vendasAupair.getObservacoes());
            if (vendasAupair.getJobGuarante().equalsIgnoreCase("Sim")){
                jCheckBox01.setSelected(true);
            }else jCheckBox01.setSelected(false);
            if (vendasAupair.getDataInicioJobOffer().equalsIgnoreCase("Sim")){
                jCheckBox02.setSelected(true);
            }else jCheckBox02.setSelected(false);
            if (vendasAupair.getDataTerminoJobOffer().equalsIgnoreCase("Sim")){
                jCheckBox03.setSelected(true);
            }else jCheckBox03.setSelected(false);
            if (vendasAupair.getEmailListaDocoumentos().equalsIgnoreCase("Sim")){
                jCheckBox04.setSelected(true);
            }else jCheckBox04.setSelected(false);
            if (vendasAupair.getFichaContratoOriginal().equalsIgnoreCase("Sim")){
                jCheckBox05.setSelected(true);
            }else jCheckBox05.setSelected(false);
            if (vendasAupair.getInformativoOriginal().equalsIgnoreCase("Sim")){
                jCheckBox06.setSelected(true);
            }else jCheckBox06.setSelected(false);
            if (vendasAupair.getAtestadoOriginal().equalsIgnoreCase("Sim")){
                jCheckBox07.setSelected(true);
            }else jCheckBox07.setSelected(false);
            if (vendasAupair.getCopiaPPTColorida().equalsIgnoreCase("Sim")){
                jCheckBox08.setSelected(true);
            }else jCheckBox08.setSelected(false);
            if (vendasAupair.getCopiaRGCPF().equalsIgnoreCase("Sim")){
                jCheckBox09.setSelected(true);
            }else jCheckBox09.setSelected(false);
            if (vendasAupair.getFotoDS().equalsIgnoreCase("Sim")){
                jCheckBox10.setSelected(true);
            }else jCheckBox10.setSelected(false);
            if (vendasAupair.getDs160().equalsIgnoreCase("Sim")){
                jCheckBox11.setSelected(true);
            }else jCheckBox11.setSelected(false);
            if (vendasAupair.getVc().equalsIgnoreCase("Sim")){
                jCheckBox12.setSelected(true);
            }else jCheckBox12.setSelected(false);
            if (vendasAupair.getCartaoApresentacao().equalsIgnoreCase("Sim")){
                jCheckBox13.setSelected(true);
            }else jCheckBox13.setSelected(false);
            if (vendasAupair.getCartaoRecomendacao().equalsIgnoreCase("Sim")){
                jCheckBox14.setSelected(true);
            }else jCheckBox14.setSelected(false);
            if (vendasAupair.getAtestado2SMEOriginal().equalsIgnoreCase("Sim")){
                jCheckBox15.setSelected(true);
            }else jCheckBox15.setSelected(false);
            if (vendasAupair.getAtestadoSaude().equalsIgnoreCase("Sim")){
                jCheckBox16.setSelected(true);
            }else jCheckBox16.setSelected(false);
            if (vendasAupair.getAntecedentesCrimianis().equalsIgnoreCase("Sim")){
                jCheckBox17.setSelected(true);
            }else jCheckBox17.setSelected(false);
            if (vendasAupair.getSleeptestecorrigido().equalsIgnoreCase("Sim")){
                jCheckBox18.setSelected(true);
            }else jCheckBox18.setSelected(false);   
        }
    }
    public void limitarJText(){
        nomejTextField.setDocument(new LimiteTextoJedit(100));
        emailjTextField.setDocument(new LimiteTextoJedit(100));
        foneCelularjTextField.setDocument(new LimiteTextoJedit(14));        
        universidadejTextField.setDocument(new LimiteTextoJedit(50));
        cursojTextField.setDocument(new LimiteTextoJedit(50));        
        cidadeEstudajTextField.setDocument(new LimiteTextoJedit(50));        
        linguajTextField.setDocument(new LimiteTextoJedit(50));       
        niveljTextField.setDocument(new LimiteTextoJedit(50));     
        sexojTextField.setDocument(new LimiteTextoJedit(9));       
        rgjTextField.setDocument(new LimiteTextoJedit(45));
        skypejTextField.setDocument(new LimiteTextoJedit(100));
        passaportejTextField.setDocument(new LimiteTextoJedit(50));        
        statusProgramajTextField.setDocument(new LimiteTextoJedit(50));        
        sponsorjTextField.setDocument(new LimiteTextoJedit(100));
        cidadeEmpregadorjTextField.setDocument(new LimiteTextoJedit(100));        
        empregadorjTextField.setDocument(new LimiteTextoJedit(100));                    
    }

}
