/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmLocalizarArquivo.java
 *
 * Created on 15/03/2011, 11:47:17
 */

package telas.Arquivo;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.net.URL;
import javax.swing.JFileChooser;
import telas.Cliente.ICliente;
import telas.Usuarios.IUsuario;


/**
 *
 * @author wolverine
 */
public class FrmCarregarArquivo extends javax.swing.JFrame {
    
    private ICliente telaCliente;
    private IUsuario telaUsuario;
    private String tipo;
            
    /** Creates new form FrmLocalizarArquivo */
    public FrmCarregarArquivo(ICliente telaCliente) {
        this.telaCliente = telaCliente;
        initComponents();
        carregarjFileChooser.setFileFilter(null);
        URL url = this.getClass().getResource("/imagens/logo/logotela.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        setVisible(true);
    }
    
    public FrmCarregarArquivo(IUsuario telaIUsuario, String tipo) {
        this.telaUsuario = telaIUsuario;
        this.tipo = tipo;
        initComponents();
        carregarjFileChooser.setFileFilter(null);
        carregarjFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        this.setLocationRelativeTo(null);
        setVisible(true);
    }
    
    
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        carregarjFileChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carregar Arquivo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        carregarjFileChooser.setCurrentDirectory(null);
        carregarjFileChooser.setDialogTitle("Carregar Arquivos");
        carregarjFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carregarjFileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(carregarjFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(carregarjFileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carregarjFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carregarjFileChooserActionPerformed
        if (telaUsuario != null) {
            File curDir = carregarjFileChooser.getCurrentDirectory();
            if (tipo.equalsIgnoreCase("Salvar")){
                this.telaUsuario.setCaminhoPadraoSalvar(curDir.getPath());
            }else this.telaUsuario.setCaminhoPadraoVisualizar(curDir.getPath());
        } else {
            File f = carregarjFileChooser.getSelectedFile();
            this.telaCliente.setArquivo(f);
        }
        this.dispose();
    }//GEN-LAST:event_carregarjFileChooserActionPerformed

    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser carregarjFileChooser;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
