package telas;

import controller.AcessoController;
import controller.GrupoAcessoController;
import controller.ParametrosProdutosController;
import controller.UnidadeNegocioController;
import controller.UsuarioController;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import model.Acesso;
import model.Grupoacesso;
import model.Parametrosprodutos;
import model.Unidadenegocio;
import model.Usuario;
import telas.Usuarios.UsuarioLogadoBean;
import util.Criptografia;
import util.Formatacao;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wolverine
 */
public class FrmLogin extends javax.swing.JDialog {
    
    private UsuarioLogadoBean usuarioLogadoBean;
    private JLabel nomeUsuariojLabel;
    private JLabel unidadejLabel;
    private java.awt.Frame telaPrincipal;
    private int contador;

    /**
     * Creates new form FrmLoginD
     */
    public FrmLogin(java.awt.Frame parent, boolean modal, UsuarioLogadoBean usuarioLogadoBean, JLabel nomeUsuariojLabel, JLabel unidadejLabel) {
        super(parent, modal);
        contador=0;
        this.telaPrincipal = parent;
        this.unidadejLabel = unidadejLabel;
        this.usuarioLogadoBean = usuarioLogadoBean;
        this.nomeUsuariojLabel = nomeUsuariojLabel;
        initComponents();
       try{
            UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);  
            this.pack();  
        }catch (Exception e){
        }
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginjPanel = new javax.swing.JPanel();
        senhajPasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        loginjButton = new javax.swing.JButton();
        sairjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        loginjTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SysTM - Login");

        loginjPanel.setBackground(new java.awt.Color(234, 238, 235));
        loginjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        senhajPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhajPasswordFieldActionPerformed(evt);
            }
        });
        loginjPanel.add(senhajPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, -1));

        jLabel1.setText("Senha de Acesso");
        loginjPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginjButton.setBackground(new java.awt.Color(204, 204, 204));
        loginjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botozinhos/confirmar.png"))); // NOI18N
        loginjButton.setText("Confirmar");
        loginjButton.setToolTipText("Confirma entrada no sistema");
        loginjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginjButtonActionPerformed(evt);
            }
        });
        jPanel3.add(loginjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 120, -1));

        sairjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botozinhos/cancel.png"))); // NOI18N
        sairjButton.setText("Fechar");
        sairjButton.setToolTipText("Sair do Sistema");
        sairjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairjButtonfecharMovimentoCaixa(evt);
            }
        });
        jPanel3.add(sairjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 6, 100, -1));

        loginjPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 250, 40));

        jLabel2.setText("Login do Usuário");
        loginjPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        loginjPanel.add(loginjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void senhajPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhajPasswordFieldActionPerformed
        loginjButtonActionPerformed(evt);
    }//GEN-LAST:event_senhajPasswordFieldActionPerformed

    private void loginjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginjButtonActionPerformed
        UsuarioController usuarioController = new UsuarioController();
        Usuario usuario;
        String senha = Formatacao.SenhaString(senhajPasswordField.getPassword());
        if (senhajPasswordField.getPassword().length > 0) {
            try {
                senha = Criptografia.encript(senha);
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
            usuario = usuarioController.consultar(loginjTextField.getText(), senha);
            if (usuario == null) {
                JOptionPane.showMessageDialog(null, "Usuario e/ou Senha não conferem");
                verificarContagem();
            } else {
                usuarioLogadoBean.setUsuario(usuario);
                GrupoAcessoController grupoAcessoController = new GrupoAcessoController();
                Grupoacesso grupoAcesso = grupoAcessoController.consultar(usuario.getGrupoacesso());
                usuarioLogadoBean.setGrupoAcesso(grupoAcesso);
                AcessoController acessoController = new AcessoController();
                Acesso acesso = acessoController.consultar(grupoAcesso.getAcesso());
                usuarioLogadoBean.setAcesso(acesso);
                ParametrosProdutosController parametrosProdutosController = new ParametrosProdutosController();
                Parametrosprodutos parametrosprodutos = parametrosProdutosController.consultar();
                usuarioLogadoBean.setParametrosprodutos(parametrosprodutos);
                nomeUsuariojLabel.setText("Usuário : " + usuario.getNome());
                UnidadeNegocioController unidadeNegocioController = new UnidadeNegocioController();
                Unidadenegocio unidadenegocio = unidadeNegocioController.consultar(usuario.getUnidadenegocio());
                usuarioLogadoBean.setUnidadeNegocio(unidadenegocio);
                unidadejLabel.setText("Unidade : " + unidadenegocio.getNomeFantasia());
                String versao = "1.72";
                if (!usuarioLogadoBean.getUnidadeNegocio().getVersao().equalsIgnoreCase(versao)){
                    JOptionPane.showMessageDialog(rootPane, "SysTM possui nova versão " + versao + "\b\n"
                    + "Favor Atualizar nova versão");
                    System.exit(0);
                }
                this.dispose();
            }
        }else {
            JOptionPane.showMessageDialog(rootPane, "Campo senha em branco");
        }
    }//GEN-LAST:event_loginjButtonActionPerformed

    private void sairjButtonfecharMovimentoCaixa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairjButtonfecharMovimentoCaixa
        System.exit(0);
    }//GEN-LAST:event_sairjButtonfecharMovimentoCaixa

    /**
     * @param args the command line arguments
     */
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginjButton;
    private javax.swing.JPanel loginjPanel;
    private javax.swing.JTextField loginjTextField;
    private javax.swing.JButton sairjButton;
    private javax.swing.JPasswordField senhajPasswordField;
    // End of variables declaration//GEN-END:variables

    public void verificarContagem(){
        if (contador>4){
            JOptionPane.showMessageDialog(rootPane, "Excedeu numero de tentativas");
            System.exit(0);
        }else {
            contador++;
            loginjTextField.setText("");
            senhajPasswordField.setText("");
            loginjTextField.requestFocus();
        }
    }

}
