/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package telas.Invoice;

import com.toedter.calendar.JTextFieldDateEditor;
import controller.InvoicesController;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import model.Invoices;
import model.view.Viewconsultainvoice;
import util.Formatacao;
import util.LimiteTextoJedit;

/**
 *
 * @author Wolverine
 */
public class FrmCadastrarInvoice extends javax.swing.JFrame {
    
    private String datePattern;
    private String maskPattern;
    private char placeHolder;
    private Invoices invoice;
    private float cambioVenda;

    /**
     * Creates new form FrmCadastrarInvoice
     */
    public FrmCadastrarInvoice(Viewconsultainvoice viewInvoice) {
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/##";
        placeHolder = '_';
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo/logotela.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        limitarJText();
        carregarInvoice(viewInvoice);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeClientejTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        unidadeNegociojTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        produtojTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fornecedorjTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dataPrevistaPagtojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
            maskPattern, placeHolder));
    jLabel6 = new javax.swing.JLabel();
    valorPrevistoPagtojTextField = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    moedajTextField = new javax.swing.JTextField();
    cambioVendajTextField = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    dataPagtojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jLabel10 = new javax.swing.JLabel();
valorPagojTextField = new javax.swing.JTextField();
cambioPagtojTextField = new javax.swing.JTextField();
jLabel11 = new javax.swing.JLabel();
valorPagtojTextField = new javax.swing.JTextField();
jLabel12 = new javax.swing.JLabel();
jLabel13 = new javax.swing.JLabel();
perdaCambiojTextField = new javax.swing.JTextField();
jPanel3 = new javax.swing.JPanel();
jLabel19 = new javax.swing.JLabel();
valorAcomodacaojTextField = new javax.swing.JTextField();
jLabel20 = new javax.swing.JLabel();
dataPrevisaoAcomodacaojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
    maskPattern, placeHolder));
    jLabel21 = new javax.swing.JLabel();
    dataPagtoAcomodacaojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
taxajTextField = new javax.swing.JTextField();
jLabel14 = new javax.swing.JLabel();
jPanel17 = new javax.swing.JPanel();
jButton5 = new javax.swing.JButton();
jButton6 = new javax.swing.JButton();

setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
setTitle("Invoice");

jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

jLabel1.setText("Nome do Cliente");

nomeClientejTextField.setEnabled(false);

jLabel2.setText("Unidade de Negócio");

unidadeNegociojTextField.setEnabled(false);

jLabel3.setText("Produto");

produtojTextField.setEnabled(false);

jLabel4.setText("Fornecedor");

fornecedorjTextField.setEnabled(false);

jLabel5.setText("Data Prevista Pagto");

dataPrevistaPagtojDateChooser.setEnabled(false);
dataPrevistaPagtojDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
    public void focusGained(java.awt.event.FocusEvent evt) {
        dataPrevistaPagtojDateChooserFocusGained(evt);
    }
    });

    jLabel6.setText("Valor Previsto Pagto");

    valorPrevistoPagtojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorPrevistoPagtojTextField.setEnabled(false);

    jLabel7.setText("Moeda");

    moedajTextField.setEnabled(false);

    cambioVendajTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    cambioVendajTextField.setEnabled(false);

    jLabel8.setText("Câmbio Venda");

    jLabel9.setText("Data Pagamento");

    dataPagtojDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataPagtojDateChooserFocusGained(evt);
        }
    });

    jLabel10.setText("Valor Pago");

    valorPagojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorPagojTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            valorPagojTextFieldFocusGained(evt);
        }
    });

    cambioPagtojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    cambioPagtojTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            cambioPagtojTextFieldFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            cambioPagtojTextFieldFocusLost(evt);
        }
    });
    cambioPagtojTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cambioPagtojTextFieldActionPerformed(evt);
        }
    });

    jLabel11.setText("Câmbio Pagto");

    valorPagtojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorPagtojTextField.setEnabled(false);

    jLabel12.setText("Valor NET");

    jLabel13.setText("Perda/Ganho");

    perdaCambiojTextField.setEditable(false);
    perdaCambiojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Acomodação"));

    jLabel19.setText("Valor da Acomodação");

    valorAcomodacaojTextField.setEnabled(false);

    jLabel20.setText("Previsão Pagamento");

    dataPrevisaoAcomodacaojDateChooser.setEnabled(false);

    jLabel21.setText("Data de Pagamento");

    dataPagtoAcomodacaojDateChooser.setEnabled(false);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel19)
                .addComponent(valorAcomodacaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dataPrevisaoAcomodacaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel20))
            .addGap(47, 47, 47)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dataPagtoAcomodacaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel21))
            .addGap(56, 56, 56))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jLabel19)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(valorAcomodacaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(jLabel21))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataPrevisaoAcomodacaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataPagtoAcomodacaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(0, 8, Short.MAX_VALUE))
    );

    taxajTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    taxajTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            taxajTextFieldFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            taxajTextFieldFocusLost(evt);
        }
    });

    jLabel14.setText("Taxa");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(nomeClientejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dataPrevistaPagtojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(dataPagtojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valorPrevistoPagtojTextField)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(valorPagojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2)
                                .addComponent(unidadeNegociojTextField)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(moedajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel12)
                                            .addGap(8, 26, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(cambioVendajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(valorPagtojTextField))))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(taxajTextField)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(0, 37, Short.MAX_VALUE)))
                            .addGap(22, 22, 22)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cambioPagtojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(perdaCambiojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(produtojTextField)
                    .addGap(25, 25, 25)
                    .addComponent(fornecedorjTextField)))
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jLabel2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(nomeClientejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(unidadeNegociojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(jLabel4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(produtojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(fornecedorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(jLabel6)
                .addComponent(jLabel7)
                .addComponent(jLabel8)
                .addComponent(jLabel12))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(dataPrevistaPagtojDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorPrevistoPagtojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moedajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cambioVendajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorPagtojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel9)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dataPagtojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addComponent(jLabel10)
                        .addComponent(jLabel14))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cambioPagtojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(perdaCambiojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(valorPagojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(taxajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botozinhos/confirmar.png"))); // NOI18N
    jButton5.setText("Confirmar");
    jButton5.setToolTipText("Confirma Cadastro de Invoice");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });

    jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botozinhos/cancel.png"))); // NOI18N
    jButton6.setText("Cancelar");
    jButton6.setToolTipText("Cancela Ficha de Curso");
    jButton6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton6ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
    jPanel17.setLayout(jPanel17Layout);
    jPanel17Layout.setHorizontalGroup(
        jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel17Layout.createSequentialGroup()
            .addContainerGap(85, Short.MAX_VALUE)
            .addComponent(jButton5)
            .addGap(61, 61, 61)
            .addComponent(jButton6)
            .addGap(62, 62, 62))
    );
    jPanel17Layout.setVerticalGroup(
        jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel17Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton5)
                .addComponent(jButton6))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataPrevistaPagtojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataPrevistaPagtojDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataPrevistaPagtojDateChooserFocusGained

    private void dataPagtojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataPagtojDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataPagtojDateChooserFocusGained

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (valorPagojTextField.getText().length()>0){
            invoice.setValorPago(Formatacao.formatarStringfloat(valorPagojTextField.getText()));
        }
        invoice.setDataPagamentoInvoice(dataPagtojDateChooser.getDate());
        if (cambioPagtojTextField.getText().length()>0){
            invoice.setCambioPagamento(Formatacao.formatarStringfloat(cambioPagtojTextField.getText()));
        }
        if (perdaCambiojTextField.getText().length()>0){
            invoice.setGanhoCambio(Formatacao.formatarStringfloat(perdaCambiojTextField.getText()));
        }
        InvoicesController invoicesController = new InvoicesController();
        invoice = invoicesController.salvar(invoice);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void cambioPagtojTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cambioPagtojTextFieldFocusLost
       float valorPago = Formatacao.formatarStringfloat(valorPagojTextField.getText());
        Float valorVenda = valorPago * cambioVenda;
        float cambioPagto = Formatacao.formatarStringfloat(cambioPagtojTextField.getText());
        Float valorPagto = valorPago * cambioPagto;
        Float valorFinal = valorVenda - valorPagto;
        Float taxa = 0.0f;
        if (taxajTextField.getText().length()>0){
            taxa = Formatacao.formatarStringfloat(taxajTextField.getText());
        }
        valorFinal = valorFinal - taxa;
        perdaCambiojTextField.setText(Formatacao.formatarFloatString(valorFinal));
    }//GEN-LAST:event_cambioPagtojTextFieldFocusLost

    private void taxajTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_taxajTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_taxajTextFieldFocusLost

    private void valorPagojTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorPagojTextFieldFocusGained
        valorPagojTextField.selectAll();
    }//GEN-LAST:event_valorPagojTextFieldFocusGained

    private void taxajTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_taxajTextFieldFocusGained
        taxajTextField.selectAll();
    }//GEN-LAST:event_taxajTextFieldFocusGained

    private void cambioPagtojTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cambioPagtojTextFieldFocusGained
        cambioPagtojTextField.selectAll();
    }//GEN-LAST:event_cambioPagtojTextFieldFocusGained

    private void cambioPagtojTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambioPagtojTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cambioPagtojTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cambioPagtojTextField;
    private javax.swing.JTextField cambioVendajTextField;
    private com.toedter.calendar.JDateChooser dataPagtoAcomodacaojDateChooser;
    private com.toedter.calendar.JDateChooser dataPagtojDateChooser;
    private com.toedter.calendar.JDateChooser dataPrevisaoAcomodacaojDateChooser;
    private com.toedter.calendar.JDateChooser dataPrevistaPagtojDateChooser;
    private javax.swing.JTextField fornecedorjTextField;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField moedajTextField;
    private javax.swing.JTextField nomeClientejTextField;
    private javax.swing.JTextField perdaCambiojTextField;
    private javax.swing.JTextField produtojTextField;
    private javax.swing.JTextField taxajTextField;
    private javax.swing.JTextField unidadeNegociojTextField;
    private javax.swing.JTextField valorAcomodacaojTextField;
    private javax.swing.JTextField valorPagojTextField;
    private javax.swing.JTextField valorPagtojTextField;
    private javax.swing.JTextField valorPrevistoPagtojTextField;
    // End of variables declaration//GEN-END:variables

    public void carregarInvoice(Viewconsultainvoice viewInvoice){
        cambioVenda = viewInvoice.getValorCambio();
        nomeClientejTextField.setText(viewInvoice.getNomeCliente());
        unidadeNegociojTextField.setText(viewInvoice.getNomeFantasia());
        produtojTextField.setText(viewInvoice.getDescricao());
        fornecedorjTextField.setText(viewInvoice.getNomeFornecedor());
        dataPrevistaPagtojDateChooser.setDate(viewInvoice.getDataPrevistaPagamento());
        valorPrevistoPagtojTextField.setText(Formatacao.formatarFloatString(viewInvoice.getValorPrevistoInvoice()));
        moedajTextField.setText(viewInvoice.getSigla());
        cambioVendajTextField.setText(Formatacao.formatarFloatString(viewInvoice.getValorCambio()));
        valorPagtojTextField.setText(Formatacao.formatarFloatString(viewInvoice.getValorPagamentoInvoice()));
        valorPagojTextField.setText(Formatacao.formatarFloatString(viewInvoice.getValorPago()));
        cambioPagtojTextField.setText(Formatacao.formatarFloatString(viewInvoice.getCambioPagamento()));
        perdaCambiojTextField.setText(Formatacao.formatarFloatString(viewInvoice.getGanhoCambio()));
        InvoicesController invoicesController = new InvoicesController();
        invoice = invoicesController.consultar(viewInvoice.getIdinvoices());
    }
    public void limitarJText(){
       nomeClientejTextField.setDocument(new LimiteTextoJedit(100));    
    }
    
}
