/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.Cursos.Controle;

import com.toedter.calendar.JTextFieldDateEditor;
import controller.CursosController;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import model.Controlecursos;
import model.view.Viewcontrolecursos;
import telas.Usuarios.UsuarioLogadoBean;
import util.Formatacao;
import util.LimiteTextoJedit;

/**
 *
 * @author Wolverine
 */
public class FrmAtulizarControleCurso extends javax.swing.JFrame {
    
    private String datePattern;
    private String maskPattern;
    private char placeHolder;
    private Controlecursos controle;
    private Viewcontrolecursos vendasCursos;
    private UsuarioLogadoBean usuarioLogadoBean;
  //  private List<Viewcontrolecursos> listaVendas;
    
 
    /**
     * Creates new form FrmAtulizarControleCurso
     */
    public FrmAtulizarControleCurso(Viewcontrolecursos vendasCursos, UsuarioLogadoBean usuarioLogadoBean) {
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/##";
        placeHolder = '_';
        this.usuarioLogadoBean = usuarioLogadoBean;
        this.vendasCursos = vendasCursos;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo/logotela.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        limitarJText();        
        inicializar();
        if (usuarioLogadoBean.getUsuario().getTipo().equalsIgnoreCase("Unidade")){
            jTabbedPane1.setEnabled(false);
        }
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        workjTextField = new javax.swing.JTextField();
        dataEnvioInscricaojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
            maskPattern, placeHolder));
    jLabel18 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    jLabel19 = new javax.swing.JLabel();
    valorAcomodacaojTextField = new javax.swing.JTextField();
    jLabel20 = new javax.swing.JLabel();
    dataPrevisaoAcomodacaojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jLabel21 = new javax.swing.JLabel();
dataPagtoAcomodacaojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
    maskPattern, placeHolder));
    jPanel5 = new javax.swing.JPanel();
    vistoNaoEmitidojRadioButton = new javax.swing.JRadioButton();
    vistoEmitidojRadioButton = new javax.swing.JRadioButton();
    jPanel6 = new javax.swing.JPanel();
    orientacaoNaojRadioButton = new javax.swing.JRadioButton();
    orientacaoSimjRadioButton = new javax.swing.JRadioButton();
    jLabel25 = new javax.swing.JLabel();
    dataEmbarquejDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jLabel8 = new javax.swing.JLabel();
jPanel8 = new javax.swing.JPanel();
possuiAcomodacaojComboBox = new javax.swing.JComboBox();
jPanel7 = new javax.swing.JPanel();
kitNaoRecebidojRadioButton = new javax.swing.JRadioButton();
kitRecebidojRadioButton = new javax.swing.JRadioButton();
jLabel26 = new javax.swing.JLabel();
jScrollPane1 = new javax.swing.JScrollPane();
loasjTextArea = new javax.swing.JTextArea();
jPanel1 = new javax.swing.JPanel();
jLabel2 = new javax.swing.JLabel();
numeroControlejTextField = new javax.swing.JTextField();
jLabel1 = new javax.swing.JLabel();
dataInscricaojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
    maskPattern, placeHolder));
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    unidadeNegociojTextField = new javax.swing.JTextField();
    consultorjTextField = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    dataInicioCursojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jLabel10 = new javax.swing.JLabel();
programajTextField = new javax.swing.JTextField();
jLabel11 = new javax.swing.JLabel();
paisDestinojTextField = new javax.swing.JTextField();
jLabel12 = new javax.swing.JLabel();
jLabel13 = new javax.swing.JLabel();
nomejTextField = new javax.swing.JTextField();
emailjTextField = new javax.swing.JTextField();
foneCelularjTextField = new javax.swing.JTextField();
idadejTextField4 = new javax.swing.JTextField();
cidadeDestinojTextField = new javax.swing.JTextField();
jLabel14 = new javax.swing.JLabel();
duracaojTextField = new javax.swing.JTextField();
jLabel15 = new javax.swing.JLabel();
tipoAcomodacaojTextField = new javax.swing.JTextField();
jLabel16 = new javax.swing.JLabel();
numeroVTMjTextField = new javax.swing.JTextField();
jPanel17 = new javax.swing.JPanel();
jButton5 = new javax.swing.JButton();
jButton6 = new javax.swing.JButton();

setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
setTitle("Atualizar Controle de Cursos");

jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
    public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jTabbedPane1StateChanged(evt);
    }
    });

    jLabel17.setText("Work(Semanas)");

    jLabel18.setText("Data Envio Inscrição");

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Acomodação"));

    jLabel19.setText("Valor da Acomodação");

    valorAcomodacaojTextField.setEnabled(false);

    jLabel20.setText("Previsão Pagamento");

    dataPrevisaoAcomodacaojDateChooser.setEnabled(false);

    jLabel21.setText("Data de Pagamento");

    dataPagtoAcomodacaojDateChooser.setEnabled(false);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel19)
                .addComponent(valorAcomodacaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(86, 86, 86)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dataPrevisaoAcomodacaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel20))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dataPagtoAcomodacaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel21))
            .addGap(19, 19, 19))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jLabel19)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(valorAcomodacaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(jLabel21))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataPrevisaoAcomodacaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataPagtoAcomodacaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(0, 8, Short.MAX_VALUE))
    );

    jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Visto Emitido"));

    buttonGroup1.add(vistoNaoEmitidojRadioButton);
    vistoNaoEmitidojRadioButton.setText("Não");

    buttonGroup1.add(vistoEmitidojRadioButton);
    vistoEmitidojRadioButton.setText("Sim");

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
            .addContainerGap(108, Short.MAX_VALUE)
            .addComponent(vistoNaoEmitidojRadioButton)
            .addContainerGap())
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(vistoEmitidojRadioButton)
                .addContainerGap(108, Short.MAX_VALUE)))
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addComponent(vistoNaoEmitidojRadioButton)
            .addContainerGap(18, Short.MAX_VALUE))
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(vistoEmitidojRadioButton)
                .addContainerGap(16, Short.MAX_VALUE)))
    );

    jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Orientação Pré Embarque"));

    buttonGroup2.add(orientacaoNaojRadioButton);
    orientacaoNaojRadioButton.setText("Não");

    buttonGroup2.add(orientacaoSimjRadioButton);
    orientacaoSimjRadioButton.setText("Sim");

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
            .addContainerGap(114, Short.MAX_VALUE)
            .addComponent(orientacaoNaojRadioButton)
            .addContainerGap())
        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(orientacaoSimjRadioButton)
                .addContainerGap(114, Short.MAX_VALUE)))
    );
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addComponent(orientacaoNaojRadioButton)
            .addContainerGap(9, Short.MAX_VALUE))
        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(orientacaoSimjRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );

    jLabel25.setText("LOAS + Obs");

    jLabel8.setText("Data Embarque");

    jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Possui Acomodação"));

    possuiAcomodacaojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Sim" }));
    possuiAcomodacaojComboBox.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            possuiAcomodacaojComboBoxItemStateChanged(evt);
        }
    });

    javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
    jPanel8.setLayout(jPanel8Layout);
    jPanel8Layout.setHorizontalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel8Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(possuiAcomodacaojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(27, Short.MAX_VALUE))
    );
    jPanel8Layout.setVerticalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
            .addContainerGap(17, Short.MAX_VALUE)
            .addComponent(possuiAcomodacaojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Recebeu Kit Viagem"));

    buttonGroup3.add(kitNaoRecebidojRadioButton);
    kitNaoRecebidojRadioButton.setText("Não");

    buttonGroup3.add(kitRecebidojRadioButton);
    kitRecebidojRadioButton.setText("Sim");

    javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
    jPanel7.setLayout(jPanel7Layout);
    jPanel7Layout.setHorizontalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
            .addContainerGap(89, Short.MAX_VALUE)
            .addComponent(kitNaoRecebidojRadioButton)
            .addGap(25, 25, 25))
        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(kitRecebidojRadioButton)
                .addContainerGap(108, Short.MAX_VALUE)))
    );
    jPanel7Layout.setVerticalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel7Layout.createSequentialGroup()
            .addComponent(kitNaoRecebidojRadioButton)
            .addContainerGap(18, Short.MAX_VALUE))
        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(kitRecebidojRadioButton)
                .addContainerGap(16, Short.MAX_VALUE)))
    );

    jLabel26.setText("LOAS + Obs");

    loasjTextArea.setColumns(20);
    loasjTextArea.setRows(5);
    jScrollPane1.setViewportView(loasjTextArea);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel26)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(workjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(dataEnvioInscricaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dataEmbarquejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(1034, 1034, 1034)
                    .addComponent(jLabel25))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(workjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dataEnvioInscricaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dataEmbarquejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel25)
                .addComponent(jLabel26))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(245, 245, 245))
    );

    jTabbedPane1.addTab("Dados de Controle", jPanel2);

    jLabel2.setText("Nº Controle");

    numeroControlejTextField.setEditable(false);

    jLabel1.setText("Data Inscrição");

    dataInscricaojDateChooser.setEnabled(false);

    jLabel3.setText("Nome");

    jLabel4.setText("Unidade Negócio");

    unidadeNegociojTextField.setEditable(false);

    consultorjTextField.setEditable(false);

    jLabel5.setText("Consultor");

    jLabel6.setText("E-mail");

    jLabel7.setText("Fone Celular");

    jLabel9.setText("Início do Curso");

    dataInicioCursojDateChooser.setEnabled(false);

    jLabel10.setText("Programa");

    programajTextField.setEditable(false);

    jLabel11.setText("País de Destino");

    paisDestinojTextField.setEditable(false);

    jLabel12.setText("Cidade de Destino");

    jLabel13.setText("Idade");

    nomejTextField.setEditable(false);

    emailjTextField.setEditable(false);

    foneCelularjTextField.setEditable(false);

    idadejTextField4.setEditable(false);

    cidadeDestinojTextField.setEditable(false);

    jLabel14.setText("Duração(Semanas)");

    duracaojTextField.setEditable(false);

    jLabel15.setText("Tipo de Acomodação");

    tipoAcomodacaojTextField.setEditable(false);

    jLabel16.setText("Número do VTM");

    numeroVTMjTextField.setEditable(false);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(numeroControlejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(11, 11, 11)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataInscricaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(unidadeNegociojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(consultorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(duracaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(tipoAcomodacaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(numeroVTMjTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(paisDestinojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel10)))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cidadeDestinojTextField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(dataInicioCursojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(programajTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(209, 209, 209)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(foneCelularjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(idadejTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(jLabel1)
                .addComponent(jLabel4)
                .addComponent(jLabel5))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(numeroControlejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dataInscricaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(consultorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(unidadeNegociojTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3)
                .addComponent(jLabel6)
                .addComponent(jLabel7)
                .addComponent(jLabel13))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(foneCelularjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(idadejTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel9)
                .addComponent(jLabel10))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(dataInicioCursojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(programajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11)
                .addComponent(jLabel12))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(paisDestinojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cidadeDestinojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel14)
                .addComponent(jLabel15)
                .addComponent(jLabel16))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(duracaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tipoAcomodacaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(numeroVTMjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(208, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Dados da Ficha", jPanel1);

    jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botozinhos/confirmar.png"))); // NOI18N
    jButton5.setText("Confirmar");
    jButton5.setToolTipText("Confirma Cadastro da Ficha de Curso");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });

    jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botozinhos/cancel.png"))); // NOI18N
    jButton6.setText("Cancelar");
    jButton6.setToolTipText("Cancela Ficha de Curso");
    jButton6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton6ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
    jPanel17.setLayout(jPanel17Layout);
    jPanel17Layout.setHorizontalGroup(
        jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel17Layout.createSequentialGroup()
            .addContainerGap(85, Short.MAX_VALUE)
            .addComponent(jButton5)
            .addGap(37, 37, 37)
            .addComponent(jButton6)
            .addGap(86, 86, 86))
    );
    jPanel17Layout.setVerticalGroup(
        jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel17Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton5)
                .addComponent(jButton6))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addContainerGap())
        .addGroup(layout.createSequentialGroup()
            .addGap(139, 139, 139)
            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(116, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        salvarControleCursos();
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void possuiAcomodacaojComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_possuiAcomodacaojComboBoxItemStateChanged
        if (possuiAcomodacaojComboBox.getSelectedItem().toString().equalsIgnoreCase("Sim")){
            valorAcomodacaojTextField.setEnabled(true);
            dataPrevisaoAcomodacaojDateChooser.setEnabled(true);
            dataPagtoAcomodacaojDateChooser.setEnabled(true);
        }else {
            valorAcomodacaojTextField.setEnabled(false);
            dataPrevisaoAcomodacaojDateChooser.setEnabled(false);
            dataPagtoAcomodacaojDateChooser.setEnabled(false);
        }
    }//GEN-LAST:event_possuiAcomodacaojComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField cidadeDestinojTextField;
    private javax.swing.JTextField consultorjTextField;
    private com.toedter.calendar.JDateChooser dataEmbarquejDateChooser;
    private com.toedter.calendar.JDateChooser dataEnvioInscricaojDateChooser;
    private com.toedter.calendar.JDateChooser dataInicioCursojDateChooser;
    private com.toedter.calendar.JDateChooser dataInscricaojDateChooser;
    private com.toedter.calendar.JDateChooser dataPagtoAcomodacaojDateChooser;
    private com.toedter.calendar.JDateChooser dataPrevisaoAcomodacaojDateChooser;
    private javax.swing.JTextField duracaojTextField;
    private javax.swing.JTextField emailjTextField;
    private javax.swing.JTextField foneCelularjTextField;
    private javax.swing.JTextField idadejTextField4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton kitNaoRecebidojRadioButton;
    private javax.swing.JRadioButton kitRecebidojRadioButton;
    private javax.swing.JTextArea loasjTextArea;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JTextField numeroControlejTextField;
    private javax.swing.JTextField numeroVTMjTextField;
    private javax.swing.JRadioButton orientacaoNaojRadioButton;
    private javax.swing.JRadioButton orientacaoSimjRadioButton;
    private javax.swing.JTextField paisDestinojTextField;
    private javax.swing.JComboBox possuiAcomodacaojComboBox;
    private javax.swing.JTextField programajTextField;
    private javax.swing.JTextField tipoAcomodacaojTextField;
    private javax.swing.JTextField unidadeNegociojTextField;
    private javax.swing.JTextField valorAcomodacaojTextField;
    private javax.swing.JRadioButton vistoEmitidojRadioButton;
    private javax.swing.JRadioButton vistoNaoEmitidojRadioButton;
    private javax.swing.JTextField workjTextField;
    // End of variables declaration//GEN-END:variables

    public void salvarControleCursos(){
        controle.setDataEmbarque(dataEmbarquejDateChooser.getDate());
        controle.setDataEnvioInscricaoEscola(dataEnvioInscricaojDateChooser.getDate());
        if (kitRecebidojRadioButton.isSelected()){
            controle.setKitViagem("Sim");
        }else controle.setKitViagem("Não");
        if (vistoEmitidojRadioButton.isSelected()){
            controle.setVisto("Sim");
        }else controle.setVisto("Não");
        if (orientacaoSimjRadioButton.isSelected()){
            controle.setOrientacaoPreEmbarque("Sim");
        }else controle.setOrientacaoPreEmbarque("Não");
        controle.setPossuiAcomidacao(possuiAcomodacaojComboBox.getSelectedItem().toString());
        controle.setLoasObs(loasjTextArea.getText());
        controle.setPagamentoAcomodacao(dataPagtoAcomodacaojDateChooser.getDate());
        controle.setPrevisaoPagamentoAcomodacao(dataPrevisaoAcomodacaojDateChooser.getDate());
        controle.setValorAcomodacao(Formatacao.formatarStringfloat(valorAcomodacaojTextField.getText()));
        controle.setWork(Integer.parseInt(workjTextField.getText()));
        CursosController cursosController = new CursosController();
        controle = cursosController.salvar(controle);
    }
    
    public void inicializar(){
        CursosController cursosController = new CursosController();
        controle = cursosController.consultarControleCursos(vendasCursos.getIdVendas(), vendasCursos.getIdcontroleCursos());
        if (controle!=null){
            workjTextField.setText(String.valueOf(controle.getWork()));
            dataEnvioInscricaojDateChooser.setDate(controle.getDataEnvioInscricaoEscola());
            dataEmbarquejDateChooser.setDate(controle.getDataEmbarque());
            valorAcomodacaojTextField.setText(Formatacao.formatarFloatString(controle.getValorAcomodacao()));
            dataPrevisaoAcomodacaojDateChooser.setDate(controle.getPrevisaoPagamentoAcomodacao());
            dataPagtoAcomodacaojDateChooser.setDate(controle.getPagamentoAcomodacao());
            possuiAcomodacaojComboBox.setSelectedItem(controle.getPossuiAcomidacao());
            if (possuiAcomodacaojComboBox.getSelectedItem().toString().equalsIgnoreCase("Sim")) {
                valorAcomodacaojTextField.setEnabled(true);
                dataPrevisaoAcomodacaojDateChooser.setEnabled(true);
                dataPagtoAcomodacaojDateChooser.setEnabled(true);
            } else {
                valorAcomodacaojTextField.setEnabled(false);
                dataPrevisaoAcomodacaojDateChooser.setEnabled(false);
                dataPagtoAcomodacaojDateChooser.setEnabled(false);
            }
            if (controle.getVisto().equalsIgnoreCase("Sim")){
                vistoEmitidojRadioButton.setSelected(true);
            }else vistoNaoEmitidojRadioButton.setSelected(true);
            if (controle.getOrientacaoPreEmbarque().equalsIgnoreCase("Sim")){
                orientacaoSimjRadioButton.setSelected(true);
            }else orientacaoNaojRadioButton.setSelected(true);
            if (controle.getKitViagem().equalsIgnoreCase("Sim")){
                kitRecebidojRadioButton.setSelected(true);
            }else kitNaoRecebidojRadioButton.setSelected(true);
            loasjTextArea.setText(controle.getLoasObs());
            numeroControlejTextField.setText(String.valueOf(vendasCursos.getIdVendas()));
            dataInscricaojDateChooser.setDate(vendasCursos.getDataVenda());
            unidadeNegociojTextField.setText(vendasCursos.getNomeFantasia());
            consultorjTextField.setText(vendasCursos.getNomeUsuario());
            nomejTextField.setText(vendasCursos.getNomeCliente());
            emailjTextField.setText(vendasCursos.getEmail());
            foneCelularjTextField.setText(vendasCursos.getFoneCelular());
            dataInicioCursojDateChooser.setDate(vendasCursos.getDataInicio());
            programajTextField.setText(vendasCursos.getNomeCurso());
            paisDestinojTextField.setText(vendasCursos.getPais());
            cidadeDestinojTextField.setText(vendasCursos.getCidade());
            duracaojTextField.setText(String.valueOf(vendasCursos.getNumeroSenamas()));
            tipoAcomodacaojTextField.setText(vendasCursos.getTipoAcomodacao());
            numeroVTMjTextField.setText(vendasCursos.getNumeroCartaoVTM());
        }
    }
    public void limitarJText(){
        nomejTextField.setDocument(new LimiteTextoJedit(100));
        emailjTextField.setDocument(new LimiteTextoJedit(100));
        foneCelularjTextField.setDocument(new LimiteTextoJedit(14));
        programajTextField.setDocument(new LimiteTextoJedit(100));
        paisDestinojTextField.setDocument(new LimiteTextoJedit(50));
        cidadeDestinojTextField.setDocument(new LimiteTextoJedit(50));        
        duracaojTextField.setDocument(new LimiteTextoJedit(50));
        tipoAcomodacaojTextField.setDocument(new LimiteTextoJedit(50));
        numeroVTMjTextField.setDocument(new LimiteTextoJedit(45));
        
    }

}
