/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package telas.HighSchool.Valores;

import com.toedter.calendar.JTextFieldDateEditor;
import controller.CambioController;
import controller.FiltroOrcamentoProdutoController;
import controller.ParametrosProdutosController;
import controller.ValorHighSchoolController;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.List;
import javax.swing.JOptionPane;
import model.Filtroorcamentoproduto;
import model.Fornecedorcidade;
import model.Moedas;
import model.Parametrosprodutos;
import model.Valoreshighschool;
import telas.Fornecedor.FrmConsultaFornecedor;
import telas.Usuarios.UsuarioLogadoBean;
import util.Formatacao;
import util.LimiteTextoJedit;

/**
 *
 * @author Wolverine
 */
public class FrmCadastrarValoresHighSchool extends javax.swing.JFrame implements IValoresHighSchool{
    
    private Fornecedorcidade fornecedorCidade;
    private Valoreshighschool valoreshighschool;
    private UsuarioLogadoBean usuarioLogadoBean;
    private String datePattern;
    private String maskPattern;
    private char placeHolder;

    /**
     * Creates new form FrmCadastrarValoresHighSchool
     */
    public FrmCadastrarValoresHighSchool(UsuarioLogadoBean usuarioLogadoBean, Valoreshighschool valores) {
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/##";
        placeHolder = '_';
        this.usuarioLogadoBean = usuarioLogadoBean;
        this.valoreshighschool = valores;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo/logotela.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        limitarJText();
        carregarComboBox();
        iniciaizarDados();       
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fornecedorjTextField = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        iniciojTextField = new javax.swing.JTextField();
        valornetjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        moedasVendasjComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        produtojComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        valorgrossjTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        duracaojComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        moedasComissaojComboBox = new javax.swing.JComboBox();
        valorPremiumjTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        valorExpressjTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        dataInicioDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
            maskPattern, placeHolder));
    jLabel11 = new javax.swing.JLabel();
    jPanel17 = new javax.swing.JPanel();
    jButton5 = new javax.swing.JButton();
    jButton6 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Cadastrar Valores High School");

    jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabel1.setText("Fornecedor");

    fornecedorjTextField.setEditable(false);

    jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botozinhos/selecionar.png"))); // NOI18N
    jButton7.setText("Selecionar");
    jButton7.setToolTipText("Selecionar Fornecedor");
    jButton7.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton7ActionPerformed(evt);
        }
    });

    jLabel2.setText("Duração");

    jLabel3.setText("Ínicio");

    valornetjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valornetjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            valornetjTextFieldKeyTyped(evt);
        }
    });

    jLabel4.setText("Valor Net");

    jLabel5.setText("Moeda");

    jLabel6.setText("Produto Orçamento");

    valorgrossjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorgrossjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            valorgrossjTextFieldKeyTyped(evt);
        }
    });

    jLabel7.setText("Valor Gross");

    duracaojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01 Semetre", "02 Semetre" }));

    jLabel8.setText("Moeda Comissão");

    valorPremiumjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorPremiumjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            valorPremiumjTextFieldKeyTyped(evt);
        }
    });

    jLabel9.setText("Comissão Premium");

    valorExpressjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorExpressjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            valorExpressjTextFieldKeyTyped(evt);
        }
    });

    jLabel10.setText("Comissão Express");

    dataInicioDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataInicioDateChooserFocusGained(evt);
        }
    });

    jLabel11.setText("Data Inicio");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(duracaojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(iniciojTextField))
                .addComponent(produtojComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(moedasComissaojComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(valorPremiumjTextField)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(valorExpressjTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataInicioDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(fornecedorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(177, 177, 177)
                                    .addComponent(jLabel3))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(valornetjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(valorgrossjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(96, 96, 96))
                                        .addComponent(moedasVendasjComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(fornecedorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton7))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(jLabel3))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(iniciojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(duracaojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(jLabel5)
                .addComponent(jLabel7))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(valornetjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(moedasVendasjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(valorgrossjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(produtojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(moedasComissaojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(valorPremiumjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(valorExpressjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel11)
                    .addGap(26, 26, 26))
                .addComponent(dataInicioDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botozinhos/confirmar.png"))); // NOI18N
    jButton5.setText("Confirmar");
    jButton5.setToolTipText("Confirma Cadastro");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });

    jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botozinhos/cancel.png"))); // NOI18N
    jButton6.setText("Cancelar");
    jButton6.setToolTipText("Cancela Cadastro");
    jButton6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton6ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
    jPanel17.setLayout(jPanel17Layout);
    jPanel17Layout.setHorizontalGroup(
        jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel17Layout.createSequentialGroup()
            .addContainerGap(85, Short.MAX_VALUE)
            .addComponent(jButton5)
            .addGap(37, 37, 37)
            .addComponent(jButton6)
            .addGap(86, 86, 86))
    );
    jPanel17Layout.setVerticalGroup(
        jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel17Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton5)
                .addComponent(jButton6))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(39, 39, 39))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        ParametrosProdutosController parametrosProdutosController = new ParametrosProdutosController();
        Parametrosprodutos parametrosprodutos = parametrosProdutosController.consultar();
        new FrmConsultaFornecedor(usuarioLogadoBean, this, parametrosprodutos.getHighSchool());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String msg = validarDados();
        if (msg.length() < 5) {
            valoreshighschool.setDuracao(duracaojComboBox.getSelectedItem().toString());
            valoreshighschool.setInicio(iniciojTextField.getText());
            Moedas moeda = (Moedas) moedasVendasjComboBox.getSelectedItem();
            valoreshighschool.setMoedas(moeda);
            moeda = (Moedas) moedasComissaojComboBox.getSelectedItem();
            valoreshighschool.setMoedas1(moeda);
            valoreshighschool.setFornecedor(fornecedorCidade.getFornecedor());
            valoreshighschool.setFornecedorcidade(fornecedorCidade);
            valoreshighschool.setComissaoexpress(Formatacao.formatarStringfloat(valorExpressjTextField.getText()));
            valoreshighschool.setComissaopremium(Formatacao.formatarStringfloat(valorPremiumjTextField.getText()));
            valoreshighschool.setValornet(Formatacao.formatarStringfloat(valornetjTextField.getText()));
            valoreshighschool.setValorgross(Formatacao.formatarStringfloat(valorgrossjTextField.getText()));
            Filtroorcamentoproduto  filtroorcamentoproduto = ((Filtroorcamentoproduto) produtojComboBox.getSelectedItem());
            valoreshighschool.setProdutosorcamento(filtroorcamentoproduto.getProdutosorcamento());
            valoreshighschool.setDatainicio(dataInicioDateChooser.getDate());
            ValorHighSchoolController valorHighSchoolController = new ValorHighSchoolController();
            valorHighSchoolController.salvar(valoreshighschool);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, msg);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void valornetjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valornetjTextFieldKeyTyped
        if (evt.getKeyChar()=='.'){
            evt.setKeyChar(',');
        }
        String caracteres = "0987654321-,";
        if (evt.getKeyChar() != '\b') {
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_valornetjTextFieldKeyTyped

    private void valorgrossjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorgrossjTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_valorgrossjTextFieldKeyTyped

    private void valorPremiumjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorPremiumjTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_valorPremiumjTextFieldKeyTyped

    private void valorExpressjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorExpressjTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_valorExpressjTextFieldKeyTyped

    private void dataInicioDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataInicioDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataInicioDateChooserFocusGained

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dataInicioDateChooser;
    private javax.swing.JComboBox duracaojComboBox;
    private javax.swing.JTextField fornecedorjTextField;
    private javax.swing.JTextField iniciojTextField;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JComboBox moedasComissaojComboBox;
    private javax.swing.JComboBox moedasVendasjComboBox;
    private javax.swing.JComboBox produtojComboBox;
    private javax.swing.JTextField valorExpressjTextField;
    private javax.swing.JTextField valorPremiumjTextField;
    private javax.swing.JTextField valorgrossjTextField;
    private javax.swing.JTextField valornetjTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setFornecedor(Fornecedorcidade fornecedorCidade) {
        if (fornecedorCidade!=null){
            this.fornecedorCidade= fornecedorCidade;
            fornecedorjTextField.setText(fornecedorCidade.getFornecedor().getNome());
        }
    }

    @Override
    public void setModel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void iniciaizarDados(){
        if (valoreshighschool!=null){
            if (valoreshighschool.getFornecedorcidade()!=null){
                fornecedorCidade = valoreshighschool.getFornecedorcidade();
                fornecedorjTextField.setText(fornecedorCidade.getFornecedor().getNome());
            }
            iniciojTextField.setText(valoreshighschool.getInicio());
            duracaojComboBox.setSelectedItem(valoreshighschool.getDuracao());
            valornetjTextField.setText(Formatacao.formatarFloatString(valoreshighschool.getValornet()));
            valorgrossjTextField.setText(Formatacao.formatarFloatString(valoreshighschool.getValorgross()));
            moedasVendasjComboBox.setSelectedItem(valoreshighschool.getMoedas());
            moedasComissaojComboBox.setSelectedItem(valoreshighschool.getMoedas1());
            valorExpressjTextField.setText(Formatacao.formatarFloatString(valoreshighschool.getComissaoexpress()));
            valorPremiumjTextField.setText(Formatacao.formatarFloatString(valoreshighschool.getComissaopremium()));
            dataInicioDateChooser.setDate(valoreshighschool.getDatainicio());
            produtojComboBox.setSelectedItem(valoreshighschool.getProdutosorcamento().getFiltroorcamentoprodutoList().get(0));
        }else {
            valoreshighschool = new Valoreshighschool();
            valoreshighschool.setSituacao("Ativo");
        }
    }
    
    public String validarDados(){
        String msg ="";
        if (iniciojTextField.getText().length()==0){
            msg = msg + "Campo duração não preenchido\r\n";
        }
        if (valornetjTextField.getText().length()==0){
            msg = msg + "Campo valor não preenchido\r\n";
        }
        if (fornecedorCidade==null){
            msg = msg + "Fornecedor não informada\r\n";
        }
        if(dataInicioDateChooser==null){
            msg = msg + "Data de início não informada\r\n";
        }
        return msg;
    }
    
    public void carregarComboBox() {
        FiltroOrcamentoProdutoController filtroOrcamentoProdutoController = new FiltroOrcamentoProdutoController();
        List<Filtroorcamentoproduto> listaProdutosFiltro = filtroOrcamentoProdutoController.pesquisar(usuarioLogadoBean.getParametrosprodutos().getHighSchool());
        produtojComboBox = Formatacao.preencherComobox(listaProdutosFiltro, produtojComboBox, false, null);
        CambioController cambioController = new CambioController();
        List<Moedas> listaMoedas = cambioController.listaMoedas();
        moedasVendasjComboBox = Formatacao.preencherComobox(listaMoedas, moedasVendasjComboBox, false, null);
        moedasComissaojComboBox = Formatacao.preencherComobox(listaMoedas, moedasComissaojComboBox, false, null);
    }
    
    public void limitarJText(){
        iniciojTextField.setDocument(new LimiteTextoJedit(100));
    }
}
