/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.CotacaoPacotes;

import controller.CotacaoPacotesController;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumnModel;
import model.Cotacaopacotes;
import model.view.Viewconsultacotacaopacote;
import telas.FollowUp.JTableRenderer;
import telas.Usuarios.UsuarioLogadoBean;
import util.relatoriosJasper;



/**
 *
 * @author Wolverine
 */
public class FrmConsultaCotacaoPacotes extends javax.swing.JFrame {
    
        private UsuarioLogadoBean usuarioLogadoBean;
        private List<Viewconsultacotacaopacote> listaCotacao;
        private ConsultaCotacaoPacotesTableModel modelCotacao;

    /**
     * Creates new form FrmConsultaCotacaoPacotes
     */
    public FrmConsultaCotacaoPacotes(UsuarioLogadoBean usuarioLogadoBean) {
        this.usuarioLogadoBean = usuarioLogadoBean;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo/logotela.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        carregarModel(gerarConsulta());
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cotacaojTable = new javax.swing.JTable();
        BarradeTarefasjToolBar4 = new javax.swing.JToolBar();
        AdicionarjButton4 = new javax.swing.JButton();
        imprimirjButton2 = new javax.swing.JButton();
        excluirjButton = new javax.swing.JButton();
        imprimirjButton4 = new javax.swing.JButton();
        SeparadordeTarefasjSeparator = new javax.swing.JToolBar.Separator();
        imprimirjButton = new javax.swing.JButton();
        imprimirjButton1 = new javax.swing.JButton();
        FecharrjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Cotação Pacotes");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cotacaojTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(cotacaojTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        BarradeTarefasjToolBar4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BarradeTarefasjToolBar4.setFloatable(false);
        BarradeTarefasjToolBar4.setRollover(true);

        AdicionarjButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/adicionar.png"))); // NOI18N
        AdicionarjButton4.setText("Nova");
        AdicionarjButton4.setToolTipText("Nova Ficha de Curso");
        AdicionarjButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AdicionarjButton4.setMaximumSize(new java.awt.Dimension(80, 90));
        AdicionarjButton4.setMinimumSize(new java.awt.Dimension(80, 90));
        AdicionarjButton4.setName(""); // NOI18N
        AdicionarjButton4.setPreferredSize(new java.awt.Dimension(80, 90));
        AdicionarjButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AdicionarjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarjButton4ActionPerformed(evt);
            }
        });
        BarradeTarefasjToolBar4.add(AdicionarjButton4);

        imprimirjButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/VER DADOS.png"))); // NOI18N
        imprimirjButton2.setText("Visualizar");
        imprimirjButton2.setToolTipText("Imprimir Documentos");
        imprimirjButton2.setFocusable(false);
        imprimirjButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imprimirjButton2.setMaximumSize(new java.awt.Dimension(80, 90));
        imprimirjButton2.setMinimumSize(new java.awt.Dimension(80, 90));
        imprimirjButton2.setPreferredSize(new java.awt.Dimension(80, 90));
        imprimirjButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        imprimirjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirjButton2ActionPerformed(evt);
            }
        });
        BarradeTarefasjToolBar4.add(imprimirjButton2);

        excluirjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/cancelar.png"))); // NOI18N
        excluirjButton.setText("Cancelar");
        excluirjButton.setToolTipText("Cancelar Ficha de Curso");
        excluirjButton.setFocusable(false);
        excluirjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        excluirjButton.setMaximumSize(new java.awt.Dimension(80, 90));
        excluirjButton.setMinimumSize(new java.awt.Dimension(80, 90));
        excluirjButton.setPreferredSize(new java.awt.Dimension(80, 90));
        excluirjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        excluirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirjButtonActionPerformed(evt);
            }
        });
        BarradeTarefasjToolBar4.add(excluirjButton);

        imprimirjButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/finalizar.png"))); // NOI18N
        imprimirjButton4.setText("Finalizar");
        imprimirjButton4.setToolTipText("Finalizar Ficha");
        imprimirjButton4.setFocusable(false);
        imprimirjButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imprimirjButton4.setMaximumSize(new java.awt.Dimension(80, 90));
        imprimirjButton4.setMinimumSize(new java.awt.Dimension(80, 90));
        imprimirjButton4.setPreferredSize(new java.awt.Dimension(80, 90));
        imprimirjButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        imprimirjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirjButton4ActionPerformed(evt);
            }
        });
        BarradeTarefasjToolBar4.add(imprimirjButton4);
        BarradeTarefasjToolBar4.add(SeparadordeTarefasjSeparator);

        imprimirjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/imprimir.png"))); // NOI18N
        imprimirjButton.setText("Imprimir");
        imprimirjButton.setToolTipText("Imprimir Documentos");
        imprimirjButton.setFocusable(false);
        imprimirjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imprimirjButton.setMaximumSize(new java.awt.Dimension(80, 90));
        imprimirjButton.setMinimumSize(new java.awt.Dimension(80, 90));
        imprimirjButton.setPreferredSize(new java.awt.Dimension(80, 90));
        imprimirjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        imprimirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirjButtonActionPerformed(evt);
            }
        });
        BarradeTarefasjToolBar4.add(imprimirjButton);

        imprimirjButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/pesquisar.png"))); // NOI18N
        imprimirjButton1.setText("Pesquisar");
        imprimirjButton1.setToolTipText("Pesquisar Ficha de Curso");
        imprimirjButton1.setEnabled(false);
        imprimirjButton1.setFocusable(false);
        imprimirjButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imprimirjButton1.setMaximumSize(new java.awt.Dimension(80, 90));
        imprimirjButton1.setMinimumSize(new java.awt.Dimension(80, 90));
        imprimirjButton1.setPreferredSize(new java.awt.Dimension(80, 90));
        imprimirjButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        imprimirjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirjButton1ActionPerformed(evt);
            }
        });
        BarradeTarefasjToolBar4.add(imprimirjButton1);

        FecharrjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/fechar.png"))); // NOI18N
        FecharrjButton.setText("Fechar");
        FecharrjButton.setToolTipText("Fechar");
        FecharrjButton.setFocusable(false);
        FecharrjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        FecharrjButton.setMaximumSize(new java.awt.Dimension(80, 90));
        FecharrjButton.setMinimumSize(new java.awt.Dimension(80, 90));
        FecharrjButton.setPreferredSize(new java.awt.Dimension(80, 90));
        FecharrjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        FecharrjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharrjButtonActionPerformed(evt);
            }
        });
        BarradeTarefasjToolBar4.add(FecharrjButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(117, 117, 117)
                    .addComponent(BarradeTarefasjToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(104, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(301, 301, 301)
                    .addComponent(BarradeTarefasjToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdicionarjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarjButton4ActionPerformed
        new FrmCotacaoPacotes(usuarioLogadoBean);
        
    }//GEN-LAST:event_AdicionarjButton4ActionPerformed

    private void excluirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirjButtonActionPerformed
        int linha = cotacaojTable.getSelectedRow();
        if (linha>=0){
            boolean resultado = JOptionPane.showConfirmDialog(null, "Confirma Cancelamento?", "Cancelar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0;
            if (resultado) {
                CotacaoPacotesController cotacaoPacotesController = new CotacaoPacotesController();
                Cotacaopacotes cotacaopacotes = cotacaoPacotesController.consultar(listaCotacao.get(linha).getIdcotacaoPacotes());
                if (cotacaopacotes!=null){
                    cotacaopacotes.setSituacao("Cancelada");
                    cotacaoPacotesController.salvar(cotacaopacotes);
                    JOptionPane.showMessageDialog(rootPane, "Cotação Cancelada");
                }
                carregarModel(gerarConsulta());
            }
        }
    }//GEN-LAST:event_excluirjButtonActionPerformed

    private void imprimirjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirjButton4ActionPerformed
        int linha = cotacaojTable.getSelectedRow();
        if (linha>=0){
            boolean resultado = JOptionPane.showConfirmDialog(null, "Confirma Finalização ?", "Cancelar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0;
            if (resultado) {
                CotacaoPacotesController cotacaoPacotesController = new CotacaoPacotesController();
                Cotacaopacotes cotacaopacotes = cotacaoPacotesController.consultar(listaCotacao.get(linha).getIdcotacaoPacotes());
                if (cotacaopacotes!=null){
                    cotacaopacotes.setSituacao("Finalizada");
                    cotacaoPacotesController.salvar(cotacaopacotes);
                    JOptionPane.showMessageDialog(rootPane, "Cotação Cancelada");
                }
                carregarModel(gerarConsulta());
            }
        }
    }//GEN-LAST:event_imprimirjButton4ActionPerformed

    private void imprimirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirjButtonActionPerformed
            imprimirCotacao();
    }//GEN-LAST:event_imprimirjButtonActionPerformed

    private void imprimirjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirjButton1ActionPerformed
        
    }//GEN-LAST:event_imprimirjButton1ActionPerformed

    private void FecharrjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharrjButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_FecharrjButtonActionPerformed

    private void imprimirjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirjButton2ActionPerformed
        int linha = cotacaojTable.getSelectedRow();
        if (linha>=0){
            new FrmCotacaoPacotes(listaCotacao.get(linha));
        }else JOptionPane.showMessageDialog(rootPane, "Selecione uma cotação");
    }//GEN-LAST:event_imprimirjButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarjButton4;
    private javax.swing.JToolBar BarradeTarefasjToolBar4;
    private javax.swing.JButton FecharrjButton;
    private javax.swing.JToolBar.Separator SeparadordeTarefasjSeparator;
    private javax.swing.JTable cotacaojTable;
    private javax.swing.JButton excluirjButton;
    private javax.swing.JButton imprimirjButton;
    private javax.swing.JButton imprimirjButton1;
    private javax.swing.JButton imprimirjButton2;
    private javax.swing.JButton imprimirjButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void carregarModel(String sql){
        CotacaoPacotesController cotacaoPacotesController = new CotacaoPacotesController();
        listaCotacao = cotacaoPacotesController.lista(sql);
        if (listaCotacao==null){
            listaCotacao = new ArrayList<Viewconsultacotacaopacote>();
        }
        modelCotacao = new ConsultaCotacaoPacotesTableModel(listaCotacao);
        cotacaojTable.setModel(modelCotacao);
        
        TableColumnModel ColumnModel = cotacaojTable.getColumnModel();  
        JTableRenderer renderer = new JTableRenderer();
        cotacaojTable.getColumnModel().getColumn(0).setCellRenderer(renderer);
        cotacaojTable.getColumnModel().getColumn(0).setPreferredWidth(80);
        cotacaojTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        cotacaojTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        cotacaojTable.getColumnModel().getColumn(3).setPreferredWidth(300);
        cotacaojTable.getColumnModel().getColumn(4).setPreferredWidth(300);
        cotacaojTable.getColumnModel().getColumn(5).setPreferredWidth(200);
        cotacaojTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        cotacaojTable.repaint();
    }
    
    public String gerarConsulta(){
        String sql;
        if (usuarioLogadoBean.getUsuario().getTipo().equalsIgnoreCase("Gerencail")){
            sql = "Select v from Viewconsultacotacaopacote v where v.situacao='Pendente'";
        }else sql = "Select v from Viewconsultacotacaopacote v where v.situacao='Pendente' and v.idunidadeNegocio=" + usuarioLogadoBean.getUnidadeNegocio().getIdunidadeNegocio();
        return sql;
    }
    
    public void imprimirCotacao() {
        int linha = cotacaojTable.getSelectedRow();
        if (linha >= 0) {
            String url = ("telas/CotacaoPacotes/Relatorios/cotacaoPacotes.jasper");
            Map parameters = new HashMap();
            try {
                parameters.put("idPacotes", listaCotacao.get(linha).getIdcotacaoPacotes());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Não foi possível gerar o relatório " + ex);
                ex.printStackTrace();
            }
            new relatoriosJasper(url, parameters);
        }else JOptionPane.showMessageDialog(rootPane, "Selecionar um cotação");
    }


}
