
package telas.CotacaoPacotes;

import com.toedter.calendar.JTextFieldDateEditor;
import controller.CotacaoPacotesController;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Cotacaopacotes;
import model.view.Viewconsultacotacaopacote;
import telas.Usuarios.UsuarioLogadoBean;
import util.Formatacao;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ti2
 */
public class FrmCotacaoPacotes extends javax.swing.JFrame {
    
    private UsuarioLogadoBean usuarioLogadoBean;
    private String datePattern;
    private String maskPattern;
    private char placeHolder;
    

    /**
     * Creates new form JFrameturismoSystm
     */
    public FrmCotacaoPacotes(UsuarioLogadoBean usuarioLogadoBean) {
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/##";
        placeHolder = '_';
        this.usuarioLogadoBean = usuarioLogadoBean;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo/logotela.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        origemClientejTextField.setText(usuarioLogadoBean.getUnidadeNegocio().getNomeFantasia());
        nomeClientejTextField.setText(usuarioLogadoBean.getUsuario().getNome());
        this.setVisible(true);
    }
    
    public FrmCotacaoPacotes(Viewconsultacotacaopacote viewconsultacotacaopacote) {
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/##";
        placeHolder = '_';
        this.usuarioLogadoBean = usuarioLogadoBean;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo/logotela.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        visualizarCotacao(viewconsultacotacaopacote);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoApartamentobuttonGroup = new javax.swing.ButtonGroup();
        tipoPacotebuttonGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        origemjTextField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        destinojTextField = new javax.swing.JTextField();
        dataIdajDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
            maskPattern, placeHolder));
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    dataRetornojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jLabel5 = new javax.swing.JLabel();
origemClientejTextField = new javax.swing.JTextField();
nomeClientejTextField = new javax.swing.JTextField();
jLabel6 = new javax.swing.JLabel();
jPanel3 = new javax.swing.JPanel();
pacoteCompletojCheckBox = new javax.swing.JCheckBox();
pacoteTerrestrejCheckBox = new javax.swing.JCheckBox();
jPanel4 = new javax.swing.JPanel();
jLabel11 = new javax.swing.JLabel();
jLabel12 = new javax.swing.JLabel();
categoriajComboBox = new javax.swing.JComboBox();
twinjCheckBox = new javax.swing.JCheckBox();
casaljCheckBox = new javax.swing.JCheckBox();
quadruplojCheckBox = new javax.swing.JCheckBox();
triplojCheckBox = new javax.swing.JCheckBox();
duplojCheckBox = new javax.swing.JCheckBox();
jPanel5 = new javax.swing.JPanel();
segurojCheckBox = new javax.swing.JCheckBox();
carrojCheckBox = new javax.swing.JCheckBox();
jLabel13 = new javax.swing.JLabel();
retiradajTextField = new javax.swing.JTextField();
jLabel14 = new javax.swing.JLabel();
entregajTextField = new javax.swing.JTextField();
jPanel12 = new javax.swing.JPanel();
jLabel1 = new javax.swing.JLabel();
adljTextField = new javax.swing.JTextField();
jLabel2 = new javax.swing.JLabel();
chd5jTextField = new javax.swing.JTextField();
jLabel26 = new javax.swing.JLabel();
chd10jTextField = new javax.swing.JTextField();
jLabel27 = new javax.swing.JLabel();
infjTextField = new javax.swing.JTextField();
jPanel13 = new javax.swing.JPanel();
jLabel28 = new javax.swing.JLabel();
valorjTextField = new javax.swing.JTextField();
jPanel11 = new javax.swing.JPanel();
jScrollPane1 = new javax.swing.JScrollPane();
observacaojTextArea = new javax.swing.JTextArea();
jPanel2 = new javax.swing.JPanel();
confirmajButton = new javax.swing.JButton();
jButton2 = new javax.swing.JButton();

setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
setTitle("Cotação de Pacotes");

jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Data especifica da viagem"));

jLabel24.setText("Origem");

origemjTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

jLabel25.setText("Destino");

destinojTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
destinojTextField.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField2ActionPerformed(evt);
    }
    });

    dataIdajDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataIdajDateChooserFocusGained(evt);
        }
    });

    jLabel3.setText("Data IDA");

    jLabel4.setText("Data Retorno");

    dataRetornojDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataRetornojDateChooserFocusGained(evt);
        }
    });

    jLabel5.setText("Origem do Cliente");

    jLabel6.setText("Nome do Cliente");

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(origemClientejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(nomeClientejTextField))
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(196, 196, 196)
                            .addComponent(jLabel6))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dataIdajDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(4, 4, 4)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(dataRetornojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(origemjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel24))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel25)
                                .addComponent(destinojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(jLabel6))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(origemClientejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(nomeClientejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataIdajDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(origemjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(destinojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(dataRetornojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
    );

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Pacote"));

    tipoPacotebuttonGroup.add(pacoteCompletojCheckBox);
    pacoteCompletojCheckBox.setSelected(true);
    pacoteCompletojCheckBox.setText("Pacote completo(Aéreo+ hotel+ serviços)");
    pacoteCompletojCheckBox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            pacoteCompletojCheckBoxActionPerformed(evt);
        }
    });

    tipoPacotebuttonGroup.add(pacoteTerrestrejCheckBox);
    pacoteTerrestrejCheckBox.setText("Somente terrestre(hotel e serviços)");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pacoteCompletojCheckBox)
                .addComponent(pacoteTerrestrejCheckBox))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(pacoteCompletojCheckBox)
            .addGap(33, 33, 33)
            .addComponent(pacoteTerrestrejCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Hotel"));

    jLabel11.setText("Tipo de apartamento");

    jLabel12.setText("Categoria :");

    categoriajComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " 1 Estrela", " 2 Estrelas", " 3 Estrelas", " 4 Estrelas", " 5 Estrelas" }));

    tipoApartamentobuttonGroup.add(twinjCheckBox);
    twinjCheckBox.setText("Twin");

    tipoApartamentobuttonGroup.add(casaljCheckBox);
    casaljCheckBox.setText("Casal");
    casaljCheckBox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            casaljCheckBoxActionPerformed(evt);
        }
    });

    tipoApartamentobuttonGroup.add(quadruplojCheckBox);
    quadruplojCheckBox.setText("QDP");
    quadruplojCheckBox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            quadruplojCheckBoxActionPerformed(evt);
        }
    });

    tipoApartamentobuttonGroup.add(triplojCheckBox);
    triplojCheckBox.setText("Triplo");

    tipoApartamentobuttonGroup.add(duplojCheckBox);
    duplojCheckBox.setText("Duplo");
    duplojCheckBox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            duplojCheckBoxActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(duplojCheckBox)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(triplojCheckBox)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(quadruplojCheckBox)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(casaljCheckBox)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(twinjCheckBox))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jLabel12)
                    .addGap(18, 18, 18)
                    .addComponent(categoriajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel11))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel12)
                .addComponent(categoriajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(duplojCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(quadruplojCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(casaljCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(twinjCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(triplojCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );

    jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    segurojCheckBox.setText("Seguro");

    carrojCheckBox.setText("Carro");
    carrojCheckBox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            carrojCheckBoxActionPerformed(evt);
        }
    });

    jLabel13.setText("Retirada");

    retiradajTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            retiradajTextFieldActionPerformed(evt);
        }
    });

    jLabel14.setText("Entrega");

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(retiradajTextField)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE))
                .addComponent(entregajTextField)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(segurojCheckBox)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carrojCheckBox)))
            .addContainerGap())
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(segurojCheckBox)
                .addComponent(carrojCheckBox))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel13)
            .addGap(5, 5, 5)
            .addComponent(retiradajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel14)
            .addGap(5, 5, 5)
            .addComponent(entregajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(12, Short.MAX_VALUE))
    );

    jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Número de pessoas"));

    jLabel1.setText("ADL acima de 10 anos");

    jLabel2.setText("CHD 1 a 5 anos");

    jLabel26.setText("CHD 5 a 10 anos");

    jLabel27.setText("INF menos de 1 ano");

    javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
    jPanel12.setLayout(jPanel12Layout);
    jPanel12Layout.setHorizontalGroup(
        jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel12Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(31, 31, 31))
                        .addComponent(chd5jTextField))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(infjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel26)
                        .addComponent(chd10jTextField))))
            .addContainerGap(19, Short.MAX_VALUE))
    );
    jPanel12Layout.setVerticalGroup(
        jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel12Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(adljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addComponent(jLabel26)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(chd10jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(chd5jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addComponent(jLabel27)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(infjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(0, 2, Short.MAX_VALUE))
    );

    jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabel28.setText("VALOR TOTAL DE INVESTIMENTO PARA ESTA VIAGEM R$ :");

    valorjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

    javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
    jPanel13.setLayout(jPanel13Layout);
    jPanel13Layout.setHorizontalGroup(
        jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel13Layout.createSequentialGroup()
            .addGap(28, 28, 28)
            .addComponent(jLabel28)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(valorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    jPanel13Layout.setVerticalGroup(
        jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel13Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel28)
                .addComponent(valorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
    jPanel10.setLayout(jPanel10Layout);
    jPanel10Layout.setHorizontalGroup(
        jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel10Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(33, Short.MAX_VALUE))
    );
    jPanel10Layout.setVerticalGroup(
        jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel10Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(26, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Dados Cotação", jPanel10);

    observacaojTextArea.setColumns(20);
    observacaojTextArea.setRows(5);
    jScrollPane1.setViewportView(observacaojTextArea);

    javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
    jPanel11.setLayout(jPanel11Layout);
    jPanel11Layout.setHorizontalGroup(
        jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel11Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
            .addContainerGap())
    );
    jPanel11Layout.setVerticalGroup(
        jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel11Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
            .addContainerGap())
    );

    jTabbedPane1.addTab("Observação", jPanel11);

    jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    confirmajButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botozinhos/confirmar.png"))); // NOI18N
    confirmajButton.setText("Confirmar");
    confirmajButton.setToolTipText("Confirmar Cadastro do Usuário");
    confirmajButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            confirmajButtonActionPerformed(evt);
        }
    });

    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botozinhos/cancel.png"))); // NOI18N
    jButton2.setText("Cancelar");
    jButton2.setToolTipText("Cancela Cadastro do Usuário");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(confirmajButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
            .addComponent(jButton2)
            .addGap(34, 34, 34))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(confirmajButton)
                .addComponent(jButton2))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(134, 134, 134)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(layout.createSequentialGroup()
            .addComponent(jTabbedPane1)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retiradajTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retiradajTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retiradajTextFieldActionPerformed

    private void carrojCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrojCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carrojCheckBoxActionPerformed

    private void duplojCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duplojCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duplojCheckBoxActionPerformed

    private void quadruplojCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quadruplojCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quadruplojCheckBoxActionPerformed

    private void casaljCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casaljCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casaljCheckBoxActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void dataIdajDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataIdajDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataIdajDateChooserFocusGained

    private void dataRetornojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataRetornojDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataRetornojDateChooserFocusGained

    private void pacoteCompletojCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacoteCompletojCheckBoxActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_pacoteCompletojCheckBoxActionPerformed

    private void confirmajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmajButtonActionPerformed
        Cotacaopacotes cotacaoPacotes = new Cotacaopacotes();
        cotacaoPacotes.setDataSolicitacao(new Date());
        cotacaoPacotes.setHoraSolicitacao(Formatacao.foramtarHoraString());
        cotacaoPacotes.setOrigemCliente(origemClientejTextField.getText());
        cotacaoPacotes.setCliente(nomeClientejTextField.getText());
        cotacaoPacotes.setDataIda(dataIdajDateChooser.getDate());
        cotacaoPacotes.setDataRetorno(dataRetornojDateChooser.getDate());
        cotacaoPacotes.setOrigram(origemjTextField.getText());
        cotacaoPacotes.setDestino(destinojTextField.getText());
        if (pacoteCompletojCheckBox.isSelected()){
            cotacaoPacotes.setTipoPacote("C");
        }else cotacaoPacotes.setTipoPacote("T");
        if (adljTextField.getText().length()>0){
            cotacaoPacotes.setNumeroAdultos(Integer.parseInt(adljTextField.getText()));
        }
        if (chd5jTextField.getText().length()>0){
            cotacaoPacotes.setNumeroCriancas5(Integer.parseInt(chd5jTextField.getText()));
        }
        if (chd10jTextField.getText().length()>0){
            cotacaoPacotes.setNumeroCriancas10(Integer.parseInt(chd10jTextField.getText()));
        }
        if (infjTextField.getText().length()>0){
            cotacaoPacotes.setNumeroBebes(Integer.parseInt(infjTextField.getText()));
        }
        cotacaoPacotes.setTipoHotel(categoriajComboBox.getSelectedItem().toString());
        if (duplojCheckBox.isSelected()){
            cotacaoPacotes.setTipoApartamento("Duplo");
        }
        if (triplojCheckBox.isSelected()){
            cotacaoPacotes.setTipoApartamento("Triplo");
        }
        if (quadruplojCheckBox.isSelected()){
            cotacaoPacotes.setTipoApartamento("Quadruplo");
        }
        if (casaljCheckBox.isSelected()){
            cotacaoPacotes.setTipoApartamento("Casal");
        }
        if (twinjCheckBox.isSelected()){
            cotacaoPacotes.setTipoApartamento("Twin");
        }
        if (segurojCheckBox.isSelected()){
            cotacaoPacotes.setSeguro("X");
        }else cotacaoPacotes.setSeguro("");
        if (carrojCheckBox.isSelected()){
            cotacaoPacotes.setCarro("X");
            cotacaoPacotes.setLocalRetiradaCarro(retiradajTextField.getText());
            cotacaoPacotes.setLocalEntregaCarro(entregajTextField.getText());
        }else {
            cotacaoPacotes.setCarro("");
            cotacaoPacotes.setLocalRetiradaCarro("");
            cotacaoPacotes.setLocalEntregaCarro("");
        }
        if (valorjTextField.getText().length()>0){
            cotacaoPacotes.setValorInvestimento(Formatacao.formatarStringfloat(valorjTextField.getText()));
        }
        cotacaoPacotes.setObservacao(observacaojTextArea.getText());
        cotacaoPacotes.setSituacao("Pendente");
        cotacaoPacotes.setUsuario(usuarioLogadoBean.getUsuario().getIdusuario());
        cotacaoPacotes.setUnidadenegocio(usuarioLogadoBean.getUnidadeNegocio().getIdunidadeNegocio());
        CotacaoPacotesController cotacaoPacotesController = new CotacaoPacotesController();
        cotacaoPacotes = cotacaoPacotesController.salvar(cotacaoPacotes);
        JOptionPane.showMessageDialog(rootPane, "Cotação Salva e Enviada para Consultor");
        emitirEmailGerencial(cotacaoPacotes);
        this.dispose();

    }//GEN-LAST:event_confirmajButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adljTextField;
    private javax.swing.JCheckBox carrojCheckBox;
    private javax.swing.JCheckBox casaljCheckBox;
    private javax.swing.JComboBox categoriajComboBox;
    private javax.swing.JTextField chd10jTextField;
    private javax.swing.JTextField chd5jTextField;
    private javax.swing.JButton confirmajButton;
    private com.toedter.calendar.JDateChooser dataIdajDateChooser;
    private com.toedter.calendar.JDateChooser dataRetornojDateChooser;
    private javax.swing.JTextField destinojTextField;
    private javax.swing.JCheckBox duplojCheckBox;
    private javax.swing.JTextField entregajTextField;
    private javax.swing.JTextField infjTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nomeClientejTextField;
    private javax.swing.JTextArea observacaojTextArea;
    private javax.swing.JTextField origemClientejTextField;
    private javax.swing.JTextField origemjTextField;
    private javax.swing.JCheckBox pacoteCompletojCheckBox;
    private javax.swing.JCheckBox pacoteTerrestrejCheckBox;
    private javax.swing.JCheckBox quadruplojCheckBox;
    private javax.swing.JTextField retiradajTextField;
    private javax.swing.JCheckBox segurojCheckBox;
    private javax.swing.ButtonGroup tipoApartamentobuttonGroup;
    private javax.swing.ButtonGroup tipoPacotebuttonGroup;
    private javax.swing.JCheckBox triplojCheckBox;
    private javax.swing.JCheckBox twinjCheckBox;
    private javax.swing.JTextField valorjTextField;
    // End of variables declaration//GEN-END:variables

public void emitirEmailGerencial(Cotacaopacotes cotacaoPacotes) {
        String texto = "";
        texto = "Nova Cotação";
        String tipoPacote;
        if (cotacaoPacotes.getTipoPacote().equalsIgnoreCase("C")){
            tipoPacote = "Pacote Completo";
        }else tipoPacote = "Somente Terrestre";
        Formatacao.emitirEmailCotacaoPacotes(usuarioLogadoBean.getUnidadeNegocio().getNomeFantasia(),
                usuarioLogadoBean.getUsuario().getNome(), texto, tipoPacote);
    }

    public void visualizarCotacao(Viewconsultacotacaopacote cotacao){
        confirmajButton.setEnabled(false);
        origemClientejTextField.setText(cotacao.getOrgiemCliente());
        nomeClientejTextField.setText(cotacao.getCliente());
        dataIdajDateChooser.setDate(cotacao.getDataIda());
//        dataIdajDateChooser.setEnabled(false);
        dataRetornojDateChooser.setDate(cotacao.getDataRetorno());
  //      dataRetornojDateChooser.setEnabled(false);
        origemjTextField.setText(cotacao.getOrigram());
    //    origemjTextField.setEditable(false);
        destinojTextField.setText(cotacao.getDestino());
      //  destinojTextField.setEditable(false);
        if (cotacao.getTipoPacote().equalsIgnoreCase("C")){
            pacoteCompletojCheckBox.setSelected(true);
        }else pacoteTerrestrejCheckBox.setSelected(true);
        //pacoteCompletojCheckBox.setEnabled(false);
       // pacoteTerrestrejCheckBox.setEnabled(false);
        adljTextField.setText(String.valueOf(cotacao.getNumeroAdultos()));
        //adljTextField.setEditable(false);
        chd5jTextField.setText(String.valueOf(cotacao.getNumeroCriancas5()));
        //chd5jTextField.setEditable(false);
        chd10jTextField.setText(String.valueOf(cotacao.getNumeroCriancas10()));
        //chd10jTextField.setEditable(false);
        infjTextField.setText(String.valueOf(cotacao.getNumeroBebes()));
        //infjTextField.setEditable(false);
        categoriajComboBox.setSelectedItem(cotacao.getTipoHotel());
        //categoriajComboBox.setEnabled(false);
        if (cotacao.getTipoApartamento().equalsIgnoreCase("Duplo")){
            duplojCheckBox.setSelected(true);
        }else if (cotacao.getTipoApartamento().equalsIgnoreCase("Triplo")){
            triplojCheckBox.setSelected(true);
        }else if (cotacao.getTipoApartamento().equalsIgnoreCase("Quadruplo")){
            quadruplojCheckBox.setSelected(true);
        }else if (cotacao.getTipoApartamento().equalsIgnoreCase("Casal")){
            casaljCheckBox.setSelected(true);
        }else if (cotacao.getTipoApartamento().equalsIgnoreCase("Twin")){
            twinjCheckBox.setSelected(true);
        }
        //duplojCheckBox.setEnabled(false);
        //triplojCheckBox.setEnabled(false);
        //quadruplojCheckBox.setEnabled(false);
        //casaljCheckBox.setEnabled(false);
        //twinjCheckBox.setEnabled(false);
        if (cotacao.getSeguro().equalsIgnoreCase("X")){
            segurojCheckBox.setSelected(true);
        }else segurojCheckBox.setSelected(false);
        //segurojCheckBox.setEnabled(false);
        if (cotacao.getCarro().equalsIgnoreCase("X")){
            carrojCheckBox.setSelected(true);
        }else carrojCheckBox.setSelected(false);
        //carrojCheckBox.setEnabled(false);
        valorjTextField.setText(Formatacao.formatarFloatString(cotacao.getValorInvestimento()));
        //valorjTextField.setEditable(false);
    }
}
